/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { agentSessionsStop } from "../funcs/agentSessionsStop.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { AlienError } from "../models/errors/alienerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useAlienContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type AgentSessionsStopMutationVariables = {
  request: operations.StopAgentSessionRequest;
  options?: RequestOptions;
};

export type AgentSessionsStopMutationData = models.AgentSessionStopResponse;

export type AgentSessionsStopMutationError =
  | errors.APIError
  | AlienError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Stop (cancel) a running or queued ai-agent monitor session. Proxies to the ai-agent service, minting a fresh CLI session for the caller so the ai-agent's own auth applies. Idempotent — stopping an already-terminal session is a 200 no-op.
 */
export function useAgentSessionsStopMutation(
  options?: MutationHookOptions<
    AgentSessionsStopMutationData,
    AgentSessionsStopMutationError,
    AgentSessionsStopMutationVariables
  >,
): UseMutationResult<
  AgentSessionsStopMutationData,
  AgentSessionsStopMutationError,
  AgentSessionsStopMutationVariables
> {
  const client = useAlienContext();
  return useMutation({
    ...buildAgentSessionsStopMutation(client, options),
    ...options,
  });
}

export function mutationKeyAgentSessionsStop(): MutationKey {
  return ["@alienplatform/platform-api", "agentSessions", "stop"];
}

export function buildAgentSessionsStopMutation(
  client$: AlienCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: AgentSessionsStopMutationVariables,
  ) => Promise<AgentSessionsStopMutationData>;
} {
  return {
    mutationKey: mutationKeyAgentSessionsStop(),
    mutationFn: function agentSessionsStopMutationFn({
      request,
      options,
    }): Promise<AgentSessionsStopMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(agentSessionsStop(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
