/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { AlienError } from "../models/errors/alienerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useAlienContext } from "./_context.js";
import { QueryHookOptions, SuspenseQueryHookOptions } from "./_types.js";
import {
  BillingGetEntitlementsQueryData,
  buildBillingGetEntitlementsQuery,
  prefetchBillingGetEntitlements,
  queryKeyBillingGetEntitlements,
} from "./billingGetEntitlements.core.js";
export {
  type BillingGetEntitlementsQueryData,
  buildBillingGetEntitlementsQuery,
  prefetchBillingGetEntitlements,
  queryKeyBillingGetEntitlements,
};

export type BillingGetEntitlementsQueryError =
  | errors.APIError
  | AlienError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get the workspace billing entitlements used for product feature gates. Autumn is the source of truth; the response is served through the workspace billing read model with stale-cache fallback.
 */
export function useBillingGetEntitlements(
  request?: operations.GetWorkspaceBillingEntitlementsRequest | undefined,
  options?: QueryHookOptions<
    BillingGetEntitlementsQueryData,
    BillingGetEntitlementsQueryError
  >,
): UseQueryResult<
  BillingGetEntitlementsQueryData,
  BillingGetEntitlementsQueryError
> {
  const client = useAlienContext();
  return useQuery({
    ...buildBillingGetEntitlementsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get the workspace billing entitlements used for product feature gates. Autumn is the source of truth; the response is served through the workspace billing read model with stale-cache fallback.
 */
export function useBillingGetEntitlementsSuspense(
  request?: operations.GetWorkspaceBillingEntitlementsRequest | undefined,
  options?: SuspenseQueryHookOptions<
    BillingGetEntitlementsQueryData,
    BillingGetEntitlementsQueryError
  >,
): UseSuspenseQueryResult<
  BillingGetEntitlementsQueryData,
  BillingGetEntitlementsQueryError
> {
  const client = useAlienContext();
  return useSuspenseQuery({
    ...buildBillingGetEntitlementsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setBillingGetEntitlementsData(
  client: QueryClient,
  data: BillingGetEntitlementsQueryData,
): BillingGetEntitlementsQueryData | undefined {
  const key = queryKeyBillingGetEntitlements();

  return client.setQueryData<BillingGetEntitlementsQueryData>(key, data);
}

export function invalidateAllBillingGetEntitlements(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@alienplatform/platform-api", "billing", "getEntitlements"],
  });
}
