/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { commandsResolveTarget } from "../funcs/commandsResolveTarget.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type CommandsResolveTargetQueryData = models.ResolvedCommandTarget;

export function prefetchCommandsResolveTarget(
  queryClient: QueryClient,
  client$: AlienCore,
  request: operations.ResolveCommandTargetRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildCommandsResolveTargetQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildCommandsResolveTargetQuery(
  client$: AlienCore,
  request: operations.ResolveCommandTargetRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<CommandsResolveTargetQueryData>;
} {
  return {
    queryKey: queryKeyCommandsResolveTarget({
      deploymentId: request.deploymentId,
      target: request.target,
      command: request.command,
    }),
    queryFn: async function commandsResolveTargetQueryFn(
      ctx,
    ): Promise<CommandsResolveTargetQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(commandsResolveTarget(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyCommandsResolveTarget(
  parameters: {
    deploymentId: string;
    target?: string | undefined;
    command?: string | undefined;
  },
): QueryKey {
  return [
    "@alienplatform/platform-api",
    "commands",
    "resolveTarget",
    parameters,
  ];
}
