/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { containerRegistryGetContainerRegistryManagerSnapshot } from "../funcs/containerRegistryGetContainerRegistryManagerSnapshot.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type ContainerRegistryGetContainerRegistryManagerSnapshotQueryData =
  models.ContainerRegistryManagerSnapshot;

export function prefetchContainerRegistryGetContainerRegistryManagerSnapshot(
  queryClient: QueryClient,
  client$: AlienCore,
  request: operations.GetContainerRegistryManagerSnapshotRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildContainerRegistryGetContainerRegistryManagerSnapshotQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildContainerRegistryGetContainerRegistryManagerSnapshotQuery(
  client$: AlienCore,
  request: operations.GetContainerRegistryManagerSnapshotRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<ContainerRegistryGetContainerRegistryManagerSnapshotQueryData>;
} {
  return {
    queryKey: queryKeyContainerRegistryGetContainerRegistryManagerSnapshot(
      request.id,
    ),
    queryFn:
      async function containerRegistryGetContainerRegistryManagerSnapshotQueryFn(
        ctx,
      ): Promise<
        ContainerRegistryGetContainerRegistryManagerSnapshotQueryData
      > {
        const sig = combineSignals(
          ctx.signal,
          options?.signal,
          options?.fetchOptions?.signal,
        );
        const mergedOptions = {
          ...options?.fetchOptions,
          ...options,
          signal: sig,
        };

        return unwrapAsync(containerRegistryGetContainerRegistryManagerSnapshot(
          client$,
          request,
          mergedOptions,
        ));
      },
  };
}

export function queryKeyContainerRegistryGetContainerRegistryManagerSnapshot(
  id: string,
): QueryKey {
  return [
    "@alienplatform/platform-api",
    "container-registry",
    "getContainerRegistryManagerSnapshot",
    id,
  ];
}
