/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { deploymentsList } from "../funcs/deploymentsList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type DeploymentsListQueryData = operations.ListDeploymentsResponse;

export function prefetchDeploymentsList(
  queryClient: QueryClient,
  client$: AlienCore,
  request?: operations.ListDeploymentsRequest | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildDeploymentsListQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildDeploymentsListQuery(
  client$: AlienCore,
  request?: operations.ListDeploymentsRequest | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<DeploymentsListQueryData>;
} {
  return {
    queryKey: queryKeyDeploymentsList({
      project: request?.project,
      deploymentGroup: request?.deploymentGroup,
      name: request?.name,
      managerId: request?.managerId,
      purpose: request?.purpose,
      search: request?.search,
      status: request?.status,
      environment: request?.environment,
      include: request?.include,
      limit: request?.limit,
      cursor: request?.cursor,
    }),
    queryFn: async function deploymentsListQueryFn(
      ctx,
    ): Promise<DeploymentsListQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(deploymentsList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyDeploymentsList(
  parameters: {
    project?: string | undefined;
    deploymentGroup?: string | undefined;
    name?: string | undefined;
    managerId?: string | undefined;
    purpose?: models.DeploymentPurpose | undefined;
    search?: string | undefined;
    status?: Array<operations.ListDeploymentsStatus> | undefined;
    environment?: Array<operations.ListDeploymentsEnvironment> | undefined;
    include?: Array<operations.ListDeploymentsInclude> | undefined;
    limit?: number | undefined;
    cursor?: string | undefined;
  },
): QueryKey {
  return ["@alienplatform/platform-api", "deployments", "list", parameters];
}
