/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { deploymentGroupsCreateDeploymentGroup } from "../funcs/deploymentGroupsCreateDeploymentGroup.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { AlienError } from "../models/errors/alienerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useAlienContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type DeploymentGroupsCreateDeploymentGroupMutationVariables = {
  request?: models.CreateDeploymentGroupRequest | undefined;
  options?: RequestOptions;
};

export type DeploymentGroupsCreateDeploymentGroupMutationData =
  models.DeploymentGroup;

export type DeploymentGroupsCreateDeploymentGroupMutationError =
  | errors.APIError
  | AlienError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Create a new deployment group
 */
export function useDeploymentGroupsCreateDeploymentGroupMutation(
  options?: MutationHookOptions<
    DeploymentGroupsCreateDeploymentGroupMutationData,
    DeploymentGroupsCreateDeploymentGroupMutationError,
    DeploymentGroupsCreateDeploymentGroupMutationVariables
  >,
): UseMutationResult<
  DeploymentGroupsCreateDeploymentGroupMutationData,
  DeploymentGroupsCreateDeploymentGroupMutationError,
  DeploymentGroupsCreateDeploymentGroupMutationVariables
> {
  const client = useAlienContext();
  return useMutation({
    ...buildDeploymentGroupsCreateDeploymentGroupMutation(client, options),
    ...options,
  });
}

export function mutationKeyDeploymentGroupsCreateDeploymentGroup(): MutationKey {
  return [
    "@alienplatform/platform-api",
    "deployment-groups",
    "createDeploymentGroup",
  ];
}

export function buildDeploymentGroupsCreateDeploymentGroupMutation(
  client$: AlienCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: DeploymentGroupsCreateDeploymentGroupMutationVariables,
  ) => Promise<DeploymentGroupsCreateDeploymentGroupMutationData>;
} {
  return {
    mutationKey: mutationKeyDeploymentGroupsCreateDeploymentGroup(),
    mutationFn: function deploymentGroupsCreateDeploymentGroupMutationFn({
      request,
      options,
    }): Promise<DeploymentGroupsCreateDeploymentGroupMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(deploymentGroupsCreateDeploymentGroup(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
