/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { deploymentGroupsPutExternalAIBinding } from "../funcs/deploymentGroupsPutExternalAIBinding.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { AlienError } from "../models/errors/alienerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useAlienContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type DeploymentGroupsPutExternalAIBindingMutationVariables = {
  request: operations.PutExternalAIBindingRequest;
  options?: RequestOptions;
};

export type DeploymentGroupsPutExternalAIBindingMutationData =
  models.ExternalAIBinding;

export type DeploymentGroupsPutExternalAIBindingMutationError =
  | errors.APIError
  | AlienError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Connect or rotate an external AI provider key
 */
export function useDeploymentGroupsPutExternalAIBindingMutation(
  options?: MutationHookOptions<
    DeploymentGroupsPutExternalAIBindingMutationData,
    DeploymentGroupsPutExternalAIBindingMutationError,
    DeploymentGroupsPutExternalAIBindingMutationVariables
  >,
): UseMutationResult<
  DeploymentGroupsPutExternalAIBindingMutationData,
  DeploymentGroupsPutExternalAIBindingMutationError,
  DeploymentGroupsPutExternalAIBindingMutationVariables
> {
  const client = useAlienContext();
  return useMutation({
    ...buildDeploymentGroupsPutExternalAIBindingMutation(client, options),
    ...options,
  });
}

export function mutationKeyDeploymentGroupsPutExternalAIBinding(): MutationKey {
  return [
    "@alienplatform/platform-api",
    "deployment-groups",
    "putExternalAIBinding",
  ];
}

export function buildDeploymentGroupsPutExternalAIBindingMutation(
  client$: AlienCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: DeploymentGroupsPutExternalAIBindingMutationVariables,
  ) => Promise<DeploymentGroupsPutExternalAIBindingMutationData>;
} {
  return {
    mutationKey: mutationKeyDeploymentGroupsPutExternalAIBinding(),
    mutationFn: function deploymentGroupsPutExternalAIBindingMutationFn({
      request,
      options,
    }): Promise<DeploymentGroupsPutExternalAIBindingMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(deploymentGroupsPutExternalAIBinding(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
