/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { deploymentGroupsDeleteExternalAIBinding } from "../funcs/deploymentGroupsDeleteExternalAIBinding.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { AlienError } from "../models/errors/alienerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useAlienContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type DeploymentGroupsDeleteExternalAIBindingMutationVariables = {
  request: operations.DeleteExternalAIBindingRequest;
  options?: RequestOptions;
};

export type DeploymentGroupsDeleteExternalAIBindingMutationData = void;

export type DeploymentGroupsDeleteExternalAIBindingMutationError =
  | errors.APIError
  | AlienError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Revoke the external AI connection
 */
export function useDeploymentGroupsDeleteExternalAIBindingMutation(
  options?: MutationHookOptions<
    DeploymentGroupsDeleteExternalAIBindingMutationData,
    DeploymentGroupsDeleteExternalAIBindingMutationError,
    DeploymentGroupsDeleteExternalAIBindingMutationVariables
  >,
): UseMutationResult<
  DeploymentGroupsDeleteExternalAIBindingMutationData,
  DeploymentGroupsDeleteExternalAIBindingMutationError,
  DeploymentGroupsDeleteExternalAIBindingMutationVariables
> {
  const client = useAlienContext();
  return useMutation({
    ...buildDeploymentGroupsDeleteExternalAIBindingMutation(client, options),
    ...options,
  });
}

export function mutationKeyDeploymentGroupsDeleteExternalAIBinding(): MutationKey {
  return [
    "@alienplatform/platform-api",
    "deployment-groups",
    "deleteExternalAIBinding",
  ];
}

export function buildDeploymentGroupsDeleteExternalAIBindingMutation(
  client$: AlienCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: DeploymentGroupsDeleteExternalAIBindingMutationVariables,
  ) => Promise<DeploymentGroupsDeleteExternalAIBindingMutationData>;
} {
  return {
    mutationKey: mutationKeyDeploymentGroupsDeleteExternalAIBinding(),
    mutationFn: function deploymentGroupsDeleteExternalAIBindingMutationFn({
      request,
      options,
    }): Promise<DeploymentGroupsDeleteExternalAIBindingMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(deploymentGroupsDeleteExternalAIBinding(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
