/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { AlienError } from "../models/errors/alienerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useAlienContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildDeploymentGetInfoQuery,
  DeploymentGetInfoQueryData,
  prefetchDeploymentGetInfo,
  queryKeyDeploymentGetInfo,
} from "./deploymentGetInfo.core.js";
export {
  buildDeploymentGetInfoQuery,
  type DeploymentGetInfoQueryData,
  prefetchDeploymentGetInfo,
  queryKeyDeploymentGetInfo,
};

export type DeploymentGetInfoQueryError =
  | errors.APIError
  | AlienError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get deployment information for the deployment portal. Accepts both deployment-scoped and deployment-group-scoped API keys. Returns project information, package status/outputs, and either deployment or deployment group details depending on the token type. Poll this endpoint to check if packages are ready.
 */
export function useDeploymentGetInfo(
  request?: operations.GetDeploymentInfoRequest | undefined,
  options?: QueryHookOptions<
    DeploymentGetInfoQueryData,
    DeploymentGetInfoQueryError
  >,
): UseQueryResult<DeploymentGetInfoQueryData, DeploymentGetInfoQueryError> {
  const client = useAlienContext();
  return useQuery({
    ...buildDeploymentGetInfoQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get deployment information for the deployment portal. Accepts both deployment-scoped and deployment-group-scoped API keys. Returns project information, package status/outputs, and either deployment or deployment group details depending on the token type. Poll this endpoint to check if packages are ready.
 */
export function useDeploymentGetInfoSuspense(
  request?: operations.GetDeploymentInfoRequest | undefined,
  options?: SuspenseQueryHookOptions<
    DeploymentGetInfoQueryData,
    DeploymentGetInfoQueryError
  >,
): UseSuspenseQueryResult<
  DeploymentGetInfoQueryData,
  DeploymentGetInfoQueryError
> {
  const client = useAlienContext();
  return useSuspenseQuery({
    ...buildDeploymentGetInfoQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setDeploymentGetInfoData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      platform?: operations.GetDeploymentInfoPlatform | undefined;
      setupItem?: operations.GetDeploymentInfoSetupItem | undefined;
      deploymentId?: string | undefined;
      updateOperationId?: string | undefined;
    },
  ],
  data: DeploymentGetInfoQueryData,
): DeploymentGetInfoQueryData | undefined {
  const key = queryKeyDeploymentGetInfo(...queryKeyBase);

  return client.setQueryData<DeploymentGetInfoQueryData>(key, data);
}

export function invalidateDeploymentGetInfo(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      platform?: operations.GetDeploymentInfoPlatform | undefined;
      setupItem?: operations.GetDeploymentInfoSetupItem | undefined;
      deploymentId?: string | undefined;
      updateOperationId?: string | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@alienplatform/platform-api",
      "deployment",
      "getInfo",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllDeploymentGetInfo(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@alienplatform/platform-api", "deployment", "getInfo"],
  });
}
