/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { dynamicContainersList } from "../funcs/dynamicContainersList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type DynamicContainersListQueryData = Array<
  models.DynamicContainerResponse
>;

export function prefetchDynamicContainersList(
  queryClient: QueryClient,
  client$: AlienCore,
  request: operations.ListDynamicContainersRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildDynamicContainersListQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildDynamicContainersListQuery(
  client$: AlienCore,
  request: operations.ListDynamicContainersRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<DynamicContainersListQueryData>;
} {
  return {
    queryKey: queryKeyDynamicContainersList(request.id),
    queryFn: async function dynamicContainersListQueryFn(
      ctx,
    ): Promise<DynamicContainersListQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(dynamicContainersList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyDynamicContainersList(id: string): QueryKey {
  return ["@alienplatform/platform-api", "dynamicContainers", "list", id];
}
