/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { AlienError } from "../models/errors/alienerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useAlienContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildGetDeploymentCredentialRotationQuery,
  GetDeploymentCredentialRotationQueryData,
  prefetchGetDeploymentCredentialRotation,
  queryKeyGetDeploymentCredentialRotation,
} from "./getDeploymentCredentialRotation.core.js";
export {
  buildGetDeploymentCredentialRotationQuery,
  type GetDeploymentCredentialRotationQueryData,
  prefetchGetDeploymentCredentialRotation,
  queryKeyGetDeploymentCredentialRotation,
};

export type GetDeploymentCredentialRotationQueryError =
  | errors.APIError
  | AlienError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

export function useGetDeploymentCredentialRotation(
  request: operations.GetDeploymentCredentialRotationRequest,
  options?: QueryHookOptions<
    GetDeploymentCredentialRotationQueryData,
    GetDeploymentCredentialRotationQueryError
  >,
): UseQueryResult<
  GetDeploymentCredentialRotationQueryData,
  GetDeploymentCredentialRotationQueryError
> {
  const client = useAlienContext();
  return useQuery({
    ...buildGetDeploymentCredentialRotationQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function useGetDeploymentCredentialRotationSuspense(
  request: operations.GetDeploymentCredentialRotationRequest,
  options?: SuspenseQueryHookOptions<
    GetDeploymentCredentialRotationQueryData,
    GetDeploymentCredentialRotationQueryError
  >,
): UseSuspenseQueryResult<
  GetDeploymentCredentialRotationQueryData,
  GetDeploymentCredentialRotationQueryError
> {
  const client = useAlienContext();
  return useSuspenseQuery({
    ...buildGetDeploymentCredentialRotationQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setGetDeploymentCredentialRotationData(
  client: QueryClient,
  queryKeyBase: [id: string],
  data: GetDeploymentCredentialRotationQueryData,
): GetDeploymentCredentialRotationQueryData | undefined {
  const key = queryKeyGetDeploymentCredentialRotation(...queryKeyBase);

  return client.setQueryData<GetDeploymentCredentialRotationQueryData>(
    key,
    data,
  );
}

export function invalidateGetDeploymentCredentialRotation(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[id: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@alienplatform/platform-api",
      "getDeploymentCredentialRotation",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllGetDeploymentCredentialRotation(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@alienplatform/platform-api",
      "getDeploymentCredentialRotation",
    ],
  });
}
