/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { incidentsList } from "../funcs/incidentsList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type IncidentsListQueryData = models.IncidentListResponse;

export function prefetchIncidentsList(
  queryClient: QueryClient,
  client$: AlienCore,
  request?: operations.ListIncidentsRequest | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildIncidentsListQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildIncidentsListQuery(
  client$: AlienCore,
  request?: operations.ListIncidentsRequest | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<IncidentsListQueryData>;
} {
  return {
    queryKey: queryKeyIncidentsList({
      projectId: request?.projectId,
      status: request?.status,
      search: request?.search,
      limit: request?.limit,
      cursor: request?.cursor,
    }),
    queryFn: async function incidentsListQueryFn(
      ctx,
    ): Promise<IncidentsListQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(incidentsList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyIncidentsList(
  parameters: {
    projectId?: string | undefined;
    status?: operations.ListIncidentsStatus | undefined;
    search?: string | undefined;
    limit?: number | undefined;
    cursor?: string | undefined;
  },
): QueryKey {
  return ["@alienplatform/platform-api", "incidents", "list", parameters];
}
