/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { managersGenerateManagerBindingToken } from "../funcs/managersGenerateManagerBindingToken.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { AlienError } from "../models/errors/alienerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useAlienContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ManagersGenerateManagerBindingTokenMutationVariables = {
  id: string;
  generateManagerBindingTokenRequest: models.GenerateManagerBindingTokenRequest;
  options?: RequestOptions;
};

export type ManagersGenerateManagerBindingTokenMutationData =
  models.GenerateManagerBindingTokenResponse;

export type ManagersGenerateManagerBindingTokenMutationError =
  | errors.APIError
  | AlienError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Generate a short-lived deployment-scoped token for resolving opted-in remote bindings through the currently assigned manager.
 */
export function useManagersGenerateManagerBindingTokenMutation(
  options?: MutationHookOptions<
    ManagersGenerateManagerBindingTokenMutationData,
    ManagersGenerateManagerBindingTokenMutationError,
    ManagersGenerateManagerBindingTokenMutationVariables
  >,
): UseMutationResult<
  ManagersGenerateManagerBindingTokenMutationData,
  ManagersGenerateManagerBindingTokenMutationError,
  ManagersGenerateManagerBindingTokenMutationVariables
> {
  const client = useAlienContext();
  return useMutation({
    ...buildManagersGenerateManagerBindingTokenMutation(client, options),
    ...options,
  });
}

export function mutationKeyManagersGenerateManagerBindingToken(): MutationKey {
  return [
    "@alienplatform/platform-api",
    "managers",
    "generateManagerBindingToken",
  ];
}

export function buildManagersGenerateManagerBindingTokenMutation(
  client$: AlienCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ManagersGenerateManagerBindingTokenMutationVariables,
  ) => Promise<ManagersGenerateManagerBindingTokenMutationData>;
} {
  return {
    mutationKey: mutationKeyManagersGenerateManagerBindingToken(),
    mutationFn: function managersGenerateManagerBindingTokenMutationFn({
      id,
      generateManagerBindingTokenRequest,
      options,
    }): Promise<ManagersGenerateManagerBindingTokenMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(managersGenerateManagerBindingToken(
        client$,
        id,
        generateManagerBindingTokenRequest,
        mergedOptions,
      ));
    },
  };
}
