/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { AlienError } from "../models/errors/alienerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useAlienContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildManagersListQuery,
  ManagersListQueryData,
  prefetchManagersList,
  queryKeyManagersList,
} from "./managersList.core.js";
export {
  buildManagersListQuery,
  type ManagersListQueryData,
  prefetchManagersList,
  queryKeyManagersList,
};

export type ManagersListQueryError =
  | errors.APIError
  | AlienError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Retrieve all managers.
 */
export function useManagersList(
  request?: operations.ListManagersRequest | undefined,
  options?: QueryHookOptions<ManagersListQueryData, ManagersListQueryError>,
): UseQueryResult<ManagersListQueryData, ManagersListQueryError> {
  const client = useAlienContext();
  return useQuery({
    ...buildManagersListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Retrieve all managers.
 */
export function useManagersListSuspense(
  request?: operations.ListManagersRequest | undefined,
  options?: SuspenseQueryHookOptions<
    ManagersListQueryData,
    ManagersListQueryError
  >,
): UseSuspenseQueryResult<ManagersListQueryData, ManagersListQueryError> {
  const client = useAlienContext();
  return useSuspenseQuery({
    ...buildManagersListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setManagersListData(
  client: QueryClient,
  queryKeyBase: [
    parameters: { search?: string | undefined; limit?: number | undefined },
  ],
  data: ManagersListQueryData,
): ManagersListQueryData | undefined {
  const key = queryKeyManagersList(...queryKeyBase);

  return client.setQueryData<ManagersListQueryData>(key, data);
}

export function invalidateManagersList(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: { search?: string | undefined; limit?: number | undefined }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@alienplatform/platform-api",
      "managers",
      "list",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllManagersList(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@alienplatform/platform-api", "managers", "list"],
  });
}
