/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { AlienError } from "../models/errors/alienerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useAlienContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildPackagesGetQuery,
  PackagesGetQueryData,
  prefetchPackagesGet,
  queryKeyPackagesGet,
} from "./packagesGet.core.js";
export {
  buildPackagesGetQuery,
  type PackagesGetQueryData,
  prefetchPackagesGet,
  queryKeyPackagesGet,
};

export type PackagesGetQueryError =
  | errors.APIError
  | AlienError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get details of a specific package.
 */
export function usePackagesGet(
  request: operations.GetPackageRequest,
  options?: QueryHookOptions<PackagesGetQueryData, PackagesGetQueryError>,
): UseQueryResult<PackagesGetQueryData, PackagesGetQueryError> {
  const client = useAlienContext();
  return useQuery({
    ...buildPackagesGetQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get details of a specific package.
 */
export function usePackagesGetSuspense(
  request: operations.GetPackageRequest,
  options?: SuspenseQueryHookOptions<
    PackagesGetQueryData,
    PackagesGetQueryError
  >,
): UseSuspenseQueryResult<PackagesGetQueryData, PackagesGetQueryError> {
  const client = useAlienContext();
  return useSuspenseQuery({
    ...buildPackagesGetQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setPackagesGetData(
  client: QueryClient,
  queryKeyBase: [id: string],
  data: PackagesGetQueryData,
): PackagesGetQueryData | undefined {
  const key = queryKeyPackagesGet(...queryKeyBase);

  return client.setQueryData<PackagesGetQueryData>(key, data);
}

export function invalidatePackagesGet(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[id: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@alienplatform/platform-api",
      "packages",
      "get",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllPackagesGet(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@alienplatform/platform-api", "packages", "get"],
  });
}
