/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { projectsUpdateGcpOAuthProvider } from "../funcs/projectsUpdateGcpOAuthProvider.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { AlienError } from "../models/errors/alienerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useAlienContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ProjectsUpdateGcpOAuthProviderMutationVariables = {
  idOrName: string;
  updateProjectGcpOAuthProvider?:
    | models.UpdateProjectGcpOAuthProvider
    | undefined;
  options?: RequestOptions;
};

export type ProjectsUpdateGcpOAuthProviderMutationData =
  models.ProjectGcpOAuthProvider;

export type ProjectsUpdateGcpOAuthProviderMutationError =
  | errors.APIError
  | AlienError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Update project-level Google Cloud OAuth provider settings.
 */
export function useProjectsUpdateGcpOAuthProviderMutation(
  options?: MutationHookOptions<
    ProjectsUpdateGcpOAuthProviderMutationData,
    ProjectsUpdateGcpOAuthProviderMutationError,
    ProjectsUpdateGcpOAuthProviderMutationVariables
  >,
): UseMutationResult<
  ProjectsUpdateGcpOAuthProviderMutationData,
  ProjectsUpdateGcpOAuthProviderMutationError,
  ProjectsUpdateGcpOAuthProviderMutationVariables
> {
  const client = useAlienContext();
  return useMutation({
    ...buildProjectsUpdateGcpOAuthProviderMutation(client, options),
    ...options,
  });
}

export function mutationKeyProjectsUpdateGcpOAuthProvider(): MutationKey {
  return ["@alienplatform/platform-api", "projects", "updateGcpOAuthProvider"];
}

export function buildProjectsUpdateGcpOAuthProviderMutation(
  client$: AlienCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ProjectsUpdateGcpOAuthProviderMutationVariables,
  ) => Promise<ProjectsUpdateGcpOAuthProviderMutationData>;
} {
  return {
    mutationKey: mutationKeyProjectsUpdateGcpOAuthProvider(),
    mutationFn: function projectsUpdateGcpOAuthProviderMutationFn({
      idOrName,
      updateProjectGcpOAuthProvider,
      options,
    }): Promise<ProjectsUpdateGcpOAuthProviderMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(projectsUpdateGcpOAuthProvider(
        client$,
        idOrName,
        updateProjectGcpOAuthProvider,
        mergedOptions,
      ));
    },
  };
}
