/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { AlienError } from "../models/errors/alienerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useAlienContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildProjectsGetDeploymentLinkSetupQuery,
  prefetchProjectsGetDeploymentLinkSetup,
  ProjectsGetDeploymentLinkSetupQueryData,
  queryKeyProjectsGetDeploymentLinkSetup,
} from "./projectsGetDeploymentLinkSetup.core.js";
export {
  buildProjectsGetDeploymentLinkSetupQuery,
  prefetchProjectsGetDeploymentLinkSetup,
  type ProjectsGetDeploymentLinkSetupQueryData,
  queryKeyProjectsGetDeploymentLinkSetup,
};

export type ProjectsGetDeploymentLinkSetupQueryError =
  | errors.APIError
  | AlienError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get the active release stack and portal-visible setup availability for deployment-link configuration.
 */
export function useProjectsGetDeploymentLinkSetup(
  request: operations.GetProjectDeploymentLinkSetupRequest,
  options?: QueryHookOptions<
    ProjectsGetDeploymentLinkSetupQueryData,
    ProjectsGetDeploymentLinkSetupQueryError
  >,
): UseQueryResult<
  ProjectsGetDeploymentLinkSetupQueryData,
  ProjectsGetDeploymentLinkSetupQueryError
> {
  const client = useAlienContext();
  return useQuery({
    ...buildProjectsGetDeploymentLinkSetupQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get the active release stack and portal-visible setup availability for deployment-link configuration.
 */
export function useProjectsGetDeploymentLinkSetupSuspense(
  request: operations.GetProjectDeploymentLinkSetupRequest,
  options?: SuspenseQueryHookOptions<
    ProjectsGetDeploymentLinkSetupQueryData,
    ProjectsGetDeploymentLinkSetupQueryError
  >,
): UseSuspenseQueryResult<
  ProjectsGetDeploymentLinkSetupQueryData,
  ProjectsGetDeploymentLinkSetupQueryError
> {
  const client = useAlienContext();
  return useSuspenseQuery({
    ...buildProjectsGetDeploymentLinkSetupQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setProjectsGetDeploymentLinkSetupData(
  client: QueryClient,
  queryKeyBase: [idOrName: string],
  data: ProjectsGetDeploymentLinkSetupQueryData,
): ProjectsGetDeploymentLinkSetupQueryData | undefined {
  const key = queryKeyProjectsGetDeploymentLinkSetup(...queryKeyBase);

  return client.setQueryData<ProjectsGetDeploymentLinkSetupQueryData>(
    key,
    data,
  );
}

export function invalidateProjectsGetDeploymentLinkSetup(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[idOrName: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@alienplatform/platform-api",
      "projects",
      "getDeploymentLinkSetup",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllProjectsGetDeploymentLinkSetup(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@alienplatform/platform-api",
      "projects",
      "getDeploymentLinkSetup",
    ],
  });
}
