/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { projectsCreate } from "../funcs/projectsCreate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { AlienError } from "../models/errors/alienerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useAlienContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ProjectsCreateMutationVariables = {
  request?: operations.CreateProjectRequest | undefined;
  options?: RequestOptions;
};

export type ProjectsCreateMutationData = operations.CreateProjectResponse;

export type ProjectsCreateMutationError =
  | errors.APIError
  | AlienError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Create a new project.
 */
export function useProjectsCreateMutation(
  options?: MutationHookOptions<
    ProjectsCreateMutationData,
    ProjectsCreateMutationError,
    ProjectsCreateMutationVariables
  >,
): UseMutationResult<
  ProjectsCreateMutationData,
  ProjectsCreateMutationError,
  ProjectsCreateMutationVariables
> {
  const client = useAlienContext();
  return useMutation({
    ...buildProjectsCreateMutation(client, options),
    ...options,
  });
}

export function mutationKeyProjectsCreate(): MutationKey {
  return ["@alienplatform/platform-api", "projects", "create"];
}

export function buildProjectsCreateMutation(
  client$: AlienCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ProjectsCreateMutationVariables,
  ) => Promise<ProjectsCreateMutationData>;
} {
  return {
    mutationKey: mutationKeyProjectsCreate(),
    mutationFn: function projectsCreateMutationFn({
      request,
      options,
    }): Promise<ProjectsCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(projectsCreate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
