/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { projectsGetAiUsage } from "../funcs/projectsGetAiUsage.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type ProjectsGetAiUsageQueryData = operations.GetProjectAiUsageResponse;

export function prefetchProjectsGetAiUsage(
  queryClient: QueryClient,
  client$: AlienCore,
  request: operations.GetProjectAiUsageRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildProjectsGetAiUsageQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildProjectsGetAiUsageQuery(
  client$: AlienCore,
  request: operations.GetProjectAiUsageRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<ProjectsGetAiUsageQueryData>;
} {
  return {
    queryKey: queryKeyProjectsGetAiUsage(request.idOrName, {
      range: request.range,
    }),
    queryFn: async function projectsGetAiUsageQueryFn(
      ctx,
    ): Promise<ProjectsGetAiUsageQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(projectsGetAiUsage(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyProjectsGetAiUsage(
  idOrName: string,
  parameters: {
    range?: operations.GetProjectAiUsageQueryParamRange | undefined;
  },
): QueryKey {
  return [
    "@alienplatform/platform-api",
    "projects",
    "getAiUsage",
    idOrName,
    parameters,
  ];
}
