/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { projectsList } from "../funcs/projectsList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type ProjectsListQueryData = operations.ListProjectsResponse;

export function prefetchProjectsList(
  queryClient: QueryClient,
  client$: AlienCore,
  request?: operations.ListProjectsRequest | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildProjectsListQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildProjectsListQuery(
  client$: AlienCore,
  request?: operations.ListProjectsRequest | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<ProjectsListQueryData>;
} {
  return {
    queryKey: queryKeyProjectsList({
      search: request?.search,
      include: request?.include,
      limit: request?.limit,
      cursor: request?.cursor,
    }),
    queryFn: async function projectsListQueryFn(
      ctx,
    ): Promise<ProjectsListQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(projectsList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyProjectsList(
  parameters: {
    search?: string | undefined;
    include?: Array<operations.ListProjectsInclude> | undefined;
    limit?: number | undefined;
    cursor?: string | undefined;
  },
): QueryKey {
  return ["@alienplatform/platform-api", "projects", "list", parameters];
}
