/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { projectsGetAiProviderHeaders } from "../funcs/projectsGetAiProviderHeaders.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type ProjectsGetAiProviderHeadersQueryData = models.AIProviderHeaders;

export function prefetchProjectsGetAiProviderHeaders(
  queryClient: QueryClient,
  client$: AlienCore,
  request: operations.GetProjectAiProviderHeadersRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildProjectsGetAiProviderHeadersQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildProjectsGetAiProviderHeadersQuery(
  client$: AlienCore,
  request: operations.GetProjectAiProviderHeadersRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<ProjectsGetAiProviderHeadersQueryData>;
} {
  return {
    queryKey: queryKeyProjectsGetAiProviderHeaders(request.idOrName),
    queryFn: async function projectsGetAiProviderHeadersQueryFn(
      ctx,
    ): Promise<ProjectsGetAiProviderHeadersQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(projectsGetAiProviderHeaders(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyProjectsGetAiProviderHeaders(
  idOrName: string,
): QueryKey {
  return [
    "@alienplatform/platform-api",
    "projects",
    "getAiProviderHeaders",
    idOrName,
  ];
}
