/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { projectsGet } from "../funcs/projectsGet.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type ProjectsGetQueryData = models.Project;

export function prefetchProjectsGet(
  queryClient: QueryClient,
  client$: AlienCore,
  request: operations.GetProjectRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildProjectsGetQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildProjectsGetQuery(
  client$: AlienCore,
  request: operations.GetProjectRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<ProjectsGetQueryData>;
} {
  return {
    queryKey: queryKeyProjectsGet(request.idOrName),
    queryFn: async function projectsGetQueryFn(
      ctx,
    ): Promise<ProjectsGetQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(projectsGet(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyProjectsGet(idOrName: string): QueryKey {
  return ["@alienplatform/platform-api", "projects", "get", idOrName];
}
