/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { projectsConfigureModels } from "../funcs/projectsConfigureModels.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { AlienError } from "../models/errors/alienerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useAlienContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ProjectsConfigureModelsMutationVariables = {
  idOrName: string;
  configureModelsRequest?: models.ConfigureModelsRequest | undefined;
  options?: RequestOptions;
};

export type ProjectsConfigureModelsMutationData =
  models.CapabilityMaterialization;

export type ProjectsConfigureModelsMutationError =
  | errors.APIError
  | AlienError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Configure customer-owned model providers without requiring an application Release.
 */
export function useProjectsConfigureModelsMutation(
  options?: MutationHookOptions<
    ProjectsConfigureModelsMutationData,
    ProjectsConfigureModelsMutationError,
    ProjectsConfigureModelsMutationVariables
  >,
): UseMutationResult<
  ProjectsConfigureModelsMutationData,
  ProjectsConfigureModelsMutationError,
  ProjectsConfigureModelsMutationVariables
> {
  const client = useAlienContext();
  return useMutation({
    ...buildProjectsConfigureModelsMutation(client, options),
    ...options,
  });
}

export function mutationKeyProjectsConfigureModels(): MutationKey {
  return ["@alienplatform/platform-api", "projects", "configureModels"];
}

export function buildProjectsConfigureModelsMutation(
  client$: AlienCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ProjectsConfigureModelsMutationVariables,
  ) => Promise<ProjectsConfigureModelsMutationData>;
} {
  return {
    mutationKey: mutationKeyProjectsConfigureModels(),
    mutationFn: function projectsConfigureModelsMutationFn({
      idOrName,
      configureModelsRequest,
      options,
    }): Promise<ProjectsConfigureModelsMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(projectsConfigureModels(
        client$,
        idOrName,
        configureModelsRequest,
        mergedOptions,
      ));
    },
  };
}
