/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { AlienError } from "../models/errors/alienerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useAlienContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildProjectsGetDeploymentPortalDomainQuery,
  prefetchProjectsGetDeploymentPortalDomain,
  ProjectsGetDeploymentPortalDomainQueryData,
  queryKeyProjectsGetDeploymentPortalDomain,
} from "./projectsGetDeploymentPortalDomain.core.js";
export {
  buildProjectsGetDeploymentPortalDomainQuery,
  prefetchProjectsGetDeploymentPortalDomain,
  type ProjectsGetDeploymentPortalDomainQueryData,
  queryKeyProjectsGetDeploymentPortalDomain,
};

export type ProjectsGetDeploymentPortalDomainQueryError =
  | errors.APIError
  | AlienError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get the deployment portal domain binding for a project.
 */
export function useProjectsGetDeploymentPortalDomain(
  request: operations.GetProjectDeploymentPortalDomainRequest,
  options?: QueryHookOptions<
    ProjectsGetDeploymentPortalDomainQueryData,
    ProjectsGetDeploymentPortalDomainQueryError
  >,
): UseQueryResult<
  ProjectsGetDeploymentPortalDomainQueryData,
  ProjectsGetDeploymentPortalDomainQueryError
> {
  const client = useAlienContext();
  return useQuery({
    ...buildProjectsGetDeploymentPortalDomainQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get the deployment portal domain binding for a project.
 */
export function useProjectsGetDeploymentPortalDomainSuspense(
  request: operations.GetProjectDeploymentPortalDomainRequest,
  options?: SuspenseQueryHookOptions<
    ProjectsGetDeploymentPortalDomainQueryData,
    ProjectsGetDeploymentPortalDomainQueryError
  >,
): UseSuspenseQueryResult<
  ProjectsGetDeploymentPortalDomainQueryData,
  ProjectsGetDeploymentPortalDomainQueryError
> {
  const client = useAlienContext();
  return useSuspenseQuery({
    ...buildProjectsGetDeploymentPortalDomainQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setProjectsGetDeploymentPortalDomainData(
  client: QueryClient,
  queryKeyBase: [idOrName: string],
  data: ProjectsGetDeploymentPortalDomainQueryData,
): ProjectsGetDeploymentPortalDomainQueryData | undefined {
  const key = queryKeyProjectsGetDeploymentPortalDomain(...queryKeyBase);

  return client.setQueryData<ProjectsGetDeploymentPortalDomainQueryData>(
    key,
    data,
  );
}

export function invalidateProjectsGetDeploymentPortalDomain(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[idOrName: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@alienplatform/platform-api",
      "projects",
      "getDeploymentPortalDomain",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllProjectsGetDeploymentPortalDomain(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@alienplatform/platform-api",
      "projects",
      "getDeploymentPortalDomain",
    ],
  });
}
