/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { AlienCore } from "../core.js";
import { releasesList } from "../funcs/releasesList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type ReleasesListQueryData = operations.ListReleasesResponse;

export function prefetchReleasesList(
  queryClient: QueryClient,
  client$: AlienCore,
  request?: operations.ListReleasesRequest | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildReleasesListQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildReleasesListQuery(
  client$: AlienCore,
  request?: operations.ListReleasesRequest | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<ReleasesListQueryData>;
} {
  return {
    queryKey: queryKeyReleasesList({
      project: request?.project,
      channel: request?.channel,
      allChannels: request?.allChannels,
      include: request?.include,
      search: request?.search,
      branch: request?.branch,
      author: request?.author,
      createdAfter: request?.createdAfter,
      createdBefore: request?.createdBefore,
      limit: request?.limit,
      cursor: request?.cursor,
    }),
    queryFn: async function releasesListQueryFn(
      ctx,
    ): Promise<ReleasesListQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(releasesList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyReleasesList(
  parameters: {
    project?: string | null | undefined;
    channel?: string | null | undefined;
    allChannels?: operations.AllChannels | undefined;
    include?: Array<operations.ListReleasesInclude> | undefined;
    search?: string | null | undefined;
    branch?: string | null | undefined;
    author?: string | null | undefined;
    createdAfter?: Date | null | undefined;
    createdBefore?: Date | null | undefined;
    limit?: number | undefined;
    cursor?: string | undefined;
  },
): QueryKey {
  return ["@alienplatform/platform-api", "releases", "list", parameters];
}
