workflowVersion: 1.0.0
speakeasyVersion: 1.680.11
sources:
  platform-api:
    inputs:
      - location: ../openapi.json
targets:
  platform-typescript:
    target: typescript
    source: platform-api
