packages:
  - packages/*
  - client-sdks/platform/typescript
  - client-sdks/manager/typescript
  - crates/alien-test-app
  - crates/alien-bindings-node
  - tests/e2e/test-apps/*

overrides:
  '@alienplatform/sdk': link:packages/sdk
  '@alienplatform/core': link:packages/core
  '@alienplatform/typescript-config': link:packages/config-typescript
  '@alienplatform/testing': link:packages/testing
  '@alienplatform/platform-api': link:client-sdks/platform/typescript
