[package]
name = "alien-infra-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license-file.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
alien-core = { workspace = true }
alien-error = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
pem = { workspace = true }
