/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { credentialsResolveCredentials } from "../funcs/credentialsResolveCredentials.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Credentials extends ClientSDK {
  async resolveCredentials(
    request: models.ResolveCredentialsRequest,
    options?: RequestOptions,
  ): Promise<models.ResolveCredentialsResponse> {
    return unwrapAsync(credentialsResolveCredentials(
      this,
      request,
      options,
    ));
  }
}
