/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deploymentsCreateDeployment } from "../funcs/deploymentsCreateDeployment.js";
import { deploymentsDeleteDeployment } from "../funcs/deploymentsDeleteDeployment.js";
import { deploymentsGetDeployment } from "../funcs/deploymentsGetDeployment.js";
import { deploymentsGetDeploymentBundleSources } from "../funcs/deploymentsGetDeploymentBundleSources.js";
import { deploymentsGetDeploymentInfo } from "../funcs/deploymentsGetDeploymentInfo.js";
import { deploymentsGetDeploymentLogs } from "../funcs/deploymentsGetDeploymentLogs.js";
import { deploymentsGetDeploymentRouting } from "../funcs/deploymentsGetDeploymentRouting.js";
import { deploymentsGetDeploymentTarget } from "../funcs/deploymentsGetDeploymentTarget.js";
import { deploymentsImportDeploymentStatus } from "../funcs/deploymentsImportDeploymentStatus.js";
import { deploymentsListDeployments } from "../funcs/deploymentsListDeployments.js";
import { deploymentsRedeploy } from "../funcs/deploymentsRedeploy.js";
import { deploymentsRetryDeployment } from "../funcs/deploymentsRetryDeployment.js";
import { deploymentsSetDeploymentChannel } from "../funcs/deploymentsSetDeploymentChannel.js";
import { deploymentsSetDeploymentPin } from "../funcs/deploymentsSetDeploymentPin.js";
import { deploymentsSignDeploymentBundle } from "../funcs/deploymentsSignDeploymentBundle.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Deployments extends ClientSDK {
  async listDeployments(
    request?: operations.ListDeploymentsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListDeploymentsResponse> {
    return unwrapAsync(deploymentsListDeployments(
      this,
      request,
      options,
    ));
  }

  /**
   * Every handler in this file runs `auth::require_auth(&state, &headers)`
   * and then threads `&subject` into the `DeploymentStore` calls. Embedders
   * that proxy to an upstream API can use the subject's `bearer_token` for
   * passthrough; single-tenant impls ignore it. See the trait doc on
   * [`DeploymentStore`] for the full convention.
   *
   * @remarks
   * `POST /v1/deployments` — Inbound: workspace / project / dg bearer (or
   * authenticated user). Deployment-scoped tokens cannot create deployments.
   */
  async createDeployment(
    request: models.CreateDeploymentRequest,
    options?: RequestOptions,
  ): Promise<models.CreateDeploymentResponse> {
    return unwrapAsync(deploymentsCreateDeployment(
      this,
      request,
      options,
    ));
  }

  async getDeployment(
    request: operations.GetDeploymentRequest,
    options?: RequestOptions,
  ): Promise<models.DeploymentResponse> {
    return unwrapAsync(deploymentsGetDeployment(
      this,
      request,
      options,
    ));
  }

  async signDeploymentBundle(
    id: string,
    bundleSignatureRequest: models.BundleSignatureRequest,
    options?: RequestOptions,
  ): Promise<models.BundleSignatureResponse> {
    return unwrapAsync(deploymentsSignDeploymentBundle(
      this,
      id,
      bundleSignatureRequest,
      options,
    ));
  }

  async getDeploymentBundleSources(
    request: operations.GetDeploymentBundleSourcesRequest,
    options?: RequestOptions,
  ): Promise<models.BundleSources> {
    return unwrapAsync(deploymentsGetDeploymentBundleSources(
      this,
      request,
      options,
    ));
  }

  async setDeploymentChannel(
    id: string,
    setDeploymentChannelRequest: models.SetDeploymentChannelRequest,
    options?: RequestOptions,
  ): Promise<models.DeploymentRoutingResponse> {
    return unwrapAsync(deploymentsSetDeploymentChannel(
      this,
      id,
      setDeploymentChannelRequest,
      options,
    ));
  }

  async deleteDeployment(
    id: string,
    deleteDeploymentRequest: models.DeleteDeploymentRequest,
    options?: RequestOptions,
  ): Promise<models.DeleteDeploymentResponse> {
    return unwrapAsync(deploymentsDeleteDeployment(
      this,
      id,
      deleteDeploymentRequest,
      options,
    ));
  }

  async getDeploymentInfo(
    request: operations.GetDeploymentInfoRequest,
    options?: RequestOptions,
  ): Promise<models.DeploymentInfoResponse> {
    return unwrapAsync(deploymentsGetDeploymentInfo(
      this,
      request,
      options,
    ));
  }

  async getDeploymentLogs(
    request: operations.GetDeploymentLogsRequest,
    options?: RequestOptions,
  ): Promise<models.RecentLogsResponse> {
    return unwrapAsync(deploymentsGetDeploymentLogs(
      this,
      request,
      options,
    ));
  }

  async setDeploymentPin(
    id: string,
    setDeploymentPinRequest: models.SetDeploymentPinRequest,
    options?: RequestOptions,
  ): Promise<models.DeploymentRoutingResponse> {
    return unwrapAsync(deploymentsSetDeploymentPin(
      this,
      id,
      setDeploymentPinRequest,
      options,
    ));
  }

  async redeploy(
    request: operations.RedeployRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(deploymentsRedeploy(
      this,
      request,
      options,
    ));
  }

  async retryDeployment(
    request: operations.RetryDeploymentRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(deploymentsRetryDeployment(
      this,
      request,
      options,
    ));
  }

  async getDeploymentRouting(
    request: operations.GetDeploymentRoutingRequest,
    options?: RequestOptions,
  ): Promise<models.DeploymentRoutingResponse> {
    return unwrapAsync(deploymentsGetDeploymentRouting(
      this,
      request,
      options,
    ));
  }

  async importDeploymentStatus(
    id: string,
    statusReport: models.StatusReport,
    options?: RequestOptions,
  ): Promise<models.StatusReportResponse> {
    return unwrapAsync(deploymentsImportDeploymentStatus(
      this,
      id,
      statusReport,
      options,
    ));
  }

  async getDeploymentTarget(
    request: operations.GetDeploymentTargetRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(deploymentsGetDeploymentTarget(
      this,
      request,
      options,
    ));
  }
}
