/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { releasesCreateManagerReleaseChannel } from "../funcs/releasesCreateManagerReleaseChannel.js";
import { releasesCreateRelease } from "../funcs/releasesCreateRelease.js";
import { releasesDeleteManagerReleaseChannel } from "../funcs/releasesDeleteManagerReleaseChannel.js";
import { releasesGetLatestRelease } from "../funcs/releasesGetLatestRelease.js";
import { releasesGetRelease } from "../funcs/releasesGetRelease.js";
import { releasesListManagerReleaseChannels } from "../funcs/releasesListManagerReleaseChannels.js";
import { releasesListReleases } from "../funcs/releasesListReleases.js";
import { releasesPromoteManagerRelease } from "../funcs/releasesPromoteManagerRelease.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Releases extends ClientSDK {
  async listManagerReleaseChannels(
    options?: RequestOptions,
  ): Promise<models.ListReleaseChannelsResponse> {
    return unwrapAsync(releasesListManagerReleaseChannels(
      this,
      options,
    ));
  }

  async createManagerReleaseChannel(
    request: models.CreateReleaseChannelRequest,
    options?: RequestOptions,
  ): Promise<models.ReleaseChannelResponse> {
    return unwrapAsync(releasesCreateManagerReleaseChannel(
      this,
      request,
      options,
    ));
  }

  async deleteManagerReleaseChannel(
    request: operations.DeleteManagerReleaseChannelRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(releasesDeleteManagerReleaseChannel(
      this,
      request,
      options,
    ));
  }

  /**
   * `GET /v1/releases` — Inbound: workspace / project bearer (or authenticated
   * user). Outbound: caller bearer (passthrough). Returns only releases the
   * caller may read.
   */
  async listReleases(
    options?: RequestOptions,
  ): Promise<models.ListReleasesResponse> {
    return unwrapAsync(releasesListReleases(
      this,
      options,
    ));
  }

  async createRelease(
    request: models.CreateReleaseRequest,
    options?: RequestOptions,
  ): Promise<models.ReleaseResponse> {
    return unwrapAsync(releasesCreateRelease(
      this,
      request,
      options,
    ));
  }

  async getLatestRelease(
    options?: RequestOptions,
  ): Promise<models.ReleaseResponse> {
    return unwrapAsync(releasesGetLatestRelease(
      this,
      options,
    ));
  }

  async getRelease(
    request: operations.GetReleaseRequest,
    options?: RequestOptions,
  ): Promise<models.ReleaseResponse> {
    return unwrapAsync(releasesGetRelease(
      this,
      request,
      options,
    ));
  }

  async promoteManagerRelease(
    id: string,
    promoteReleaseRequest: models.PromoteReleaseRequest,
    options?: RequestOptions,
  ): Promise<models.ReleaseChannelResponse> {
    return unwrapAsync(releasesPromoteManagerRelease(
      this,
      id,
      promoteReleaseRequest,
      options,
    ));
  }
}
