/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AgentSessionStopResponse = {
  jobId: string;
  status: string;
  canceled: boolean;
};

/** @internal */
export const AgentSessionStopResponse$inboundSchema: z.ZodType<
  AgentSessionStopResponse,
  unknown
> = z.object({
  jobId: z.string(),
  status: z.string(),
  canceled: z.boolean(),
});

export function agentSessionStopResponseFromJSON(
  jsonString: string,
): SafeParseResult<AgentSessionStopResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentSessionStopResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentSessionStopResponse' from JSON`,
  );
}
