/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AgentSessionEventsTruncatedEventPayload = {
  limit: number;
};

export type AgentSessionEventsTruncatedEvent = {
  seq: number;
  createdAt: string;
  type: "events_truncated";
  payload: AgentSessionEventsTruncatedEventPayload;
};

/** @internal */
export const AgentSessionEventsTruncatedEventPayload$inboundSchema: z.ZodType<
  AgentSessionEventsTruncatedEventPayload,
  unknown
> = z.object({
  limit: z.number(),
});

export function agentSessionEventsTruncatedEventPayloadFromJSON(
  jsonString: string,
): SafeParseResult<
  AgentSessionEventsTruncatedEventPayload,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AgentSessionEventsTruncatedEventPayload$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AgentSessionEventsTruncatedEventPayload' from JSON`,
  );
}

/** @internal */
export const AgentSessionEventsTruncatedEvent$inboundSchema: z.ZodType<
  AgentSessionEventsTruncatedEvent,
  unknown
> = z.object({
  seq: z.number(),
  createdAt: z.string(),
  type: z.literal("events_truncated"),
  payload: z.lazy(() => AgentSessionEventsTruncatedEventPayload$inboundSchema),
});

export function agentSessionEventsTruncatedEventFromJSON(
  jsonString: string,
): SafeParseResult<AgentSessionEventsTruncatedEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentSessionEventsTruncatedEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentSessionEventsTruncatedEvent' from JSON`,
  );
}
