/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AgentSessionListItem,
  AgentSessionListItem$inboundSchema,
} from "./agentsessionlistitem.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AgentSessionListResponse = {
  sessions: Array<AgentSessionListItem>;
};

/** @internal */
export const AgentSessionListResponse$inboundSchema: z.ZodType<
  AgentSessionListResponse,
  unknown
> = z.object({
  sessions: z.array(AgentSessionListItem$inboundSchema),
});

export function agentSessionListResponseFromJSON(
  jsonString: string,
): SafeParseResult<AgentSessionListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentSessionListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentSessionListResponse' from JSON`,
  );
}
