/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4"
import { safeParse } from "../lib/schemas.js"
import type { Result as SafeParseResult } from "../types/fp.js"
import type { SDKValidationError } from "./errors/sdkvalidationerror.js"

export type CommandDeploymentGroupInfo = {
  id: string
  name: string
}

/** @internal */
export const CommandDeploymentGroupInfo$inboundSchema: z.ZodType<
  CommandDeploymentGroupInfo,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
})

export function commandDeploymentGroupInfoFromJSON(
  jsonString: string,
): SafeParseResult<CommandDeploymentGroupInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    x => CommandDeploymentGroupInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CommandDeploymentGroupInfo' from JSON`,
  )
}
