/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreateFirstPartyDeploymentSessionResponse = {
  /**
   * The deployment-group session token
   */
  token: string;
};

/** @internal */
export const CreateFirstPartyDeploymentSessionResponse$inboundSchema: z.ZodType<
  CreateFirstPartyDeploymentSessionResponse,
  unknown
> = z.object({
  token: z.string(),
});

export function createFirstPartyDeploymentSessionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CreateFirstPartyDeploymentSessionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreateFirstPartyDeploymentSessionResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreateFirstPartyDeploymentSessionResponse' from JSON`,
  );
}
