/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DebugSessionPublicErrorContext5 = string | number | boolean;

export type DebugSessionPublicErrorContext4 = string | number | boolean;

export type DebugSessionPublicErrorContext6 =
  | string
  | number
  | boolean
  | Array<string | number | boolean>
  | { [k: string]: string | number | boolean };

export type DebugSessionPublicErrorContext2 = string | number | boolean;

export type DebugSessionPublicErrorContext1 = string | number | boolean;

export type DebugSessionPublicErrorContext3 =
  | string
  | number
  | boolean
  | Array<string | number | boolean>
  | { [k: string]: string | number | boolean };

export type DebugSessionPublicErrorContext =
  | string
  | number
  | boolean
  | Array<
    string | number | boolean | Array<string | number | boolean> | {
      [k: string]: string | number | boolean;
    }
  >
  | {
    [k: string]:
      | string
      | number
      | boolean
      | Array<string | number | boolean>
      | { [k: string]: string | number | boolean };
  };

/** @internal */
export const DebugSessionPublicErrorContext5$inboundSchema: z.ZodType<
  DebugSessionPublicErrorContext5,
  unknown
> = z.union([z.string(), z.number(), z.boolean()]);

export function debugSessionPublicErrorContext5FromJSON(
  jsonString: string,
): SafeParseResult<DebugSessionPublicErrorContext5, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DebugSessionPublicErrorContext5$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DebugSessionPublicErrorContext5' from JSON`,
  );
}

/** @internal */
export const DebugSessionPublicErrorContext4$inboundSchema: z.ZodType<
  DebugSessionPublicErrorContext4,
  unknown
> = z.union([z.string(), z.number(), z.boolean()]);

export function debugSessionPublicErrorContext4FromJSON(
  jsonString: string,
): SafeParseResult<DebugSessionPublicErrorContext4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DebugSessionPublicErrorContext4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DebugSessionPublicErrorContext4' from JSON`,
  );
}

/** @internal */
export const DebugSessionPublicErrorContext6$inboundSchema: z.ZodType<
  DebugSessionPublicErrorContext6,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.array(z.union([z.string(), z.number(), z.boolean()])),
  z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])),
]);

export function debugSessionPublicErrorContext6FromJSON(
  jsonString: string,
): SafeParseResult<DebugSessionPublicErrorContext6, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DebugSessionPublicErrorContext6$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DebugSessionPublicErrorContext6' from JSON`,
  );
}

/** @internal */
export const DebugSessionPublicErrorContext2$inboundSchema: z.ZodType<
  DebugSessionPublicErrorContext2,
  unknown
> = z.union([z.string(), z.number(), z.boolean()]);

export function debugSessionPublicErrorContext2FromJSON(
  jsonString: string,
): SafeParseResult<DebugSessionPublicErrorContext2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DebugSessionPublicErrorContext2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DebugSessionPublicErrorContext2' from JSON`,
  );
}

/** @internal */
export const DebugSessionPublicErrorContext1$inboundSchema: z.ZodType<
  DebugSessionPublicErrorContext1,
  unknown
> = z.union([z.string(), z.number(), z.boolean()]);

export function debugSessionPublicErrorContext1FromJSON(
  jsonString: string,
): SafeParseResult<DebugSessionPublicErrorContext1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DebugSessionPublicErrorContext1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DebugSessionPublicErrorContext1' from JSON`,
  );
}

/** @internal */
export const DebugSessionPublicErrorContext3$inboundSchema: z.ZodType<
  DebugSessionPublicErrorContext3,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.array(z.union([z.string(), z.number(), z.boolean()])),
  z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])),
]);

export function debugSessionPublicErrorContext3FromJSON(
  jsonString: string,
): SafeParseResult<DebugSessionPublicErrorContext3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DebugSessionPublicErrorContext3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DebugSessionPublicErrorContext3' from JSON`,
  );
}

/** @internal */
export const DebugSessionPublicErrorContext$inboundSchema: z.ZodType<
  DebugSessionPublicErrorContext,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.array(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.array(z.union([z.string(), z.number(), z.boolean()])),
      z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])),
    ]),
  ),
  z.record(
    z.string(),
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.array(z.union([z.string(), z.number(), z.boolean()])),
      z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])),
    ]),
  ),
]);

export function debugSessionPublicErrorContextFromJSON(
  jsonString: string,
): SafeParseResult<DebugSessionPublicErrorContext, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DebugSessionPublicErrorContext$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DebugSessionPublicErrorContext' from JSON`,
  );
}
