/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DebugSessionDeploymentDeploymentGroup = {
  /**
   * Unique identifier for the deployment group.
   */
  id: string;
  name: string;
};

/**
 * Represents the target cloud platform.
 */
export const DebugSessionDeploymentPlatform = {
  Aws: "aws",
  Gcp: "gcp",
  Azure: "azure",
  Kubernetes: "kubernetes",
  Machines: "machines",
  Local: "local",
  Test: "test",
} as const;
/**
 * Represents the target cloud platform.
 */
export type DebugSessionDeploymentPlatform = ClosedEnum<
  typeof DebugSessionDeploymentPlatform
>;

export const DebugSessionDeploymentPlatformTest = {
  Test: "test",
} as const;
export type DebugSessionDeploymentPlatformTest = ClosedEnum<
  typeof DebugSessionDeploymentPlatformTest
>;

/**
 * Test platform environment information (mock)
 */
export type DebugSessionDeploymentEnvironmentInfoTest = {
  /**
   * Test identifier for this environment
   */
  testId: string;
  platform: DebugSessionDeploymentPlatformTest;
};

export const DebugSessionDeploymentPlatformLocal = {
  Local: "local",
} as const;
export type DebugSessionDeploymentPlatformLocal = ClosedEnum<
  typeof DebugSessionDeploymentPlatformLocal
>;

/**
 * Local platform environment information
 */
export type DebugSessionDeploymentEnvironmentInfoLocal = {
  /**
   * Architecture (e.g., "x86_64", "aarch64")
   */
  arch: string;
  /**
   * Hostname of the machine running the deployment
   */
  hostname: string;
  /**
   * Operating system (e.g., "linux", "macos", "windows")
   */
  os: string;
  platform: DebugSessionDeploymentPlatformLocal;
};

export const DebugSessionDeploymentPlatformAzure = {
  Azure: "azure",
} as const;
export type DebugSessionDeploymentPlatformAzure = ClosedEnum<
  typeof DebugSessionDeploymentPlatformAzure
>;

/**
 * Azure-specific environment information
 */
export type DebugSessionDeploymentEnvironmentInfoAzure = {
  /**
   * Azure location/region
   */
  location: string;
  /**
   * Azure subscription ID
   */
  subscriptionId: string;
  /**
   * Azure tenant ID
   */
  tenantId: string;
  platform: DebugSessionDeploymentPlatformAzure;
};

export const DebugSessionDeploymentPlatformGcp = {
  Gcp: "gcp",
} as const;
export type DebugSessionDeploymentPlatformGcp = ClosedEnum<
  typeof DebugSessionDeploymentPlatformGcp
>;

/**
 * GCP-specific environment information
 */
export type DebugSessionDeploymentEnvironmentInfoGcp = {
  /**
   * GCP project ID (e.g., "my-project")
   */
  projectId: string;
  /**
   * GCP project number (e.g., "123456789012")
   */
  projectNumber: string;
  /**
   * GCP region
   */
  region: string;
  platform: DebugSessionDeploymentPlatformGcp;
};

export const DebugSessionDeploymentPlatformAws = {
  Aws: "aws",
} as const;
export type DebugSessionDeploymentPlatformAws = ClosedEnum<
  typeof DebugSessionDeploymentPlatformAws
>;

/**
 * AWS-specific environment information
 */
export type DebugSessionDeploymentEnvironmentInfoAws = {
  /**
   * AWS account ID
   */
  accountId: string;
  /**
   * AWS region
   */
  region: string;
  platform: DebugSessionDeploymentPlatformAws;
};

/**
 * Platform-specific environment information
 */
export type DebugSessionDeploymentEnvironmentInfoUnion =
  | DebugSessionDeploymentEnvironmentInfoGcp
  | DebugSessionDeploymentEnvironmentInfoAzure
  | DebugSessionDeploymentEnvironmentInfoLocal
  | DebugSessionDeploymentEnvironmentInfoAws
  | DebugSessionDeploymentEnvironmentInfoTest
  | any;

export type DebugSessionDeployment = {
  /**
   * Unique identifier for the deployment.
   */
  id: string;
  name: string;
  deploymentGroup?: DebugSessionDeploymentDeploymentGroup | null | undefined;
  /**
   * Represents the target cloud platform.
   */
  platform?: DebugSessionDeploymentPlatform | null | undefined;
  /**
   * Platform-specific environment information
   */
  environmentInfo?:
    | DebugSessionDeploymentEnvironmentInfoGcp
    | DebugSessionDeploymentEnvironmentInfoAzure
    | DebugSessionDeploymentEnvironmentInfoLocal
    | DebugSessionDeploymentEnvironmentInfoAws
    | DebugSessionDeploymentEnvironmentInfoTest
    | any
    | null
    | undefined;
};

/** @internal */
export const DebugSessionDeploymentDeploymentGroup$inboundSchema: z.ZodType<
  DebugSessionDeploymentDeploymentGroup,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
});

export function debugSessionDeploymentDeploymentGroupFromJSON(
  jsonString: string,
): SafeParseResult<DebugSessionDeploymentDeploymentGroup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DebugSessionDeploymentDeploymentGroup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DebugSessionDeploymentDeploymentGroup' from JSON`,
  );
}

/** @internal */
export const DebugSessionDeploymentPlatform$inboundSchema: z.ZodEnum<
  typeof DebugSessionDeploymentPlatform
> = z.enum(DebugSessionDeploymentPlatform);

/** @internal */
export const DebugSessionDeploymentPlatformTest$inboundSchema: z.ZodEnum<
  typeof DebugSessionDeploymentPlatformTest
> = z.enum(DebugSessionDeploymentPlatformTest);

/** @internal */
export const DebugSessionDeploymentEnvironmentInfoTest$inboundSchema: z.ZodType<
  DebugSessionDeploymentEnvironmentInfoTest,
  unknown
> = z.object({
  testId: z.string(),
  platform: DebugSessionDeploymentPlatformTest$inboundSchema,
});

export function debugSessionDeploymentEnvironmentInfoTestFromJSON(
  jsonString: string,
): SafeParseResult<
  DebugSessionDeploymentEnvironmentInfoTest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DebugSessionDeploymentEnvironmentInfoTest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DebugSessionDeploymentEnvironmentInfoTest' from JSON`,
  );
}

/** @internal */
export const DebugSessionDeploymentPlatformLocal$inboundSchema: z.ZodEnum<
  typeof DebugSessionDeploymentPlatformLocal
> = z.enum(DebugSessionDeploymentPlatformLocal);

/** @internal */
export const DebugSessionDeploymentEnvironmentInfoLocal$inboundSchema:
  z.ZodType<DebugSessionDeploymentEnvironmentInfoLocal, unknown> = z.object({
    arch: z.string(),
    hostname: z.string(),
    os: z.string(),
    platform: DebugSessionDeploymentPlatformLocal$inboundSchema,
  });

export function debugSessionDeploymentEnvironmentInfoLocalFromJSON(
  jsonString: string,
): SafeParseResult<
  DebugSessionDeploymentEnvironmentInfoLocal,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DebugSessionDeploymentEnvironmentInfoLocal$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DebugSessionDeploymentEnvironmentInfoLocal' from JSON`,
  );
}

/** @internal */
export const DebugSessionDeploymentPlatformAzure$inboundSchema: z.ZodEnum<
  typeof DebugSessionDeploymentPlatformAzure
> = z.enum(DebugSessionDeploymentPlatformAzure);

/** @internal */
export const DebugSessionDeploymentEnvironmentInfoAzure$inboundSchema:
  z.ZodType<DebugSessionDeploymentEnvironmentInfoAzure, unknown> = z.object({
    location: z.string(),
    subscriptionId: z.string(),
    tenantId: z.string(),
    platform: DebugSessionDeploymentPlatformAzure$inboundSchema,
  });

export function debugSessionDeploymentEnvironmentInfoAzureFromJSON(
  jsonString: string,
): SafeParseResult<
  DebugSessionDeploymentEnvironmentInfoAzure,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DebugSessionDeploymentEnvironmentInfoAzure$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DebugSessionDeploymentEnvironmentInfoAzure' from JSON`,
  );
}

/** @internal */
export const DebugSessionDeploymentPlatformGcp$inboundSchema: z.ZodEnum<
  typeof DebugSessionDeploymentPlatformGcp
> = z.enum(DebugSessionDeploymentPlatformGcp);

/** @internal */
export const DebugSessionDeploymentEnvironmentInfoGcp$inboundSchema: z.ZodType<
  DebugSessionDeploymentEnvironmentInfoGcp,
  unknown
> = z.object({
  projectId: z.string(),
  projectNumber: z.string(),
  region: z.string(),
  platform: DebugSessionDeploymentPlatformGcp$inboundSchema,
});

export function debugSessionDeploymentEnvironmentInfoGcpFromJSON(
  jsonString: string,
): SafeParseResult<
  DebugSessionDeploymentEnvironmentInfoGcp,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DebugSessionDeploymentEnvironmentInfoGcp$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DebugSessionDeploymentEnvironmentInfoGcp' from JSON`,
  );
}

/** @internal */
export const DebugSessionDeploymentPlatformAws$inboundSchema: z.ZodEnum<
  typeof DebugSessionDeploymentPlatformAws
> = z.enum(DebugSessionDeploymentPlatformAws);

/** @internal */
export const DebugSessionDeploymentEnvironmentInfoAws$inboundSchema: z.ZodType<
  DebugSessionDeploymentEnvironmentInfoAws,
  unknown
> = z.object({
  accountId: z.string(),
  region: z.string(),
  platform: DebugSessionDeploymentPlatformAws$inboundSchema,
});

export function debugSessionDeploymentEnvironmentInfoAwsFromJSON(
  jsonString: string,
): SafeParseResult<
  DebugSessionDeploymentEnvironmentInfoAws,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DebugSessionDeploymentEnvironmentInfoAws$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DebugSessionDeploymentEnvironmentInfoAws' from JSON`,
  );
}

/** @internal */
export const DebugSessionDeploymentEnvironmentInfoUnion$inboundSchema:
  z.ZodType<DebugSessionDeploymentEnvironmentInfoUnion, unknown> = z.union([
    z.lazy(() => DebugSessionDeploymentEnvironmentInfoGcp$inboundSchema),
    z.lazy(() => DebugSessionDeploymentEnvironmentInfoAzure$inboundSchema),
    z.lazy(() => DebugSessionDeploymentEnvironmentInfoLocal$inboundSchema),
    z.lazy(() => DebugSessionDeploymentEnvironmentInfoAws$inboundSchema),
    z.lazy(() => DebugSessionDeploymentEnvironmentInfoTest$inboundSchema),
    z.any(),
  ]);

export function debugSessionDeploymentEnvironmentInfoUnionFromJSON(
  jsonString: string,
): SafeParseResult<
  DebugSessionDeploymentEnvironmentInfoUnion,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DebugSessionDeploymentEnvironmentInfoUnion$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DebugSessionDeploymentEnvironmentInfoUnion' from JSON`,
  );
}

/** @internal */
export const DebugSessionDeployment$inboundSchema: z.ZodType<
  DebugSessionDeployment,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  deploymentGroup: z.nullable(
    z.lazy(() => DebugSessionDeploymentDeploymentGroup$inboundSchema),
  ).optional(),
  platform: z.nullable(DebugSessionDeploymentPlatform$inboundSchema).optional(),
  environmentInfo: z.nullable(
    z.union([
      z.lazy(() => DebugSessionDeploymentEnvironmentInfoGcp$inboundSchema),
      z.lazy(() => DebugSessionDeploymentEnvironmentInfoAzure$inboundSchema),
      z.lazy(() => DebugSessionDeploymentEnvironmentInfoLocal$inboundSchema),
      z.lazy(() => DebugSessionDeploymentEnvironmentInfoAws$inboundSchema),
      z.lazy(() => DebugSessionDeploymentEnvironmentInfoTest$inboundSchema),
      z.any(),
    ]),
  ).optional(),
});

export function debugSessionDeploymentFromJSON(
  jsonString: string,
): SafeParseResult<DebugSessionDeployment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DebugSessionDeployment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DebugSessionDeployment' from JSON`,
  );
}
