/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DebugPackagePresignedURLs = {
  readUrl: string;
  writeUrl: string;
};

/** @internal */
export const DebugPackagePresignedURLs$inboundSchema: z.ZodType<
  DebugPackagePresignedURLs,
  unknown
> = z.object({
  readUrl: z.string(),
  writeUrl: z.string(),
});

export function debugPackagePresignedURLsFromJSON(
  jsonString: string,
): SafeParseResult<DebugPackagePresignedURLs, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DebugPackagePresignedURLs$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DebugPackagePresignedURLs' from JSON`,
  );
}
