/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../types/enums.js";

export const DeleteDeploymentRequestMode = {
  Clean: "clean",
  Detach: "detach",
  Forget: "forget",
} as const;
export type DeleteDeploymentRequestMode = ClosedEnum<
  typeof DeleteDeploymentRequestMode
>;

export type DeleteDeploymentRequest = {
  mode: DeleteDeploymentRequestMode;
};

/** @internal */
export const DeleteDeploymentRequestMode$outboundSchema: z.ZodEnum<
  typeof DeleteDeploymentRequestMode
> = z.enum(DeleteDeploymentRequestMode);

/** @internal */
export type DeleteDeploymentRequest$Outbound = {
  mode: string;
};

/** @internal */
export const DeleteDeploymentRequest$outboundSchema: z.ZodType<
  DeleteDeploymentRequest$Outbound,
  DeleteDeploymentRequest
> = z.object({
  mode: DeleteDeploymentRequestMode$outboundSchema,
});

export function deleteDeploymentRequestToJSON(
  deleteDeploymentRequest: DeleteDeploymentRequest,
): string {
  return JSON.stringify(
    DeleteDeploymentRequest$outboundSchema.parse(deleteDeploymentRequest),
  );
}
