/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DeploymentMachineCpu = {
  allocated: number;
  systemReserve: number;
  total: number;
};

export type DeploymentMachineMemory = {
  allocated: number;
  systemReserve: number;
  total: number;
};

export type Storage = {
  allocated: number;
  systemReserve: number;
  total: number;
};

export type DeploymentMachineDrainBlocker = {
  reason: string;
  workloadId?: string | null | undefined;
  workloadName?: string | null | undefined;
  replicaId?: string | null | undefined;
  schedulingMode?: string | null | undefined;
  state?: string | null | undefined;
};

export const NetworkHealth = {
  Unknown: "unknown",
  Healthy: "healthy",
  Degraded: "degraded",
} as const;
export type NetworkHealth = ClosedEnum<typeof NetworkHealth>;

export type WireguardMesh = {
  expectedPeerCount: number;
  reachablePeerCount: number;
  missingPeerMachineIds: Array<string>;
};

export type LocalOverride = {
  activeDigest?: string | null | undefined;
  actor?: string | null | undefined;
  baseAssignmentHash: string;
  baseDigest?: string | null | undefined;
  candidateDigest?: string | null | undefined;
  createdAt?: string | null | undefined;
  failureCategory?: string | null | undefined;
  fallbackDigest?: string | null | undefined;
  forcedStop?: boolean | null | undefined;
  healthySince?: string | null | undefined;
  incidentId?: string | null | undefined;
  lifecycle: string;
  phaseStartedAt?: string | null | undefined;
  replicaId: string;
  workloadName: string;
};

export type DeploymentMachine = {
  clusterResourceId: string;
  machineId: string;
  status: string;
  capacityGroup: string;
  zone: string;
  cpu: DeploymentMachineCpu;
  memory: DeploymentMachineMemory;
  storage?: Storage | null | undefined;
  drainBlockers: Array<DeploymentMachineDrainBlocker>;
  drainDeadlineAt?: string | null | undefined;
  drainForce: boolean;
  drainRequestedAt?: string | null | undefined;
  drainedAt?: string | null | undefined;
  publicIp?: string | null | undefined;
  overlayIp?: string | null | undefined;
  lastHeartbeat: string;
  horizondVersion?: string | null | undefined;
  networkHealth?: NetworkHealth | undefined;
  wireguardMesh?: WireguardMesh | null | undefined;
  wireguardMeshObservedAt?: string | null | undefined;
  localOverrides: Array<LocalOverride>;
  localOverridesObservedAt?: string | null | undefined;
  replicaCount: number;
};

/** @internal */
export const DeploymentMachineCpu$inboundSchema: z.ZodType<
  DeploymentMachineCpu,
  unknown
> = z.object({
  allocated: z.number(),
  systemReserve: z.number(),
  total: z.number(),
});

export function deploymentMachineCpuFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentMachineCpu, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentMachineCpu$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentMachineCpu' from JSON`,
  );
}

/** @internal */
export const DeploymentMachineMemory$inboundSchema: z.ZodType<
  DeploymentMachineMemory,
  unknown
> = z.object({
  allocated: z.number(),
  systemReserve: z.number(),
  total: z.number(),
});

export function deploymentMachineMemoryFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentMachineMemory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentMachineMemory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentMachineMemory' from JSON`,
  );
}

/** @internal */
export const Storage$inboundSchema: z.ZodType<Storage, unknown> = z.object({
  allocated: z.number(),
  systemReserve: z.number(),
  total: z.number(),
});

export function storageFromJSON(
  jsonString: string,
): SafeParseResult<Storage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Storage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Storage' from JSON`,
  );
}

/** @internal */
export const DeploymentMachineDrainBlocker$inboundSchema: z.ZodType<
  DeploymentMachineDrainBlocker,
  unknown
> = z.object({
  reason: z.string(),
  workloadId: z.nullable(z.string()).optional(),
  workloadName: z.nullable(z.string()).optional(),
  replicaId: z.nullable(z.string()).optional(),
  schedulingMode: z.nullable(z.string()).optional(),
  state: z.nullable(z.string()).optional(),
});

export function deploymentMachineDrainBlockerFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentMachineDrainBlocker, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentMachineDrainBlocker$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentMachineDrainBlocker' from JSON`,
  );
}

/** @internal */
export const NetworkHealth$inboundSchema: z.ZodEnum<typeof NetworkHealth> = z
  .enum(NetworkHealth);

/** @internal */
export const WireguardMesh$inboundSchema: z.ZodType<WireguardMesh, unknown> = z
  .object({
    expectedPeerCount: z.int(),
    reachablePeerCount: z.int(),
    missingPeerMachineIds: z.array(z.string()),
  });

export function wireguardMeshFromJSON(
  jsonString: string,
): SafeParseResult<WireguardMesh, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WireguardMesh$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WireguardMesh' from JSON`,
  );
}

/** @internal */
export const LocalOverride$inboundSchema: z.ZodType<LocalOverride, unknown> = z
  .object({
    activeDigest: z.nullable(z.string()).optional(),
    actor: z.nullable(z.string()).optional(),
    baseAssignmentHash: z.string(),
    baseDigest: z.nullable(z.string()).optional(),
    candidateDigest: z.nullable(z.string()).optional(),
    createdAt: z.nullable(z.string()).optional(),
    failureCategory: z.nullable(z.string()).optional(),
    fallbackDigest: z.nullable(z.string()).optional(),
    forcedStop: z.nullable(z.boolean()).optional(),
    healthySince: z.nullable(z.string()).optional(),
    incidentId: z.nullable(z.string()).optional(),
    lifecycle: z.string(),
    phaseStartedAt: z.nullable(z.string()).optional(),
    replicaId: z.string(),
    workloadName: z.string(),
  });

export function localOverrideFromJSON(
  jsonString: string,
): SafeParseResult<LocalOverride, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LocalOverride$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LocalOverride' from JSON`,
  );
}

/** @internal */
export const DeploymentMachine$inboundSchema: z.ZodType<
  DeploymentMachine,
  unknown
> = z.object({
  clusterResourceId: z.string(),
  machineId: z.string(),
  status: z.string(),
  capacityGroup: z.string(),
  zone: z.string(),
  cpu: z.lazy(() => DeploymentMachineCpu$inboundSchema),
  memory: z.lazy(() => DeploymentMachineMemory$inboundSchema),
  storage: z.nullable(z.lazy(() => Storage$inboundSchema)).optional(),
  drainBlockers: z.array(
    z.lazy(() => DeploymentMachineDrainBlocker$inboundSchema),
  ),
  drainDeadlineAt: z.nullable(z.string()).optional(),
  drainForce: z.boolean(),
  drainRequestedAt: z.nullable(z.string()).optional(),
  drainedAt: z.nullable(z.string()).optional(),
  publicIp: z.nullable(z.string()).optional(),
  overlayIp: z.nullable(z.string()).optional(),
  lastHeartbeat: z.string(),
  horizondVersion: z.nullable(z.string()).optional(),
  networkHealth: NetworkHealth$inboundSchema.optional(),
  wireguardMesh: z.nullable(z.lazy(() => WireguardMesh$inboundSchema))
    .optional(),
  wireguardMeshObservedAt: z.nullable(z.string()).optional(),
  localOverrides: z.array(z.lazy(() => LocalOverride$inboundSchema)),
  localOverridesObservedAt: z.nullable(z.string()).optional(),
  replicaCount: z.int(),
});

export function deploymentMachineFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentMachine, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentMachine$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentMachine' from JSON`,
  );
}
