/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  DeploymentSetupMethod,
  DeploymentSetupMethod$inboundSchema,
  DeploymentSetupMethod$outboundSchema,
} from "./deploymentsetupmethod.js";
import {
  DeploymentSetupStackSettingsPolicy,
  DeploymentSetupStackSettingsPolicy$inboundSchema,
  DeploymentSetupStackSettingsPolicy$Outbound,
  DeploymentSetupStackSettingsPolicy$outboundSchema,
} from "./deploymentsetupstacksettingspolicy.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  KubernetesClusterSource,
  KubernetesClusterSource$inboundSchema,
  KubernetesClusterSource$outboundSchema,
} from "./kubernetesclustersource.js";

/**
 * Represents the target cloud platform.
 */
export const AllowedPlatform = {
  Aws: "aws",
  Gcp: "gcp",
  Azure: "azure",
  Kubernetes: "kubernetes",
  Machines: "machines",
  Local: "local",
  Test: "test",
} as const;
/**
 * Represents the target cloud platform.
 */
export type AllowedPlatform = ClosedEnum<typeof AllowedPlatform>;

export const AllowedKubernetesBasePlatform = {
  Aws: "aws",
  Gcp: "gcp",
  Azure: "azure",
  OnPrem: "on-prem",
} as const;
export type AllowedKubernetesBasePlatform = ClosedEnum<
  typeof AllowedKubernetesBasePlatform
>;

export type DeploymentSetupPolicy = {
  allowedPlatforms: Array<AllowedPlatform>;
  /**
   * Kubernetes base environments the recipient may target.
   */
  allowedKubernetesBasePlatforms?:
    | Array<AllowedKubernetesBasePlatform>
    | undefined;
  /**
   * Whether recipients may create a cluster, use an existing cluster, or both.
   */
  allowedKubernetesClusterSources?: Array<KubernetesClusterSource> | undefined;
  allowedSetupMethods: Array<DeploymentSetupMethod>;
  allowReleasePinning?: boolean | undefined;
  stackSettings?: DeploymentSetupStackSettingsPolicy | undefined;
};

/** @internal */
export const AllowedPlatform$inboundSchema: z.ZodEnum<typeof AllowedPlatform> =
  z.enum(AllowedPlatform);
/** @internal */
export const AllowedPlatform$outboundSchema: z.ZodEnum<typeof AllowedPlatform> =
  AllowedPlatform$inboundSchema;

/** @internal */
export const AllowedKubernetesBasePlatform$inboundSchema: z.ZodEnum<
  typeof AllowedKubernetesBasePlatform
> = z.enum(AllowedKubernetesBasePlatform);
/** @internal */
export const AllowedKubernetesBasePlatform$outboundSchema: z.ZodEnum<
  typeof AllowedKubernetesBasePlatform
> = AllowedKubernetesBasePlatform$inboundSchema;

/** @internal */
export const DeploymentSetupPolicy$inboundSchema: z.ZodType<
  DeploymentSetupPolicy,
  unknown
> = z.object({
  allowedPlatforms: z.array(AllowedPlatform$inboundSchema),
  allowedKubernetesBasePlatforms: z.array(
    AllowedKubernetesBasePlatform$inboundSchema,
  ).optional(),
  allowedKubernetesClusterSources: z.array(
    KubernetesClusterSource$inboundSchema,
  ).optional(),
  allowedSetupMethods: z.array(DeploymentSetupMethod$inboundSchema),
  allowReleasePinning: z.boolean().optional(),
  stackSettings: DeploymentSetupStackSettingsPolicy$inboundSchema.optional(),
});
/** @internal */
export type DeploymentSetupPolicy$Outbound = {
  allowedPlatforms: Array<string>;
  allowedKubernetesBasePlatforms?: Array<string> | undefined;
  allowedKubernetesClusterSources?: Array<string> | undefined;
  allowedSetupMethods: Array<string>;
  allowReleasePinning?: boolean | undefined;
  stackSettings?: DeploymentSetupStackSettingsPolicy$Outbound | undefined;
};

/** @internal */
export const DeploymentSetupPolicy$outboundSchema: z.ZodType<
  DeploymentSetupPolicy$Outbound,
  DeploymentSetupPolicy
> = z.object({
  allowedPlatforms: z.array(AllowedPlatform$outboundSchema),
  allowedKubernetesBasePlatforms: z.array(
    AllowedKubernetesBasePlatform$outboundSchema,
  ).optional(),
  allowedKubernetesClusterSources: z.array(
    KubernetesClusterSource$outboundSchema,
  ).optional(),
  allowedSetupMethods: z.array(DeploymentSetupMethod$outboundSchema),
  allowReleasePinning: z.boolean().optional(),
  stackSettings: DeploymentSetupStackSettingsPolicy$outboundSchema.optional(),
});

export function deploymentSetupPolicyToJSON(
  deploymentSetupPolicy: DeploymentSetupPolicy,
): string {
  return JSON.stringify(
    DeploymentSetupPolicy$outboundSchema.parse(deploymentSetupPolicy),
  );
}
export function deploymentSetupPolicyFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentSetupPolicy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentSetupPolicy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentSetupPolicy' from JSON`,
  );
}
