/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import {
  DeploymentSetupPolicy,
  DeploymentSetupPolicy$Outbound,
  DeploymentSetupPolicy$outboundSchema,
} from "./deploymentsetuppolicy.js";
import {
  EncryptedStackInputValue,
  EncryptedStackInputValue$Outbound,
  EncryptedStackInputValue$outboundSchema,
} from "./encryptedstackinputvalue.js";
import {
  EnvironmentVariableConfig,
  EnvironmentVariableConfig$Outbound,
  EnvironmentVariableConfig$outboundSchema,
} from "./environmentvariableconfig.js";

export type DeploymentSetupConfig = {
  metadata: { [k: string]: any | null };
  policy: DeploymentSetupPolicy;
  environmentVariables: Array<EnvironmentVariableConfig>;
  inputValues?: { [k: string]: EncryptedStackInputValue } | undefined;
  /**
   * Operator-pinned deployment subdomain for this setup token.
   */
  publicSubdomain?: string | undefined;
};

/** @internal */
export type DeploymentSetupConfig$Outbound = {
  metadata: { [k: string]: any | null };
  policy: DeploymentSetupPolicy$Outbound;
  environmentVariables: Array<EnvironmentVariableConfig$Outbound>;
  inputValues?: { [k: string]: EncryptedStackInputValue$Outbound } | undefined;
  publicSubdomain?: string | undefined;
};

/** @internal */
export const DeploymentSetupConfig$outboundSchema: z.ZodType<
  DeploymentSetupConfig$Outbound,
  DeploymentSetupConfig
> = z.object({
  metadata: z.record(z.string(), z.nullable(z.any())),
  policy: DeploymentSetupPolicy$outboundSchema,
  environmentVariables: z.array(EnvironmentVariableConfig$outboundSchema),
  inputValues: z.record(z.string(), EncryptedStackInputValue$outboundSchema)
    .optional(),
  publicSubdomain: z.string().optional(),
});

export function deploymentSetupConfigToJSON(
  deploymentSetupConfig: DeploymentSetupConfig,
): string {
  return JSON.stringify(
    DeploymentSetupConfig$outboundSchema.parse(deploymentSetupConfig),
  );
}
