/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../types/enums.js";

/**
 * Role for deployment group-scoped service accounts
 */
export const DeploymentGroupRole = {
  DeploymentGroupDeployer: "deployment-group.deployer",
} as const;
/**
 * Role for deployment group-scoped service accounts
 */
export type DeploymentGroupRole = ClosedEnum<typeof DeploymentGroupRole>;

/** @internal */
export const DeploymentGroupRole$inboundSchema: z.ZodEnum<
  typeof DeploymentGroupRole
> = z.enum(DeploymentGroupRole);
/** @internal */
export const DeploymentGroupRole$outboundSchema: z.ZodEnum<
  typeof DeploymentGroupRole
> = DeploymentGroupRole$inboundSchema;
