/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  DeploymentPortalDomain,
  DeploymentPortalDomain$inboundSchema,
} from "./deploymentportaldomain.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type DeploymentPortalDomainResponse = {
  deploymentPortalDomain: DeploymentPortalDomain | null;
};

/** @internal */
export const DeploymentPortalDomainResponse$inboundSchema: z.ZodType<
  DeploymentPortalDomainResponse,
  unknown
> = z.object({
  deploymentPortalDomain: z.nullable(DeploymentPortalDomain$inboundSchema),
});

export function deploymentPortalDomainResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentPortalDomainResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentPortalDomainResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentPortalDomainResponse' from JSON`,
  );
}
