/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const DomainStatus = {
  PendingZoneCreation: "pending-zone-creation",
  PendingVerification: "pending-verification",
  Verified: "verified",
  Failed: "failed",
  Deleting: "deleting",
} as const;
export type DomainStatus = ClosedEnum<typeof DomainStatus>;

export type Domain = {
  /**
   * Unique identifier for the domain.
   */
  id: string;
  /**
   * Unique identifier for the workspace.
   */
  workspaceId: string;
  domain: string;
  isSystem: boolean;
  hostedZoneId?: string | null | undefined;
  nameServers?: Array<string> | null | undefined;
  status: DomainStatus;
  error?: any | null | undefined;
  createdAt: Date;
  verifiedAt?: Date | null | undefined;
};

/** @internal */
export const DomainStatus$inboundSchema: z.ZodEnum<typeof DomainStatus> = z
  .enum(DomainStatus);

/** @internal */
export const Domain$inboundSchema: z.ZodType<Domain, unknown> = z.object({
  id: z.string(),
  workspaceId: z.string(),
  domain: z.string(),
  isSystem: z.boolean(),
  hostedZoneId: z.nullable(z.string()).optional(),
  nameServers: z.nullable(z.array(z.string())).optional(),
  status: DomainStatus$inboundSchema,
  error: z.nullable(z.any()).optional(),
  createdAt: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  verifiedAt: z.nullable(
    z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
});

export function domainFromJSON(
  jsonString: string,
): SafeParseResult<Domain, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Domain$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Domain' from JSON`,
  );
}
