/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type EnsureDeploymentGroupByNameRequest = {
  /**
   * Deployment group name.
   */
  name: string;
  /**
   * Project ID or name this deployment group belongs to
   */
  project: string;
  /**
   * Maximum number of deployments for newly created groups
   */
  maxDeployments?: number | undefined;
};

/** @internal */
export type EnsureDeploymentGroupByNameRequest$Outbound = {
  name: string;
  project: string;
  maxDeployments: number;
};

/** @internal */
export const EnsureDeploymentGroupByNameRequest$outboundSchema: z.ZodType<
  EnsureDeploymentGroupByNameRequest$Outbound,
  EnsureDeploymentGroupByNameRequest
> = z.object({
  name: z.string(),
  project: z.string(),
  maxDeployments: z.int().default(100),
});

export function ensureDeploymentGroupByNameRequestToJSON(
  ensureDeploymentGroupByNameRequest: EnsureDeploymentGroupByNameRequest,
): string {
  return JSON.stringify(
    EnsureDeploymentGroupByNameRequest$outboundSchema.parse(
      ensureDeploymentGroupByNameRequest,
    ),
  );
}
