/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../types/enums.js";
import {
  ImportSource,
  ImportSource$Outbound,
  ImportSource$outboundSchema,
} from "./importsource.js";

export const ForwardImportRequestMode = {
  Forward: "forward",
} as const;
export type ForwardImportRequestMode = ClosedEnum<
  typeof ForwardImportRequestMode
>;

export type ForwardImportRequest = {
  mode?: ForwardImportRequestMode | undefined;
  /**
   * Project ID or name. Required for user-session callers.
   */
  project?: string | undefined;
  /**
   * Required for user-session callers. Deployment-group tokens use their own group automatically.
   */
  deploymentGroupId?: string | undefined;
  /**
   * Manager ID. If omitted, the first suitable manager for the source platform is used.
   */
  managerId?: string | undefined;
  /**
   * Resolved distribution import payload
   */
  source: ImportSource;
};

/** @internal */
export const ForwardImportRequestMode$outboundSchema: z.ZodEnum<
  typeof ForwardImportRequestMode
> = z.enum(ForwardImportRequestMode);

/** @internal */
export type ForwardImportRequest$Outbound = {
  mode: string;
  project?: string | undefined;
  deploymentGroupId?: string | undefined;
  managerId?: string | undefined;
  source: ImportSource$Outbound;
};

/** @internal */
export const ForwardImportRequest$outboundSchema: z.ZodType<
  ForwardImportRequest$Outbound,
  ForwardImportRequest
> = z.object({
  mode: ForwardImportRequestMode$outboundSchema.default("forward"),
  project: z.string().optional(),
  deploymentGroupId: z.string().optional(),
  managerId: z.string().optional(),
  source: ImportSource$outboundSchema,
});

export function forwardImportRequestToJSON(
  forwardImportRequest: ForwardImportRequest,
): string {
  return JSON.stringify(
    ForwardImportRequest$outboundSchema.parse(forwardImportRequest),
  );
}
