/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const GenerateManagerTokenResponseTokenType = {
  Bearer: "Bearer",
} as const;
export type GenerateManagerTokenResponseTokenType = ClosedEnum<
  typeof GenerateManagerTokenResponseTokenType
>;

export type GenerateManagerTokenResponse = {
  /**
   * Platform JWT for authenticating with the manager
   */
  accessToken: string;
  /**
   * Token lifetime in seconds
   */
  expiresIn: number | null;
  tokenType: GenerateManagerTokenResponseTokenType;
  /**
   * Manager URL for direct access
   */
  managerUrl: string;
  /**
   * Log database ID (null if logs not configured)
   */
  databaseId: string | null;
  /**
   * Log control plane URL (null if logs not configured)
   */
  controlPlaneUrl: string | null;
};

/** @internal */
export const GenerateManagerTokenResponseTokenType$inboundSchema: z.ZodEnum<
  typeof GenerateManagerTokenResponseTokenType
> = z.enum(GenerateManagerTokenResponseTokenType);

/** @internal */
export const GenerateManagerTokenResponse$inboundSchema: z.ZodType<
  GenerateManagerTokenResponse,
  unknown
> = z.object({
  accessToken: z.string(),
  expiresIn: z.nullable(z.number()),
  tokenType: GenerateManagerTokenResponseTokenType$inboundSchema,
  managerUrl: z.string(),
  databaseId: z.nullable(z.string()),
  controlPlaneUrl: z.nullable(z.string()),
});

export function generateManagerTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<GenerateManagerTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenerateManagerTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenerateManagerTokenResponse' from JSON`,
  );
}
