/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type GenerateManagerTokenRequest = {
  /**
   * Project ID or name to scope token access to. When omitted, the token is scoped to all projects accessible by the current user.
   */
  project?: string | undefined;
};

/** @internal */
export type GenerateManagerTokenRequest$Outbound = {
  project?: string | undefined;
};

/** @internal */
export const GenerateManagerTokenRequest$outboundSchema: z.ZodType<
  GenerateManagerTokenRequest$Outbound,
  GenerateManagerTokenRequest
> = z.object({
  project: z.string().optional(),
});

export function generateManagerTokenRequestToJSON(
  generateManagerTokenRequest: GenerateManagerTokenRequest,
): string {
  return JSON.stringify(
    GenerateManagerTokenRequest$outboundSchema.parse(
      generateManagerTokenRequest,
    ),
  );
}
