/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const GitNamespaceType = {
  Team: "team",
  User: "user",
} as const;
export type GitNamespaceType = ClosedEnum<typeof GitNamespaceType>;

export const GitNamespaceProvider = {
  Github: "github",
} as const;
export type GitNamespaceProvider = ClosedEnum<typeof GitNamespaceProvider>;

export type GitNamespace = {
  id: number | null;
  name: string;
  slug: string;
  installationId: number | null;
  type: GitNamespaceType;
  provider: GitNamespaceProvider;
  createdAt: Date;
};

/** @internal */
export const GitNamespaceType$inboundSchema: z.ZodEnum<
  typeof GitNamespaceType
> = z.enum(GitNamespaceType);

/** @internal */
export const GitNamespaceProvider$inboundSchema: z.ZodEnum<
  typeof GitNamespaceProvider
> = z.enum(GitNamespaceProvider);

/** @internal */
export const GitNamespace$inboundSchema: z.ZodType<GitNamespace, unknown> = z
  .object({
    id: z.nullable(z.number()),
    name: z.string(),
    slug: z.string(),
    installationId: z.nullable(z.number()),
    type: GitNamespaceType$inboundSchema,
    provider: GitNamespaceProvider$inboundSchema,
    createdAt: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  });

export function gitNamespaceFromJSON(
  jsonString: string,
): SafeParseResult<GitNamespace, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GitNamespace$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GitNamespace' from JSON`,
  );
}
