/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Incident, Incident$inboundSchema } from "./incident.js";

export type IncidentListResponse = {
  items: Array<Incident>;
  nextCursor: string | null;
};

/** @internal */
export const IncidentListResponse$inboundSchema: z.ZodType<
  IncidentListResponse,
  unknown
> = z.object({
  items: z.array(Incident$inboundSchema),
  nextCursor: z.nullable(z.string()),
});

export function incidentListResponseFromJSON(
  jsonString: string,
): SafeParseResult<IncidentListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IncidentListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IncidentListResponse' from JSON`,
  );
}
