/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ObservedRemoteOperatorImageIdentitySource = {
  Package: "package",
  Configured: "configured",
} as const;
export type ObservedRemoteOperatorImageIdentitySource = ClosedEnum<
  typeof ObservedRemoteOperatorImageIdentitySource
>;

export type ObservedRemoteOperatorImageIdentity = {
  source: ObservedRemoteOperatorImageIdentitySource;
  packageId: string | null;
  packageVersion: string | null;
  image: string;
  digest: string;
  observedAt: Date;
};

/** @internal */
export const ObservedRemoteOperatorImageIdentitySource$inboundSchema: z.ZodEnum<
  typeof ObservedRemoteOperatorImageIdentitySource
> = z.enum(ObservedRemoteOperatorImageIdentitySource);

/** @internal */
export const ObservedRemoteOperatorImageIdentity$inboundSchema: z.ZodType<
  ObservedRemoteOperatorImageIdentity,
  unknown
> = z.object({
  source: ObservedRemoteOperatorImageIdentitySource$inboundSchema,
  packageId: z.nullable(z.string()),
  packageVersion: z.nullable(z.string()),
  image: z.string(),
  digest: z.string(),
  observedAt: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
});

export function observedRemoteOperatorImageIdentityFromJSON(
  jsonString: string,
): SafeParseResult<ObservedRemoteOperatorImageIdentity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ObservedRemoteOperatorImageIdentity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ObservedRemoteOperatorImageIdentity' from JSON`,
  );
}
