/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OperationsPermissionDiffSource,
  OperationsPermissionDiffSource$inboundSchema,
  OperationsPermissionDiffSource$Outbound,
  OperationsPermissionDiffSource$outboundSchema,
} from "./operationspermissiondiffsource.js";

/**
 * Where setup grants the permission: the configured project, or each Cloud Storage bucket the installer lists.
 */
export const OperationsGcpPermissionDiffGrantScope = {
  ProjectsDollarProjectName: "projects/${projectName}",
  ProjectsDollarProjectNameBucketsDollarResourceName:
    "projects/${projectName}/buckets/${resourceName}",
} as const;
/**
 * Where setup grants the permission: the configured project, or each Cloud Storage bucket the installer lists.
 */
export type OperationsGcpPermissionDiffGrantScope = ClosedEnum<
  typeof OperationsGcpPermissionDiffGrantScope
>;

export type OperationsGcpPermissionDiffGrant = {
  permission: string;
  /**
   * Where setup grants the permission: the configured project, or each Cloud Storage bucket the installer lists.
   */
  scope: OperationsGcpPermissionDiffGrantScope;
  sources: Array<OperationsPermissionDiffSource>;
};

/** @internal */
export const OperationsGcpPermissionDiffGrantScope$inboundSchema: z.ZodEnum<
  typeof OperationsGcpPermissionDiffGrantScope
> = z.enum(OperationsGcpPermissionDiffGrantScope);
/** @internal */
export const OperationsGcpPermissionDiffGrantScope$outboundSchema: z.ZodEnum<
  typeof OperationsGcpPermissionDiffGrantScope
> = OperationsGcpPermissionDiffGrantScope$inboundSchema;

/** @internal */
export const OperationsGcpPermissionDiffGrant$inboundSchema: z.ZodType<
  OperationsGcpPermissionDiffGrant,
  unknown
> = z.object({
  permission: z.string(),
  scope: OperationsGcpPermissionDiffGrantScope$inboundSchema,
  sources: z.array(OperationsPermissionDiffSource$inboundSchema),
});
/** @internal */
export type OperationsGcpPermissionDiffGrant$Outbound = {
  permission: string;
  scope: string;
  sources: Array<OperationsPermissionDiffSource$Outbound>;
};

/** @internal */
export const OperationsGcpPermissionDiffGrant$outboundSchema: z.ZodType<
  OperationsGcpPermissionDiffGrant$Outbound,
  OperationsGcpPermissionDiffGrant
> = z.object({
  permission: z.string(),
  scope: OperationsGcpPermissionDiffGrantScope$outboundSchema,
  sources: z.array(OperationsPermissionDiffSource$outboundSchema),
});

export function operationsGcpPermissionDiffGrantToJSON(
  operationsGcpPermissionDiffGrant: OperationsGcpPermissionDiffGrant,
): string {
  return JSON.stringify(
    OperationsGcpPermissionDiffGrant$outboundSchema.parse(
      operationsGcpPermissionDiffGrant,
    ),
  );
}
export function operationsGcpPermissionDiffGrantFromJSON(
  jsonString: string,
): SafeParseResult<OperationsGcpPermissionDiffGrant, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OperationsGcpPermissionDiffGrant$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OperationsGcpPermissionDiffGrant' from JSON`,
  );
}
