/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OperationsPermissionDiffSource,
  OperationsPermissionDiffSource$inboundSchema,
  OperationsPermissionDiffSource$Outbound,
  OperationsPermissionDiffSource$outboundSchema,
} from "./operationspermissiondiffsource.js";

export const OperationsAwsPermissionDiffStatementEffect = {
  Allow: "Allow",
  Deny: "Deny",
} as const;
export type OperationsAwsPermissionDiffStatementEffect = ClosedEnum<
  typeof OperationsAwsPermissionDiffStatementEffect
>;

export type OperationsAwsPermissionDiffStatement = {
  effect: OperationsAwsPermissionDiffStatementEffect;
  actions: Array<string>;
  resources: Array<string>;
  condition: { [k: string]: { [k: string]: string } } | null;
  sources: Array<OperationsPermissionDiffSource>;
};

/** @internal */
export const OperationsAwsPermissionDiffStatementEffect$inboundSchema:
  z.ZodEnum<typeof OperationsAwsPermissionDiffStatementEffect> = z.enum(
    OperationsAwsPermissionDiffStatementEffect,
  );
/** @internal */
export const OperationsAwsPermissionDiffStatementEffect$outboundSchema:
  z.ZodEnum<typeof OperationsAwsPermissionDiffStatementEffect> =
    OperationsAwsPermissionDiffStatementEffect$inboundSchema;

/** @internal */
export const OperationsAwsPermissionDiffStatement$inboundSchema: z.ZodType<
  OperationsAwsPermissionDiffStatement,
  unknown
> = z.object({
  effect: OperationsAwsPermissionDiffStatementEffect$inboundSchema,
  actions: z.array(z.string()),
  resources: z.array(z.string()),
  condition: z.nullable(z.record(z.string(), z.record(z.string(), z.string()))),
  sources: z.array(OperationsPermissionDiffSource$inboundSchema),
});
/** @internal */
export type OperationsAwsPermissionDiffStatement$Outbound = {
  effect: string;
  actions: Array<string>;
  resources: Array<string>;
  condition: { [k: string]: { [k: string]: string } } | null;
  sources: Array<OperationsPermissionDiffSource$Outbound>;
};

/** @internal */
export const OperationsAwsPermissionDiffStatement$outboundSchema: z.ZodType<
  OperationsAwsPermissionDiffStatement$Outbound,
  OperationsAwsPermissionDiffStatement
> = z.object({
  effect: OperationsAwsPermissionDiffStatementEffect$outboundSchema,
  actions: z.array(z.string()),
  resources: z.array(z.string()),
  condition: z.nullable(z.record(z.string(), z.record(z.string(), z.string()))),
  sources: z.array(OperationsPermissionDiffSource$outboundSchema),
});

export function operationsAwsPermissionDiffStatementToJSON(
  operationsAwsPermissionDiffStatement: OperationsAwsPermissionDiffStatement,
): string {
  return JSON.stringify(
    OperationsAwsPermissionDiffStatement$outboundSchema.parse(
      operationsAwsPermissionDiffStatement,
    ),
  );
}
export function operationsAwsPermissionDiffStatementFromJSON(
  jsonString: string,
): SafeParseResult<OperationsAwsPermissionDiffStatement, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      OperationsAwsPermissionDiffStatement$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OperationsAwsPermissionDiffStatement' from JSON`,
  );
}
