/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../types/enums.js";

/**
 * Optional setup method. Defaults to cloudformation for AWS, google-oauth for GCP, and terraform for Azure.
 */
export const PrivateManagerSetupMethod = {
  Cloudformation: "cloudformation",
  GoogleOauth: "google-oauth",
  Terraform: "terraform",
} as const;
/**
 * Optional setup method. Defaults to cloudformation for AWS, google-oauth for GCP, and terraform for Azure.
 */
export type PrivateManagerSetupMethod = ClosedEnum<
  typeof PrivateManagerSetupMethod
>;

/** @internal */
export const PrivateManagerSetupMethod$outboundSchema: z.ZodEnum<
  typeof PrivateManagerSetupMethod
> = z.enum(PrivateManagerSetupMethod);
