/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 16c89c7672a3
 */

import * as z from "zod/v4";
import { Verb, Verb$outboundSchema } from "./verb.js";

export type Rule = {
  apiGroup: string;
  resource: string;
  verbs: Array<Verb>;
  resourceNames?: Array<string> | undefined;
  reason: string;
};

/** @internal */
export type Rule$Outbound = {
  apiGroup: string;
  resource: string;
  verbs: Array<string>;
  resourceNames?: Array<string> | undefined;
  reason: string;
};

/** @internal */
export const Rule$outboundSchema: z.ZodType<Rule$Outbound, Rule> = z.object({
  apiGroup: z.string(),
  resource: z.string(),
  verbs: z.array(Verb$outboundSchema),
  resourceNames: z.array(z.string()).optional(),
  reason: z.string(),
});

export function ruleToJSON(rule: Rule): string {
  return JSON.stringify(Rule$outboundSchema.parse(rule));
}
