/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 37710d47f1b4
 */

import * as z from "zod/v4";

export type SetOperationsPluginEnabledRequest = {
  /**
   * Whether the plugin is distributed to this project's Operators.
   */
  enabled: boolean;
};

/** @internal */
export type SetOperationsPluginEnabledRequest$Outbound = {
  enabled: boolean;
};

/** @internal */
export const SetOperationsPluginEnabledRequest$outboundSchema: z.ZodType<
  SetOperationsPluginEnabledRequest$Outbound,
  SetOperationsPluginEnabledRequest
> = z.object({
  enabled: z.boolean(),
});

export function setOperationsPluginEnabledRequestToJSON(
  setOperationsPluginEnabledRequest: SetOperationsPluginEnabledRequest,
): string {
  return JSON.stringify(
    SetOperationsPluginEnabledRequest$outboundSchema.parse(
      setOperationsPluginEnabledRequest,
    ),
  );
}
