/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OperationsPermissionDiff,
  OperationsPermissionDiff$inboundSchema,
} from "./operationspermissiondiff.js";

export type SetOperationsPluginEnabledResponse = {
  name: string;
  builtin: boolean;
  enabled: boolean;
  /**
   * Cloud permission delta versus the previously enabled set.
   */
  permissionDiff: OperationsPermissionDiff;
};

/** @internal */
export const SetOperationsPluginEnabledResponse$inboundSchema: z.ZodType<
  SetOperationsPluginEnabledResponse,
  unknown
> = z.object({
  name: z.string(),
  builtin: z.boolean(),
  enabled: z.boolean(),
  permissionDiff: OperationsPermissionDiff$inboundSchema,
});

export function setOperationsPluginEnabledResponseFromJSON(
  jsonString: string,
): SafeParseResult<SetOperationsPluginEnabledResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SetOperationsPluginEnabledResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetOperationsPluginEnabledResponse' from JSON`,
  );
}
