/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type SupportedCloudRegions = {
  /**
   * AWS regions supported by this Alien environment.
   */
  aws: Array<string>;
  /**
   * GCP regions supported by this Alien environment.
   */
  gcp: Array<string>;
  /**
   * Azure locations supported by this Alien environment.
   */
  azure: Array<string>;
};

/** @internal */
export const SupportedCloudRegions$inboundSchema: z.ZodType<
  SupportedCloudRegions,
  unknown
> = z.object({
  aws: z.array(z.string()),
  gcp: z.array(z.string()),
  azure: z.array(z.string()),
});

export function supportedCloudRegionsFromJSON(
  jsonString: string,
): SafeParseResult<SupportedCloudRegions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SupportedCloudRegions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SupportedCloudRegions' from JSON`,
  );
}
