/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

/**
 * Request to release deployment lock
 */
export type SyncReleaseRequest = {
  /**
   * Deployment ID to release
   */
  deploymentId: string;
  /**
   * Session identifier to release
   */
  session: string;
  /**
   * Operation returned by acquire. Required when the lease carried update work.
   */
  operationId?: string | undefined;
  /**
   * Attempt returned by acquire. Required when the lease carried update work.
   */
  attemptId?: string | undefined;
};

/** @internal */
export type SyncReleaseRequest$Outbound = {
  deploymentId: string;
  session: string;
  operationId?: string | undefined;
  attemptId?: string | undefined;
};

/** @internal */
export const SyncReleaseRequest$outboundSchema: z.ZodType<
  SyncReleaseRequest$Outbound,
  SyncReleaseRequest
> = z.object({
  deploymentId: z.string(),
  session: z.string(),
  operationId: z.string().optional(),
  attemptId: z.string().optional(),
});

export function syncReleaseRequestToJSON(
  syncReleaseRequest: SyncReleaseRequest,
): string {
  return JSON.stringify(
    SyncReleaseRequest$outboundSchema.parse(syncReleaseRequest),
  );
}
