#[cfg(feature = "aws")]
pub mod aws_parameter_store;
#[cfg(feature = "azure")]
pub mod azure_key_vault;
#[cfg(feature = "gcp")]
pub mod gcp_secret_manager;
#[cfg(feature = "grpc")]
pub mod grpc;
#[cfg(feature = "kubernetes")]
pub mod kubernetes_secret;
#[cfg(feature = "local")]
pub mod local;

#[cfg(feature = "aws")]
pub use aws_parameter_store::*;
#[cfg(feature = "azure")]
pub use azure_key_vault::*;
#[cfg(feature = "gcp")]
pub use gcp_secret_manager::*;
#[cfg(feature = "grpc")]
pub use grpc::*;
#[cfg(feature = "kubernetes")]
pub use kubernetes_secret::*;
#[cfg(feature = "local")]
pub use local::*;
