[package]
name = "alien-gcp-compute-types"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
bon = { workspace = true }
serde = { workspace = true, features = ["derive"] }
