/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type CancelDeploymentVolumeRestoreGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type CancelDeploymentVolumeRestoreRequest = {
  /**
   * Unique identifier for the deployment.
   */
  id: string;
  /**
   * Unique identifier for the volume restore.
   */
  requestId: string;
};

/** @internal */
export type CancelDeploymentVolumeRestoreRequest$Outbound = {
  id: string;
  requestId: string;
};

/** @internal */
export const CancelDeploymentVolumeRestoreRequest$outboundSchema: z.ZodType<
  CancelDeploymentVolumeRestoreRequest$Outbound,
  CancelDeploymentVolumeRestoreRequest
> = z.object({
  id: z.string(),
  requestId: z.string(),
});

export function cancelDeploymentVolumeRestoreRequestToJSON(
  cancelDeploymentVolumeRestoreRequest: CancelDeploymentVolumeRestoreRequest,
): string {
  return JSON.stringify(
    CancelDeploymentVolumeRestoreRequest$outboundSchema.parse(
      cancelDeploymentVolumeRestoreRequest,
    ),
  );
}
