/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CreateManagerRequest = {
  /**
   * Workspace name. Defaults to your last workspace (user auth) or your API key's workspace (token auth). When using an API key, if provided, must match the key's workspace.
   */
  workspace?: string | undefined;
  newManagerRequest?: models.NewManagerRequest | undefined;
};

/**
 * Represents the target cloud platform.
 */
export const Target = {
  Aws: "aws",
  Gcp: "gcp",
  Azure: "azure",
  Kubernetes: "kubernetes",
  Local: "local",
  Test: "test",
} as const;
/**
 * Represents the target cloud platform.
 */
export type Target = ClosedEnum<typeof Target>;

export const CreateManagerPlatformKubernetes = {
  Kubernetes: "kubernetes",
} as const;
export type CreateManagerPlatformKubernetes = ClosedEnum<
  typeof CreateManagerPlatformKubernetes
>;

export type ManagementConfigKubernetes = {
  platform: CreateManagerPlatformKubernetes;
};

export const CreateManagerPlatformAzure = {
  Azure: "azure",
} as const;
export type CreateManagerPlatformAzure = ClosedEnum<
  typeof CreateManagerPlatformAzure
>;

/**
 * Azure management configuration extracted from stack settings
 */
export type ManagementConfigAzure = {
  /**
   * The principal ID of the service principal in the management account
   */
  managementPrincipalId: string;
  /**
   * The managing Azure Tenant ID for cross-tenant access
   */
  managingTenantId: string;
  platform: CreateManagerPlatformAzure;
};

export const CreateManagerPlatformGcp = {
  Gcp: "gcp",
} as const;
export type CreateManagerPlatformGcp = ClosedEnum<
  typeof CreateManagerPlatformGcp
>;

/**
 * GCP management configuration extracted from stack settings
 */
export type ManagementConfigGcp = {
  /**
   * Service account email for management roles
   */
  serviceAccountEmail: string;
  platform: CreateManagerPlatformGcp;
};

export const CreateManagerPlatformAws = {
  Aws: "aws",
} as const;
export type CreateManagerPlatformAws = ClosedEnum<
  typeof CreateManagerPlatformAws
>;

/**
 * AWS management configuration extracted from stack settings
 */
export type ManagementConfigAws = {
  /**
   * The managing AWS IAM role ARN that can assume cross-account roles
   */
  managingRoleArn: string;
  platform: CreateManagerPlatformAws;
};

/**
 * Management configuration for cross-account access (self-reported via heartbeat)
 */
export type ManagementConfig =
  | ManagementConfigAzure
  | ManagementConfigAws
  | ManagementConfigGcp
  | ManagementConfigKubernetes
  | any;

/**
 * Runtime metrics (self-reported via heartbeat)
 */
export type CreateManagerMetrics = {
  /**
   * Number of active deployments
   */
  activeDeployments?: number | undefined;
  /**
   * Number of pending deployments
   */
  pendingDeployments?: number | undefined;
  /**
   * Memory usage in megabytes
   */
  memoryUsageMb?: number | undefined;
  /**
   * CPU usage percentage
   */
  cpuUsagePercent?: number | undefined;
};

/**
 * Manager schema
 */
export type CreateManagerResponse = {
  id: string;
  /**
   * Display name of the manager
   */
  name: string;
  /**
   * Platforms this manager can handle
   */
  targets: Array<Target>;
  /**
   * Manager URL (self-reported via heartbeat). DeepStore endpoints are exposed through this URL (e.g., {url}/v1/logs)
   */
  url?: string | null | undefined;
  /**
   * Management configuration for cross-account access (self-reported via heartbeat)
   */
  managementConfig?:
    | ManagementConfigAzure
    | ManagementConfigAws
    | ManagementConfigGcp
    | ManagementConfigKubernetes
    | any
    | null
    | undefined;
  /**
   * Whether this is a system manager (Alien-hosted)
   */
  isSystem: boolean;
  /**
   * The workspace ID (for system managers, this is ALIEN_WORKSPACE_ID)
   */
  workspaceId: string;
  /**
   * Current health status
   */
  status: models.ManagerStatus;
  /**
   * Manager version (self-reported via heartbeat)
   */
  version?: string | null | undefined;
  /**
   * Runtime metrics (self-reported via heartbeat)
   */
  metrics?: CreateManagerMetrics | null | undefined;
  /**
   * Timestamp of the last received heartbeat from the manager
   */
  lastHeartbeatAt?: Date | null | undefined;
  /**
   * ID of the logs database associated with this manager
   */
  logsDatabaseId?: string | null | undefined;
  /**
   * Number of deployments currently being managed by this manager
   */
  managedDeploymentCount: number;
  /**
   * Timestamp when the manager was created
   */
  createdAt: Date;
  /**
   * Deployment link for the web deployment page
   */
  deploymentLink: string;
  /**
   * Deployment token for CLI deployment (use with `alien deploy --token=...`)
   */
  token: string;
};

/** @internal */
export type CreateManagerRequest$Outbound = {
  workspace?: string | undefined;
  NewManagerRequest?: models.NewManagerRequest$Outbound | undefined;
};

/** @internal */
export const CreateManagerRequest$outboundSchema: z.ZodType<
  CreateManagerRequest$Outbound,
  CreateManagerRequest
> = z.object({
  workspace: z.string().optional(),
  newManagerRequest: models.NewManagerRequest$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    newManagerRequest: "NewManagerRequest",
  });
});

export function createManagerRequestToJSON(
  createManagerRequest: CreateManagerRequest,
): string {
  return JSON.stringify(
    CreateManagerRequest$outboundSchema.parse(createManagerRequest),
  );
}

/** @internal */
export const Target$inboundSchema: z.ZodEnum<typeof Target> = z.enum(Target);

/** @internal */
export const CreateManagerPlatformKubernetes$inboundSchema: z.ZodEnum<
  typeof CreateManagerPlatformKubernetes
> = z.enum(CreateManagerPlatformKubernetes);

/** @internal */
export const ManagementConfigKubernetes$inboundSchema: z.ZodType<
  ManagementConfigKubernetes,
  unknown
> = z.object({
  platform: CreateManagerPlatformKubernetes$inboundSchema,
});

export function managementConfigKubernetesFromJSON(
  jsonString: string,
): SafeParseResult<ManagementConfigKubernetes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ManagementConfigKubernetes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ManagementConfigKubernetes' from JSON`,
  );
}

/** @internal */
export const CreateManagerPlatformAzure$inboundSchema: z.ZodEnum<
  typeof CreateManagerPlatformAzure
> = z.enum(CreateManagerPlatformAzure);

/** @internal */
export const ManagementConfigAzure$inboundSchema: z.ZodType<
  ManagementConfigAzure,
  unknown
> = z.object({
  managementPrincipalId: z.string(),
  managingTenantId: z.string(),
  platform: CreateManagerPlatformAzure$inboundSchema,
});

export function managementConfigAzureFromJSON(
  jsonString: string,
): SafeParseResult<ManagementConfigAzure, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ManagementConfigAzure$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ManagementConfigAzure' from JSON`,
  );
}

/** @internal */
export const CreateManagerPlatformGcp$inboundSchema: z.ZodEnum<
  typeof CreateManagerPlatformGcp
> = z.enum(CreateManagerPlatformGcp);

/** @internal */
export const ManagementConfigGcp$inboundSchema: z.ZodType<
  ManagementConfigGcp,
  unknown
> = z.object({
  serviceAccountEmail: z.string(),
  platform: CreateManagerPlatformGcp$inboundSchema,
});

export function managementConfigGcpFromJSON(
  jsonString: string,
): SafeParseResult<ManagementConfigGcp, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ManagementConfigGcp$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ManagementConfigGcp' from JSON`,
  );
}

/** @internal */
export const CreateManagerPlatformAws$inboundSchema: z.ZodEnum<
  typeof CreateManagerPlatformAws
> = z.enum(CreateManagerPlatformAws);

/** @internal */
export const ManagementConfigAws$inboundSchema: z.ZodType<
  ManagementConfigAws,
  unknown
> = z.object({
  managingRoleArn: z.string(),
  platform: CreateManagerPlatformAws$inboundSchema,
});

export function managementConfigAwsFromJSON(
  jsonString: string,
): SafeParseResult<ManagementConfigAws, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ManagementConfigAws$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ManagementConfigAws' from JSON`,
  );
}

/** @internal */
export const ManagementConfig$inboundSchema: z.ZodType<
  ManagementConfig,
  unknown
> = z.union([
  z.lazy(() => ManagementConfigAzure$inboundSchema),
  z.lazy(() => ManagementConfigAws$inboundSchema),
  z.lazy(() => ManagementConfigGcp$inboundSchema),
  z.lazy(() => ManagementConfigKubernetes$inboundSchema),
  z.any(),
]);

export function managementConfigFromJSON(
  jsonString: string,
): SafeParseResult<ManagementConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ManagementConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ManagementConfig' from JSON`,
  );
}

/** @internal */
export const CreateManagerMetrics$inboundSchema: z.ZodType<
  CreateManagerMetrics,
  unknown
> = z.object({
  activeDeployments: z.number().optional(),
  pendingDeployments: z.number().optional(),
  memoryUsageMb: z.number().optional(),
  cpuUsagePercent: z.number().optional(),
});

export function createManagerMetricsFromJSON(
  jsonString: string,
): SafeParseResult<CreateManagerMetrics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateManagerMetrics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateManagerMetrics' from JSON`,
  );
}

/** @internal */
export const CreateManagerResponse$inboundSchema: z.ZodType<
  CreateManagerResponse,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  targets: z.array(Target$inboundSchema),
  url: z.nullable(z.string()).optional(),
  managementConfig: z.nullable(
    z.union([
      z.lazy(() => ManagementConfigAzure$inboundSchema),
      z.lazy(() => ManagementConfigAws$inboundSchema),
      z.lazy(() => ManagementConfigGcp$inboundSchema),
      z.lazy(() => ManagementConfigKubernetes$inboundSchema),
      z.any(),
    ]),
  ).optional(),
  isSystem: z.boolean(),
  workspaceId: z.string(),
  status: models.ManagerStatus$inboundSchema,
  version: z.nullable(z.string()).optional(),
  metrics: z.nullable(z.lazy(() => CreateManagerMetrics$inboundSchema))
    .optional(),
  lastHeartbeatAt: z.nullable(
    z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  logsDatabaseId: z.nullable(z.string()).optional(),
  managedDeploymentCount: z.int(),
  createdAt: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  deploymentLink: z.string(),
  token: z.string(),
});

export function createManagerResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateManagerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateManagerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateManagerResponse' from JSON`,
  );
}
