/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateOperationsBundleUploadUrlRequest = {
  /**
   * Workspace name. Required for user/session/OAuth requests. Optional for API keys because API keys are workspace-scoped; if provided with an API key, it must match the key's workspace.
   */
  workspace?: string | undefined;
  /**
   * Filter by project ID or name.
   */
  project: string;
  operationsBundleUploadUrlRequest?:
    | models.OperationsBundleUploadUrlRequest
    | undefined;
};

/** @internal */
export type CreateOperationsBundleUploadUrlRequest$Outbound = {
  workspace?: string | undefined;
  project: string;
  OperationsBundleUploadUrlRequest?:
    | models.OperationsBundleUploadUrlRequest$Outbound
    | undefined;
};

/** @internal */
export const CreateOperationsBundleUploadUrlRequest$outboundSchema: z.ZodType<
  CreateOperationsBundleUploadUrlRequest$Outbound,
  CreateOperationsBundleUploadUrlRequest
> = z.object({
  workspace: z.string().optional(),
  project: z.string(),
  operationsBundleUploadUrlRequest: models
    .OperationsBundleUploadUrlRequest$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    operationsBundleUploadUrlRequest: "OperationsBundleUploadUrlRequest",
  });
});

export function createOperationsBundleUploadUrlRequestToJSON(
  createOperationsBundleUploadUrlRequest:
    CreateOperationsBundleUploadUrlRequest,
): string {
  return JSON.stringify(
    CreateOperationsBundleUploadUrlRequest$outboundSchema.parse(
      createOperationsBundleUploadUrlRequest,
    ),
  );
}
