/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateManagerRequest = {
  /**
   * Workspace name. Required for user/session/OAuth requests. Optional for API keys because API keys are workspace-scoped; if provided with an API key, it must match the key's workspace.
   */
  workspace?: string | undefined;
  newManagerRequest?: models.NewManagerRequest | undefined;
};

/** @internal */
export type CreateManagerRequest$Outbound = {
  workspace?: string | undefined;
  NewManagerRequest?: models.NewManagerRequest$Outbound | undefined;
};

/** @internal */
export const CreateManagerRequest$outboundSchema: z.ZodType<
  CreateManagerRequest$Outbound,
  CreateManagerRequest
> = z.object({
  workspace: z.string().optional(),
  newManagerRequest: models.NewManagerRequest$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    newManagerRequest: "NewManagerRequest",
  });
});

export function createManagerRequestToJSON(
  createManagerRequest: CreateManagerRequest,
): string {
  return JSON.stringify(
    CreateManagerRequest$outboundSchema.parse(createManagerRequest),
  );
}
