/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type Setup = {
  deploymentPortal?: boolean | undefined;
  packages?: boolean | undefined;
  /**
   * Unique identifier for the project.
   */
  deploymentUrlProjectId?: string | null | undefined;
  managerIds?: Array<string> | undefined;
};

export type CreateDomainRequestBody = {
  domain: string;
  setup?: Setup | undefined;
};

export type CreateDomainRequest = {
  /**
   * Workspace name. Defaults to your last workspace (user auth) or your API key's workspace (token auth). When using an API key, if provided, must match the key's workspace.
   */
  workspace?: string | undefined;
  requestBody?: CreateDomainRequestBody | undefined;
};

/** @internal */
export type Setup$Outbound = {
  deploymentPortal?: boolean | undefined;
  packages?: boolean | undefined;
  deploymentUrlProjectId?: string | null | undefined;
  managerIds?: Array<string> | undefined;
};

/** @internal */
export const Setup$outboundSchema: z.ZodType<Setup$Outbound, Setup> = z.object({
  deploymentPortal: z.boolean().optional(),
  packages: z.boolean().optional(),
  deploymentUrlProjectId: z.nullable(z.string()).optional(),
  managerIds: z.array(z.string()).optional(),
});

export function setupToJSON(setup: Setup): string {
  return JSON.stringify(Setup$outboundSchema.parse(setup));
}

/** @internal */
export type CreateDomainRequestBody$Outbound = {
  domain: string;
  setup?: Setup$Outbound | undefined;
};

/** @internal */
export const CreateDomainRequestBody$outboundSchema: z.ZodType<
  CreateDomainRequestBody$Outbound,
  CreateDomainRequestBody
> = z.object({
  domain: z.string(),
  setup: z.lazy(() => Setup$outboundSchema).optional(),
});

export function createDomainRequestBodyToJSON(
  createDomainRequestBody: CreateDomainRequestBody,
): string {
  return JSON.stringify(
    CreateDomainRequestBody$outboundSchema.parse(createDomainRequestBody),
  );
}

/** @internal */
export type CreateDomainRequest$Outbound = {
  workspace?: string | undefined;
  RequestBody?: CreateDomainRequestBody$Outbound | undefined;
};

/** @internal */
export const CreateDomainRequest$outboundSchema: z.ZodType<
  CreateDomainRequest$Outbound,
  CreateDomainRequest
> = z.object({
  workspace: z.string().optional(),
  requestBody: z.lazy(() => CreateDomainRequestBody$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function createDomainRequestToJSON(
  createDomainRequest: CreateDomainRequest,
): string {
  return JSON.stringify(
    CreateDomainRequest$outboundSchema.parse(createDomainRequest),
  );
}
