/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CreateDeploymentRequest = {
  /**
   * Workspace name. Required for user/session/OAuth requests. Optional for API keys because API keys are workspace-scoped; if provided with an API key, it must match the key's workspace.
   */
  workspace?: string | undefined;
  newDeploymentRequest?: models.NewDeploymentRequest | undefined;
};

/**
 * Existing deployment returned for idempotent deployment-group registration.
 */
export type CreateDeploymentResponseBody = {
  deployment: models.Deployment;
  /**
   * Deployment token (only returned when using deployment group token)
   */
  token?: string | undefined;
};

export type CreateDeploymentResponse =
  | CreateDeploymentResponseBody
  | models.CreateDeploymentResponse;

/** @internal */
export type CreateDeploymentRequest$Outbound = {
  workspace?: string | undefined;
  NewDeploymentRequest?: models.NewDeploymentRequest$Outbound | undefined;
};

/** @internal */
export const CreateDeploymentRequest$outboundSchema: z.ZodType<
  CreateDeploymentRequest$Outbound,
  CreateDeploymentRequest
> = z.object({
  workspace: z.string().optional(),
  newDeploymentRequest: models.NewDeploymentRequest$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    newDeploymentRequest: "NewDeploymentRequest",
  });
});

export function createDeploymentRequestToJSON(
  createDeploymentRequest: CreateDeploymentRequest,
): string {
  return JSON.stringify(
    CreateDeploymentRequest$outboundSchema.parse(createDeploymentRequest),
  );
}

/** @internal */
export const CreateDeploymentResponseBody$inboundSchema: z.ZodType<
  CreateDeploymentResponseBody,
  unknown
> = z.object({
  deployment: models.Deployment$inboundSchema,
  token: z.string().optional(),
});

export function createDeploymentResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateDeploymentResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateDeploymentResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateDeploymentResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateDeploymentResponse$inboundSchema: z.ZodType<
  CreateDeploymentResponse,
  unknown
> = z.union([
  z.lazy(() => CreateDeploymentResponseBody$inboundSchema),
  models.CreateDeploymentResponse$inboundSchema,
]);

export function createDeploymentResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateDeploymentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateDeploymentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateDeploymentResponse' from JSON`,
  );
}
