/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Delete scope: full or liveOnly
 */
export const DeleteScope = {
  Full: "full",
  LiveOnly: "liveOnly",
} as const;
/**
 * Delete scope: full or liveOnly
 */
export type DeleteScope = ClosedEnum<typeof DeleteScope>;

export type DeleteDeploymentRequest = {
  /**
   * Unique identifier for the deployment.
   */
  id: string;
  /**
   * Workspace name. Defaults to your last workspace (user auth) or your API key's workspace (token auth). When using an API key, if provided, must match the key's workspace.
   */
  workspace?: string | undefined;
  force?: boolean | null | undefined;
  /**
   * Delete scope: full or liveOnly
   */
  deleteScope?: DeleteScope | undefined;
};

/**
 * Deployment deletion enqueued successfully.
 */
export type DeleteDeploymentResponse = {
  message: string;
};

/** @internal */
export const DeleteScope$outboundSchema: z.ZodEnum<typeof DeleteScope> = z.enum(
  DeleteScope,
);

/** @internal */
export type DeleteDeploymentRequest$Outbound = {
  id: string;
  workspace?: string | undefined;
  force: boolean | null;
  deleteScope?: string | undefined;
};

/** @internal */
export const DeleteDeploymentRequest$outboundSchema: z.ZodType<
  DeleteDeploymentRequest$Outbound,
  DeleteDeploymentRequest
> = z.object({
  id: z.string(),
  workspace: z.string().optional(),
  force: z.nullable(z.boolean().default(false)),
  deleteScope: DeleteScope$outboundSchema.optional(),
});

export function deleteDeploymentRequestToJSON(
  deleteDeploymentRequest: DeleteDeploymentRequest,
): string {
  return JSON.stringify(
    DeleteDeploymentRequest$outboundSchema.parse(deleteDeploymentRequest),
  );
}

/** @internal */
export const DeleteDeploymentResponse$inboundSchema: z.ZodType<
  DeleteDeploymentResponse,
  unknown
> = z.object({
  message: z.string(),
});

export function deleteDeploymentResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteDeploymentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteDeploymentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteDeploymentResponse' from JSON`,
  );
}
