/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteAPIKeysGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

/**
 * API keys deleted successfully.
 */
export type DeleteAPIKeysResponse = {
  deletedCount: number;
};

/** @internal */
export const DeleteAPIKeysResponse$inboundSchema: z.ZodType<
  DeleteAPIKeysResponse,
  unknown
> = z.object({
  deletedCount: z.number(),
});

export function deleteAPIKeysResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteAPIKeysResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteAPIKeysResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteAPIKeysResponse' from JSON`,
  );
}
