/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type GetAgentSessionRequest = {
  id: string;
  /**
   * Workspace name. Required for user/session/OAuth requests. Optional for API keys because API keys are workspace-scoped; if provided with an API key, it must match the key's workspace.
   */
  workspace?: string | undefined;
};

/** @internal */
export type GetAgentSessionRequest$Outbound = {
  id: string;
  workspace?: string | undefined;
};

/** @internal */
export const GetAgentSessionRequest$outboundSchema: z.ZodType<
  GetAgentSessionRequest$Outbound,
  GetAgentSessionRequest
> = z.object({
  id: z.string(),
  workspace: z.string().optional(),
});

export function getAgentSessionRequestToJSON(
  getAgentSessionRequest: GetAgentSessionRequest,
): string {
  return JSON.stringify(
    GetAgentSessionRequest$outboundSchema.parse(getAgentSessionRequest),
  );
}
