/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type GetAccessRequestActivityGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type GetAccessRequestActivityRequest = {
  id: string;
};

/** @internal */
export type GetAccessRequestActivityRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetAccessRequestActivityRequest$outboundSchema: z.ZodType<
  GetAccessRequestActivityRequest$Outbound,
  GetAccessRequestActivityRequest
> = z.object({
  id: z.string(),
});

export function getAccessRequestActivityRequestToJSON(
  getAccessRequestActivityRequest: GetAccessRequestActivityRequest,
): string {
  return JSON.stringify(
    GetAccessRequestActivityRequest$outboundSchema.parse(
      getAccessRequestActivityRequest,
    ),
  );
}
