/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type GetDeploymentConnectionInfoRequest = {
  /**
   * Unique identifier for the deployment.
   */
  id: string;
  /**
   * Workspace name. Required for user/session/OAuth requests. Optional for API keys because API keys are workspace-scoped; if provided with an API key, it must match the key's workspace.
   */
  workspace?: string | undefined;
};

/** @internal */
export type GetDeploymentConnectionInfoRequest$Outbound = {
  id: string;
  workspace?: string | undefined;
};

/** @internal */
export const GetDeploymentConnectionInfoRequest$outboundSchema: z.ZodType<
  GetDeploymentConnectionInfoRequest$Outbound,
  GetDeploymentConnectionInfoRequest
> = z.object({
  id: z.string(),
  workspace: z.string().optional(),
});

export function getDeploymentConnectionInfoRequestToJSON(
  getDeploymentConnectionInfoRequest: GetDeploymentConnectionInfoRequest,
): string {
  return JSON.stringify(
    GetDeploymentConnectionInfoRequest$outboundSchema.parse(
      getDeploymentConnectionInfoRequest,
    ),
  );
}
