/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type GetDynamicContainerGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type GetDynamicContainerRequest = {
  /**
   * Unique identifier for the deployment.
   */
  id: string;
  name: string;
};

/** @internal */
export type GetDynamicContainerRequest$Outbound = {
  id: string;
  name: string;
};

/** @internal */
export const GetDynamicContainerRequest$outboundSchema: z.ZodType<
  GetDynamicContainerRequest$Outbound,
  GetDynamicContainerRequest
> = z.object({
  id: z.string(),
  name: z.string(),
});

export function getDynamicContainerRequestToJSON(
  getDynamicContainerRequest: GetDynamicContainerRequest,
): string {
  return JSON.stringify(
    GetDynamicContainerRequest$outboundSchema.parse(getDynamicContainerRequest),
  );
}
