/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type GetManagerDomainBindingGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type GetManagerDomainBindingRequest = {
  /**
   * Unique identifier for a manager.
   */
  id: string;
};

/** @internal */
export type GetManagerDomainBindingRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetManagerDomainBindingRequest$outboundSchema: z.ZodType<
  GetManagerDomainBindingRequest$Outbound,
  GetManagerDomainBindingRequest
> = z.object({
  id: z.string(),
});

export function getManagerDomainBindingRequestToJSON(
  getManagerDomainBindingRequest: GetManagerDomainBindingRequest,
): string {
  return JSON.stringify(
    GetManagerDomainBindingRequest$outboundSchema.parse(
      getManagerDomainBindingRequest,
    ),
  );
}
