/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type GetProjectGcpOAuthProviderGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type GetProjectGcpOAuthProviderRequest = {
  /**
   * Project ID or name.
   */
  idOrName: string;
};

/** @internal */
export type GetProjectGcpOAuthProviderRequest$Outbound = {
  idOrName: string;
};

/** @internal */
export const GetProjectGcpOAuthProviderRequest$outboundSchema: z.ZodType<
  GetProjectGcpOAuthProviderRequest$Outbound,
  GetProjectGcpOAuthProviderRequest
> = z.object({
  idOrName: z.string(),
});

export function getProjectGcpOAuthProviderRequestToJSON(
  getProjectGcpOAuthProviderRequest: GetProjectGcpOAuthProviderRequest,
): string {
  return JSON.stringify(
    GetProjectGcpOAuthProviderRequest$outboundSchema.parse(
      getProjectGcpOAuthProviderRequest,
    ),
  );
}
