/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type GetProjectCapabilityOverviewGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type GetProjectCapabilityOverviewRequest = {
  /**
   * Project ID or name.
   */
  idOrName: string;
};

/** @internal */
export type GetProjectCapabilityOverviewRequest$Outbound = {
  idOrName: string;
};

/** @internal */
export const GetProjectCapabilityOverviewRequest$outboundSchema: z.ZodType<
  GetProjectCapabilityOverviewRequest$Outbound,
  GetProjectCapabilityOverviewRequest
> = z.object({
  idOrName: z.string(),
});

export function getProjectCapabilityOverviewRequestToJSON(
  getProjectCapabilityOverviewRequest: GetProjectCapabilityOverviewRequest,
): string {
  return JSON.stringify(
    GetProjectCapabilityOverviewRequest$outboundSchema.parse(
      getProjectCapabilityOverviewRequest,
    ),
  );
}
