/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type GetProjectCapabilityOverviewRequest = {
  /**
   * Project ID or name.
   */
  idOrName: string;
  /**
   * Workspace name. Required for user/session/OAuth requests. Optional for API keys because API keys are workspace-scoped; if provided with an API key, it must match the key's workspace.
   */
  workspace?: string | undefined;
};

/** @internal */
export type GetProjectCapabilityOverviewRequest$Outbound = {
  idOrName: string;
  workspace?: string | undefined;
};

/** @internal */
export const GetProjectCapabilityOverviewRequest$outboundSchema: z.ZodType<
  GetProjectCapabilityOverviewRequest$Outbound,
  GetProjectCapabilityOverviewRequest
> = z.object({
  idOrName: z.string(),
  workspace: z.string().optional(),
});

export function getProjectCapabilityOverviewRequestToJSON(
  getProjectCapabilityOverviewRequest: GetProjectCapabilityOverviewRequest,
): string {
  return JSON.stringify(
    GetProjectCapabilityOverviewRequest$outboundSchema.parse(
      getProjectCapabilityOverviewRequest,
    ),
  );
}
