/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type GetProjectAiProviderHeadersGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type GetProjectAiProviderHeadersRequest = {
  /**
   * Project ID or name.
   */
  idOrName: string;
};

/** @internal */
export type GetProjectAiProviderHeadersRequest$Outbound = {
  idOrName: string;
};

/** @internal */
export const GetProjectAiProviderHeadersRequest$outboundSchema: z.ZodType<
  GetProjectAiProviderHeadersRequest$Outbound,
  GetProjectAiProviderHeadersRequest
> = z.object({
  idOrName: z.string(),
});

export function getProjectAiProviderHeadersRequestToJSON(
  getProjectAiProviderHeadersRequest: GetProjectAiProviderHeadersRequest,
): string {
  return JSON.stringify(
    GetProjectAiProviderHeadersRequest$outboundSchema.parse(
      getProjectAiProviderHeadersRequest,
    ),
  );
}
