/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../../types/enums.js";

export const GetReleaseInclude = {
  Project: "project",
} as const;
export type GetReleaseInclude = ClosedEnum<typeof GetReleaseInclude>;

export type GetReleaseRequest = {
  /**
   * Unique identifier for the release.
   */
  id: string;
  /**
   * Workspace name. Defaults to your last workspace (user auth) or your API key's workspace (token auth). When using an API key, if provided, must match the key's workspace.
   */
  workspace?: string | undefined;
  /**
   * Optional fields to include: project
   */
  include?: Array<GetReleaseInclude> | undefined;
};

/** @internal */
export const GetReleaseInclude$outboundSchema: z.ZodEnum<
  typeof GetReleaseInclude
> = z.enum(GetReleaseInclude);

/** @internal */
export type GetReleaseRequest$Outbound = {
  id: string;
  workspace?: string | undefined;
  include?: Array<string> | undefined;
};

/** @internal */
export const GetReleaseRequest$outboundSchema: z.ZodType<
  GetReleaseRequest$Outbound,
  GetReleaseRequest
> = z.object({
  id: z.string(),
  workspace: z.string().optional(),
  include: z.array(GetReleaseInclude$outboundSchema).optional(),
});

export function getReleaseRequestToJSON(
  getReleaseRequest: GetReleaseRequest,
): string {
  return JSON.stringify(
    GetReleaseRequest$outboundSchema.parse(getReleaseRequest),
  );
}
