/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type GetSetupRegistrationOperationRequest = {
  /**
   * Unique identifier for the setup registration operation.
   */
  id: string;
  /**
   * Workspace name. Required for user/session/OAuth requests. Optional for API keys because API keys are workspace-scoped; if provided with an API key, it must match the key's workspace.
   */
  workspace?: string | undefined;
};

/** @internal */
export type GetSetupRegistrationOperationRequest$Outbound = {
  id: string;
  workspace?: string | undefined;
};

/** @internal */
export const GetSetupRegistrationOperationRequest$outboundSchema: z.ZodType<
  GetSetupRegistrationOperationRequest$Outbound,
  GetSetupRegistrationOperationRequest
> = z.object({
  id: z.string(),
  workspace: z.string().optional(),
});

export function getSetupRegistrationOperationRequestToJSON(
  getSetupRegistrationOperationRequest: GetSetupRegistrationOperationRequest,
): string {
  return JSON.stringify(
    GetSetupRegistrationOperationRequest$outboundSchema.parse(
      getSetupRegistrationOperationRequest,
    ),
  );
}
