/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import * as models from "../index.js";

export type GetWorkspaceGatewayOverviewRequest = {
  gateway: models.GatewayKind;
  /**
   * Workspace name. Required for user/session/OAuth requests. Optional for API keys because API keys are workspace-scoped; if provided with an API key, it must match the key's workspace.
   */
  workspace?: string | undefined;
};

/** @internal */
export type GetWorkspaceGatewayOverviewRequest$Outbound = {
  gateway: string;
  workspace?: string | undefined;
};

/** @internal */
export const GetWorkspaceGatewayOverviewRequest$outboundSchema: z.ZodType<
  GetWorkspaceGatewayOverviewRequest$Outbound,
  GetWorkspaceGatewayOverviewRequest
> = z.object({
  gateway: models.GatewayKind$outboundSchema,
  workspace: z.string().optional(),
});

export function getWorkspaceGatewayOverviewRequestToJSON(
  getWorkspaceGatewayOverviewRequest: GetWorkspaceGatewayOverviewRequest,
): string {
  return JSON.stringify(
    GetWorkspaceGatewayOverviewRequest$outboundSchema.parse(
      getWorkspaceGatewayOverviewRequest,
    ),
  );
}
