/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type GetWorkspaceBillingEntitlementsGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type GetWorkspaceBillingEntitlementsRequest = {};

/** @internal */
export type GetWorkspaceBillingEntitlementsRequest$Outbound = {};

/** @internal */
export const GetWorkspaceBillingEntitlementsRequest$outboundSchema: z.ZodType<
  GetWorkspaceBillingEntitlementsRequest$Outbound,
  GetWorkspaceBillingEntitlementsRequest
> = z.object({});

export function getWorkspaceBillingEntitlementsRequestToJSON(
  getWorkspaceBillingEntitlementsRequest:
    GetWorkspaceBillingEntitlementsRequest,
): string {
  return JSON.stringify(
    GetWorkspaceBillingEntitlementsRequest$outboundSchema.parse(
      getWorkspaceBillingEntitlementsRequest,
    ),
  );
}
