/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type InvokeOperationRequest = {
  /**
   * Workspace name. Required for user/session/OAuth requests. Optional for API keys because API keys are workspace-scoped; if provided with an API key, it must match the key's workspace.
   */
  workspace?: string | undefined;
  /**
   * Filter by project ID or name.
   */
  project: string;
  invokeOperationRequest?: models.InvokeOperationRequest | undefined;
};

/** @internal */
export type InvokeOperationRequest$Outbound = {
  workspace?: string | undefined;
  project: string;
  InvokeOperationRequest?: models.InvokeOperationRequest$Outbound | undefined;
};

/** @internal */
export const InvokeOperationRequest$outboundSchema: z.ZodType<
  InvokeOperationRequest$Outbound,
  InvokeOperationRequest
> = z.object({
  workspace: z.string().optional(),
  project: z.string(),
  invokeOperationRequest: models.InvokeOperationRequest$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    invokeOperationRequest: "InvokeOperationRequest",
  });
});

export function invokeOperationRequestToJSON(
  invokeOperationRequest: InvokeOperationRequest,
): string {
  return JSON.stringify(
    InvokeOperationRequest$outboundSchema.parse(invokeOperationRequest),
  );
}
