/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * List of user's workspaces.
 */
export type ListMembershipsResponse = {
  items: Array<models.Membership>;
};

/** @internal */
export const ListMembershipsResponse$inboundSchema: z.ZodType<
  ListMembershipsResponse,
  unknown
> = z.object({
  items: z.array(models.Membership$inboundSchema),
});

export function listMembershipsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMembershipsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMembershipsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMembershipsResponse' from JSON`,
  );
}
