/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type ListAgentSessionsGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type ListAgentSessionsRequest = {
  /**
   * Only sessions bound to this project. Omit to list the whole workspace.
   */
  project?: string | undefined;
};

/** @internal */
export type ListAgentSessionsRequest$Outbound = {
  project?: string | undefined;
};

/** @internal */
export const ListAgentSessionsRequest$outboundSchema: z.ZodType<
  ListAgentSessionsRequest$Outbound,
  ListAgentSessionsRequest
> = z.object({
  project: z.string().optional(),
});

export function listAgentSessionsRequestToJSON(
  listAgentSessionsRequest: ListAgentSessionsRequest,
): string {
  return JSON.stringify(
    ListAgentSessionsRequest$outboundSchema.parse(listAgentSessionsRequest),
  );
}
