/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type ListDeploymentMachinesGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type ListDeploymentMachinesRequest = {
  /**
   * Unique identifier for the deployment.
   */
  id: string;
};

/** @internal */
export type ListDeploymentMachinesRequest$Outbound = {
  id: string;
};

/** @internal */
export const ListDeploymentMachinesRequest$outboundSchema: z.ZodType<
  ListDeploymentMachinesRequest$Outbound,
  ListDeploymentMachinesRequest
> = z.object({
  id: z.string(),
});

export function listDeploymentMachinesRequestToJSON(
  listDeploymentMachinesRequest: ListDeploymentMachinesRequest,
): string {
  return JSON.stringify(
    ListDeploymentMachinesRequest$outboundSchema.parse(
      listDeploymentMachinesRequest,
    ),
  );
}
