/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListDeploymentContainersRequest = {
  /**
   * Unique identifier for the deployment.
   */
  id: string;
  /**
   * Workspace name. Defaults to your last workspace (user auth) or your API key's workspace (token auth). When using an API key, if provided, must match the key's workspace.
   */
  workspace?: string | undefined;
};

export const ListDeploymentContainersStatus = {
  Pending: "pending",
  Running: "running",
  Stopped: "stopped",
  Failing: "failing",
} as const;
export type ListDeploymentContainersStatus = ClosedEnum<
  typeof ListDeploymentContainersStatus
>;

export type Container = {
  name: string;
  image: string;
  status: ListDeploymentContainersStatus;
  currentReplicas: number;
};

/**
 * List of containers.
 */
export type ListDeploymentContainersResponse = {
  containers: Array<Container>;
};

/** @internal */
export type ListDeploymentContainersRequest$Outbound = {
  id: string;
  workspace?: string | undefined;
};

/** @internal */
export const ListDeploymentContainersRequest$outboundSchema: z.ZodType<
  ListDeploymentContainersRequest$Outbound,
  ListDeploymentContainersRequest
> = z.object({
  id: z.string(),
  workspace: z.string().optional(),
});

export function listDeploymentContainersRequestToJSON(
  listDeploymentContainersRequest: ListDeploymentContainersRequest,
): string {
  return JSON.stringify(
    ListDeploymentContainersRequest$outboundSchema.parse(
      listDeploymentContainersRequest,
    ),
  );
}

/** @internal */
export const ListDeploymentContainersStatus$inboundSchema: z.ZodEnum<
  typeof ListDeploymentContainersStatus
> = z.enum(ListDeploymentContainersStatus);

/** @internal */
export const Container$inboundSchema: z.ZodType<Container, unknown> = z.object({
  name: z.string(),
  image: z.string(),
  status: ListDeploymentContainersStatus$inboundSchema,
  currentReplicas: z.int(),
});

export function containerFromJSON(
  jsonString: string,
): SafeParseResult<Container, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Container$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Container' from JSON`,
  );
}

/** @internal */
export const ListDeploymentContainersResponse$inboundSchema: z.ZodType<
  ListDeploymentContainersResponse,
  unknown
> = z.object({
  containers: z.array(z.lazy(() => Container$inboundSchema)),
});

export function listDeploymentContainersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDeploymentContainersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDeploymentContainersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDeploymentContainersResponse' from JSON`,
  );
}
