/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ReportLogExportDeliveryError = {
  Timeout: "timeout",
  Connection: "connection",
  DestinationRejected: "destination-rejected",
  InvalidDestination: "invalid-destination",
  Overflow: "overflow",
} as const;
export type ReportLogExportDeliveryError = ClosedEnum<
  typeof ReportLogExportDeliveryError
>;

export type ReportLogExportDeliveryRequestBody = {
  revision: string;
  succeeded: boolean;
  error: ReportLogExportDeliveryError | null;
  statusCode?: number | null | undefined;
};

export type ReportLogExportDeliveryRequest = {
  /**
   * Unique identifier for the deployment.
   */
  id: string;
  requestBody?: ReportLogExportDeliveryRequestBody | undefined;
};

/**
 * Delivery status recorded for the current configuration revision.
 */
export type ReportLogExportDeliveryResponse = {
  accepted: boolean;
};

/** @internal */
export const ReportLogExportDeliveryError$outboundSchema: z.ZodEnum<
  typeof ReportLogExportDeliveryError
> = z.enum(ReportLogExportDeliveryError);

/** @internal */
export type ReportLogExportDeliveryRequestBody$Outbound = {
  revision: string;
  succeeded: boolean;
  error: string | null;
  statusCode?: number | null | undefined;
};

/** @internal */
export const ReportLogExportDeliveryRequestBody$outboundSchema: z.ZodType<
  ReportLogExportDeliveryRequestBody$Outbound,
  ReportLogExportDeliveryRequestBody
> = z.object({
  revision: z.string(),
  succeeded: z.boolean(),
  error: z.nullable(ReportLogExportDeliveryError$outboundSchema),
  statusCode: z.nullable(z.int()).optional(),
});

export function reportLogExportDeliveryRequestBodyToJSON(
  reportLogExportDeliveryRequestBody: ReportLogExportDeliveryRequestBody,
): string {
  return JSON.stringify(
    ReportLogExportDeliveryRequestBody$outboundSchema.parse(
      reportLogExportDeliveryRequestBody,
    ),
  );
}

/** @internal */
export type ReportLogExportDeliveryRequest$Outbound = {
  id: string;
  RequestBody?: ReportLogExportDeliveryRequestBody$Outbound | undefined;
};

/** @internal */
export const ReportLogExportDeliveryRequest$outboundSchema: z.ZodType<
  ReportLogExportDeliveryRequest$Outbound,
  ReportLogExportDeliveryRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => ReportLogExportDeliveryRequestBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function reportLogExportDeliveryRequestToJSON(
  reportLogExportDeliveryRequest: ReportLogExportDeliveryRequest,
): string {
  return JSON.stringify(
    ReportLogExportDeliveryRequest$outboundSchema.parse(
      reportLogExportDeliveryRequest,
    ),
  );
}

/** @internal */
export const ReportLogExportDeliveryResponse$inboundSchema: z.ZodType<
  ReportLogExportDeliveryResponse,
  unknown
> = z.object({
  accepted: z.boolean(),
});

export function reportLogExportDeliveryResponseFromJSON(
  jsonString: string,
): SafeParseResult<ReportLogExportDeliveryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReportLogExportDeliveryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReportLogExportDeliveryResponse' from JSON`,
  );
}
