/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ReportManagerHeartbeatGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type ReportManagerHeartbeatRequest = {
  /**
   * Unique identifier for a manager.
   */
  id: string;
  managerHeartbeatRequest?: models.ManagerHeartbeatRequest | undefined;
};

/** @internal */
export type ReportManagerHeartbeatRequest$Outbound = {
  id: string;
  ManagerHeartbeatRequest?: models.ManagerHeartbeatRequest$Outbound | undefined;
};

/** @internal */
export const ReportManagerHeartbeatRequest$outboundSchema: z.ZodType<
  ReportManagerHeartbeatRequest$Outbound,
  ReportManagerHeartbeatRequest
> = z.object({
  id: z.string(),
  managerHeartbeatRequest: models.ManagerHeartbeatRequest$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    managerHeartbeatRequest: "ManagerHeartbeatRequest",
  });
});

export function reportManagerHeartbeatRequestToJSON(
  reportManagerHeartbeatRequest: ReportManagerHeartbeatRequest,
): string {
  return JSON.stringify(
    ReportManagerHeartbeatRequest$outboundSchema.parse(
      reportManagerHeartbeatRequest,
    ),
  );
}
