/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RestoreAwsVirtualKeyRequestBody = {
  kmsKeyArn: string;
};

export type RestoreAwsVirtualKeyRequest = {
  /**
   * Unique identifier for the aws virtual key.
   */
  id: string;
  requestBody?: RestoreAwsVirtualKeyRequestBody | undefined;
};

export const RestoreAwsVirtualKeyStatus = {
  Provisioning: "provisioning",
  Ready: "ready",
  ActionRequired: "action-required",
  Decommissioning: "decommissioning",
  DeletionPending: "deletion-pending",
  Deleted: "deleted",
  Failed: "failed",
} as const;
export type RestoreAwsVirtualKeyStatus = ClosedEnum<
  typeof RestoreAwsVirtualKeyStatus
>;

/**
 * Virtual Key awaiting a successful AWS XKS canary after restore
 */
export type RestoreAwsVirtualKeyResponse = {
  /**
   * Unique identifier for the aws virtual key.
   */
  id: string;
  projectId: string;
  status: RestoreAwsVirtualKeyStatus;
  externalKeyId: string;
  awsAccountId: string;
  awsRegion: string;
  customKeyStoreId: string | null;
  kmsKeyArn: string | null;
  alias: string | null;
  description: string | null;
  deletionWindowDays: number;
  tags: { [k: string]: string };
  observedAt: Date | null;
  canaryPassedAt: Date | null;
  deletionScheduledAt: Date | null;
  finalDeletionObservedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export type RestoreAwsVirtualKeyRequestBody$Outbound = {
  kmsKeyArn: string;
};

/** @internal */
export const RestoreAwsVirtualKeyRequestBody$outboundSchema: z.ZodType<
  RestoreAwsVirtualKeyRequestBody$Outbound,
  RestoreAwsVirtualKeyRequestBody
> = z.object({
  kmsKeyArn: z.string(),
});

export function restoreAwsVirtualKeyRequestBodyToJSON(
  restoreAwsVirtualKeyRequestBody: RestoreAwsVirtualKeyRequestBody,
): string {
  return JSON.stringify(
    RestoreAwsVirtualKeyRequestBody$outboundSchema.parse(
      restoreAwsVirtualKeyRequestBody,
    ),
  );
}

/** @internal */
export type RestoreAwsVirtualKeyRequest$Outbound = {
  id: string;
  RequestBody?: RestoreAwsVirtualKeyRequestBody$Outbound | undefined;
};

/** @internal */
export const RestoreAwsVirtualKeyRequest$outboundSchema: z.ZodType<
  RestoreAwsVirtualKeyRequest$Outbound,
  RestoreAwsVirtualKeyRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => RestoreAwsVirtualKeyRequestBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function restoreAwsVirtualKeyRequestToJSON(
  restoreAwsVirtualKeyRequest: RestoreAwsVirtualKeyRequest,
): string {
  return JSON.stringify(
    RestoreAwsVirtualKeyRequest$outboundSchema.parse(
      restoreAwsVirtualKeyRequest,
    ),
  );
}

/** @internal */
export const RestoreAwsVirtualKeyStatus$inboundSchema: z.ZodEnum<
  typeof RestoreAwsVirtualKeyStatus
> = z.enum(RestoreAwsVirtualKeyStatus);

/** @internal */
export const RestoreAwsVirtualKeyResponse$inboundSchema: z.ZodType<
  RestoreAwsVirtualKeyResponse,
  unknown
> = z.object({
  id: z.string(),
  projectId: z.string(),
  status: RestoreAwsVirtualKeyStatus$inboundSchema,
  externalKeyId: z.string(),
  awsAccountId: z.string(),
  awsRegion: z.string(),
  customKeyStoreId: z.nullable(z.string()),
  kmsKeyArn: z.nullable(z.string()),
  alias: z.nullable(z.string()),
  description: z.nullable(z.string()),
  deletionWindowDays: z.int(),
  tags: z.record(z.string(), z.string()),
  observedAt: z.nullable(
    z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  ),
  canaryPassedAt: z.nullable(
    z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  ),
  deletionScheduledAt: z.nullable(
    z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  ),
  finalDeletionObservedAt: z.nullable(
    z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  ),
  createdAt: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  updatedAt: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
});

export function restoreAwsVirtualKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<RestoreAwsVirtualKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RestoreAwsVirtualKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RestoreAwsVirtualKeyResponse' from JSON`,
  );
}
