/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type RevokeAccessRequestGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type RevokeAccessRequestRequest = {
  id: string;
  revokeAccessRequest?: models.RevokeAccessRequest | undefined;
};

export const RevokeAccessRequestRequesterKind = {
  User: "user",
  ServiceAccount: "serviceAccount",
} as const;
export type RevokeAccessRequestRequesterKind = ClosedEnum<
  typeof RevokeAccessRequestRequesterKind
>;

export type RevokeAccessRequestDeployment = {
  id: string;
  name: string;
  deploymentGroup?: models.DeploymentGroupInfo | undefined;
};

/**
 * How risky an operation is (declared by the plugin metadata).
 */
export const RevokeAccessRequestTier = {
  ReadOnly: "read-only",
  Mutating: "mutating",
  Destructive: "destructive",
} as const;
/**
 * How risky an operation is (declared by the plugin metadata).
 */
export type RevokeAccessRequestTier = ClosedEnum<
  typeof RevokeAccessRequestTier
>;

export type RevokeAccessRequestCommand = {
  command: string;
  summary: string;
  params?: any | null | undefined;
  /**
   * How risky an operation is (declared by the plugin metadata).
   */
  tier?: RevokeAccessRequestTier | undefined;
  pluginVersion?: string | undefined;
  operationContractHash?: string | undefined;
};

/**
 * How risky an operation is (declared by the plugin metadata).
 */
export const RevokeAccessRequestMaxRisk = {
  ReadOnly: "read-only",
  Mutating: "mutating",
  Destructive: "destructive",
} as const;
/**
 * How risky an operation is (declared by the plugin metadata).
 */
export type RevokeAccessRequestMaxRisk = ClosedEnum<
  typeof RevokeAccessRequestMaxRisk
>;

/**
 * How and when the customer gate was passed. Null until approved.
 */
export type RevokeAccessRequestApprovedBy = {
  /**
   * `kubectl` for the in-cluster path, else the direct caller's method such as `slack`.
   */
  method: string | null;
  /**
   * The approving user. Null for the kubectl path: the approver is only in the customer's cluster audit log.
   */
  actorId: string | null;
  at: string;
};

export type RevokeAccessRequestDeniedBy = {
  actorId: string | null;
  at: string;
};

export const RevokeAccessRequestActorKind = {
  User: "user",
  ServiceAccount: "serviceAccount",
} as const;
export type RevokeAccessRequestActorKind = ClosedEnum<
  typeof RevokeAccessRequestActorKind
>;

export type RevokeAccessRequestRevokedBy = {
  actorKind: RevokeAccessRequestActorKind;
  actorId: string;
  at: string;
  reason: string | null;
};

/**
 * The revoked access request.
 */
export type RevokeAccessRequestResponse = {
  id: string;
  requesterKind: RevokeAccessRequestRequesterKind | null;
  requesterId: string | null;
  requestedExpiresAt: string | null;
  deploymentId: string;
  deployment?: RevokeAccessRequestDeployment | undefined;
  remediationPlanId: string | null;
  /**
   * The investigation whose remediation plan proposed this request, if a plan did.
   */
  agentSessionId: string | null;
  title: string;
  reason: string | null;
  commands: Array<RevokeAccessRequestCommand>;
  operationPattern: string | null;
  /**
   * How risky an operation is (declared by the plugin metadata).
   */
  maxRisk: RevokeAccessRequestMaxRisk | null;
  debugGrant: models.AccessRequestDebugGrant | null;
  status: models.AccessRequestStatus;
  approvedUntil: string | null;
  createdAt: string;
  /**
   * Who passed the engineer gate; the requester for a plan-less request.
   */
  queuedBy: string | null;
  queuedAt: string | null;
  /**
   * How and when the customer gate was passed. Null until approved.
   */
  approvedBy: RevokeAccessRequestApprovedBy | null;
  deniedBy: RevokeAccessRequestDeniedBy | null;
  revokedBy: RevokeAccessRequestRevokedBy | null;
  approvalChannels?: Array<models.AccessRequestApprovalChannel> | undefined;
};

/** @internal */
export type RevokeAccessRequestRequest$Outbound = {
  id: string;
  RevokeAccessRequest?: models.RevokeAccessRequest$Outbound | undefined;
};

/** @internal */
export const RevokeAccessRequestRequest$outboundSchema: z.ZodType<
  RevokeAccessRequestRequest$Outbound,
  RevokeAccessRequestRequest
> = z.object({
  id: z.string(),
  revokeAccessRequest: models.RevokeAccessRequest$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    revokeAccessRequest: "RevokeAccessRequest",
  });
});

export function revokeAccessRequestRequestToJSON(
  revokeAccessRequestRequest: RevokeAccessRequestRequest,
): string {
  return JSON.stringify(
    RevokeAccessRequestRequest$outboundSchema.parse(revokeAccessRequestRequest),
  );
}

/** @internal */
export const RevokeAccessRequestRequesterKind$inboundSchema: z.ZodEnum<
  typeof RevokeAccessRequestRequesterKind
> = z.enum(RevokeAccessRequestRequesterKind);

/** @internal */
export const RevokeAccessRequestDeployment$inboundSchema: z.ZodType<
  RevokeAccessRequestDeployment,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  deploymentGroup: models.DeploymentGroupInfo$inboundSchema.optional(),
});

export function revokeAccessRequestDeploymentFromJSON(
  jsonString: string,
): SafeParseResult<RevokeAccessRequestDeployment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RevokeAccessRequestDeployment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevokeAccessRequestDeployment' from JSON`,
  );
}

/** @internal */
export const RevokeAccessRequestTier$inboundSchema: z.ZodEnum<
  typeof RevokeAccessRequestTier
> = z.enum(RevokeAccessRequestTier);

/** @internal */
export const RevokeAccessRequestCommand$inboundSchema: z.ZodType<
  RevokeAccessRequestCommand,
  unknown
> = z.object({
  command: z.string(),
  summary: z.string(),
  params: z.nullable(z.any()).optional(),
  tier: RevokeAccessRequestTier$inboundSchema.optional(),
  pluginVersion: z.string().optional(),
  operationContractHash: z.string().optional(),
});

export function revokeAccessRequestCommandFromJSON(
  jsonString: string,
): SafeParseResult<RevokeAccessRequestCommand, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RevokeAccessRequestCommand$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevokeAccessRequestCommand' from JSON`,
  );
}

/** @internal */
export const RevokeAccessRequestMaxRisk$inboundSchema: z.ZodEnum<
  typeof RevokeAccessRequestMaxRisk
> = z.enum(RevokeAccessRequestMaxRisk);

/** @internal */
export const RevokeAccessRequestApprovedBy$inboundSchema: z.ZodType<
  RevokeAccessRequestApprovedBy,
  unknown
> = z.object({
  method: z.nullable(z.string()),
  actorId: z.nullable(z.string()),
  at: z.string(),
});

export function revokeAccessRequestApprovedByFromJSON(
  jsonString: string,
): SafeParseResult<RevokeAccessRequestApprovedBy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RevokeAccessRequestApprovedBy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevokeAccessRequestApprovedBy' from JSON`,
  );
}

/** @internal */
export const RevokeAccessRequestDeniedBy$inboundSchema: z.ZodType<
  RevokeAccessRequestDeniedBy,
  unknown
> = z.object({
  actorId: z.nullable(z.string()),
  at: z.string(),
});

export function revokeAccessRequestDeniedByFromJSON(
  jsonString: string,
): SafeParseResult<RevokeAccessRequestDeniedBy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RevokeAccessRequestDeniedBy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevokeAccessRequestDeniedBy' from JSON`,
  );
}

/** @internal */
export const RevokeAccessRequestActorKind$inboundSchema: z.ZodEnum<
  typeof RevokeAccessRequestActorKind
> = z.enum(RevokeAccessRequestActorKind);

/** @internal */
export const RevokeAccessRequestRevokedBy$inboundSchema: z.ZodType<
  RevokeAccessRequestRevokedBy,
  unknown
> = z.object({
  actorKind: RevokeAccessRequestActorKind$inboundSchema,
  actorId: z.string(),
  at: z.string(),
  reason: z.nullable(z.string()),
});

export function revokeAccessRequestRevokedByFromJSON(
  jsonString: string,
): SafeParseResult<RevokeAccessRequestRevokedBy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RevokeAccessRequestRevokedBy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevokeAccessRequestRevokedBy' from JSON`,
  );
}

/** @internal */
export const RevokeAccessRequestResponse$inboundSchema: z.ZodType<
  RevokeAccessRequestResponse,
  unknown
> = z.object({
  id: z.string(),
  requesterKind: z.nullable(RevokeAccessRequestRequesterKind$inboundSchema),
  requesterId: z.nullable(z.string()),
  requestedExpiresAt: z.nullable(z.string()),
  deploymentId: z.string(),
  deployment: z.lazy(() => RevokeAccessRequestDeployment$inboundSchema)
    .optional(),
  remediationPlanId: z.nullable(z.string()),
  agentSessionId: z.nullable(z.string()),
  title: z.string(),
  reason: z.nullable(z.string()),
  commands: z.array(z.lazy(() => RevokeAccessRequestCommand$inboundSchema)),
  operationPattern: z.nullable(z.string()),
  maxRisk: z.nullable(RevokeAccessRequestMaxRisk$inboundSchema),
  debugGrant: z.nullable(models.AccessRequestDebugGrant$inboundSchema),
  status: models.AccessRequestStatus$inboundSchema,
  approvedUntil: z.nullable(z.string()),
  createdAt: z.string(),
  queuedBy: z.nullable(z.string()),
  queuedAt: z.nullable(z.string()),
  approvedBy: z.nullable(
    z.lazy(() => RevokeAccessRequestApprovedBy$inboundSchema),
  ),
  deniedBy: z.nullable(z.lazy(() => RevokeAccessRequestDeniedBy$inboundSchema)),
  revokedBy: z.nullable(
    z.lazy(() => RevokeAccessRequestRevokedBy$inboundSchema),
  ),
  approvalChannels: z.array(models.AccessRequestApprovalChannel$inboundSchema)
    .optional(),
});

export function revokeAccessRequestResponseFromJSON(
  jsonString: string,
): SafeParseResult<RevokeAccessRequestResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RevokeAccessRequestResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevokeAccessRequestResponse' from JSON`,
  );
}
