/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4"

export type RevokeAPIKeyRequest = {
  /**
   * Unique identifier for the api key.
   */
  id: string
  /**
   * Workspace name. Defaults to your last workspace (user auth) or your API key's workspace (token auth). When using an API key, if provided, must match the key's workspace.
   */
  workspace?: string | undefined
}

/** @internal */
export type RevokeAPIKeyRequest$Outbound = {
  id: string
  workspace?: string | undefined
}

/** @internal */
export const RevokeAPIKeyRequest$outboundSchema: z.ZodType<
  RevokeAPIKeyRequest$Outbound,
  RevokeAPIKeyRequest
> = z.object({
  id: z.string(),
  workspace: z.string().optional(),
})

export function revokeAPIKeyRequestToJSON(revokeAPIKeyRequest: RevokeAPIKeyRequest): string {
  return JSON.stringify(RevokeAPIKeyRequest$outboundSchema.parse(revokeAPIKeyRequest))
}
