/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type RotateMachinesJoinTokenGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type RotateMachinesJoinTokenRequest = {
  /**
   * Unique identifier for the deployment.
   */
  id: string;
};

/** @internal */
export type RotateMachinesJoinTokenRequest$Outbound = {
  id: string;
};

/** @internal */
export const RotateMachinesJoinTokenRequest$outboundSchema: z.ZodType<
  RotateMachinesJoinTokenRequest$Outbound,
  RotateMachinesJoinTokenRequest
> = z.object({
  id: z.string(),
});

export function rotateMachinesJoinTokenRequestToJSON(
  rotateMachinesJoinTokenRequest: RotateMachinesJoinTokenRequest,
): string {
  return JSON.stringify(
    RotateMachinesJoinTokenRequest$outboundSchema.parse(
      rotateMachinesJoinTokenRequest,
    ),
  );
}
