/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const Enabled = {
  Deployments: "deployments",
  Models: "models",
  Keys: "keys",
  Buckets: "buckets",
  Registry: "registry",
} as const;
export type Enabled = ClosedEnum<typeof Enabled>;

export type SetProjectCapabilitiesRequestBody = {
  enabled: Array<Enabled>;
};

export type SetProjectCapabilitiesRequest = {
  /**
   * Project ID or name.
   */
  idOrName: string;
  /**
   * Workspace name. Required for user/session/OAuth requests. Optional for API keys because API keys are workspace-scoped; if provided with an API key, it must match the key's workspace.
   */
  workspace?: string | undefined;
  requestBody?: SetProjectCapabilitiesRequestBody | undefined;
};

/** @internal */
export const Enabled$outboundSchema: z.ZodEnum<typeof Enabled> = z.enum(
  Enabled,
);

/** @internal */
export type SetProjectCapabilitiesRequestBody$Outbound = {
  enabled: Array<string>;
};

/** @internal */
export const SetProjectCapabilitiesRequestBody$outboundSchema: z.ZodType<
  SetProjectCapabilitiesRequestBody$Outbound,
  SetProjectCapabilitiesRequestBody
> = z.object({
  enabled: z.array(Enabled$outboundSchema),
});

export function setProjectCapabilitiesRequestBodyToJSON(
  setProjectCapabilitiesRequestBody: SetProjectCapabilitiesRequestBody,
): string {
  return JSON.stringify(
    SetProjectCapabilitiesRequestBody$outboundSchema.parse(
      setProjectCapabilitiesRequestBody,
    ),
  );
}

/** @internal */
export type SetProjectCapabilitiesRequest$Outbound = {
  idOrName: string;
  workspace?: string | undefined;
  RequestBody?: SetProjectCapabilitiesRequestBody$Outbound | undefined;
};

/** @internal */
export const SetProjectCapabilitiesRequest$outboundSchema: z.ZodType<
  SetProjectCapabilitiesRequest$Outbound,
  SetProjectCapabilitiesRequest
> = z.object({
  idOrName: z.string(),
  workspace: z.string().optional(),
  requestBody: z.lazy(() => SetProjectCapabilitiesRequestBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function setProjectCapabilitiesRequestToJSON(
  setProjectCapabilitiesRequest: SetProjectCapabilitiesRequest,
): string {
  return JSON.stringify(
    SetProjectCapabilitiesRequest$outboundSchema.parse(
      setProjectCapabilitiesRequest,
    ),
  );
}
