/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type SlackIntegrationUninstallGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type SlackIntegrationUninstallRequest = {};

/** @internal */
export type SlackIntegrationUninstallRequest$Outbound = {};

/** @internal */
export const SlackIntegrationUninstallRequest$outboundSchema: z.ZodType<
  SlackIntegrationUninstallRequest$Outbound,
  SlackIntegrationUninstallRequest
> = z.object({});

export function slackIntegrationUninstallRequestToJSON(
  slackIntegrationUninstallRequest: SlackIntegrationUninstallRequest,
): string {
  return JSON.stringify(
    SlackIntegrationUninstallRequest$outboundSchema.parse(
      slackIntegrationUninstallRequest,
    ),
  );
}
