/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type SyncReconcileRequest = {
  /**
   * Workspace name. Defaults to your last workspace (user auth) or your API key's workspace (token auth). When using an API key, if provided, must match the key's workspace.
   */
  workspace?: string | undefined;
  syncReconcileRequest?: models.SyncReconcileRequest | undefined;
};

/** @internal */
export type SyncReconcileRequest$Outbound = {
  workspace?: string | undefined;
  SyncReconcileRequest?: models.SyncReconcileRequest$Outbound | undefined;
};

/** @internal */
export const SyncReconcileRequest$outboundSchema: z.ZodType<
  SyncReconcileRequest$Outbound,
  SyncReconcileRequest
> = z.object({
  workspace: z.string().optional(),
  syncReconcileRequest: models.SyncReconcileRequest$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    syncReconcileRequest: "SyncReconcileRequest",
  });
});

export function syncReconcileRequestToJSON(
  syncReconcileRequest: SyncReconcileRequest,
): string {
  return JSON.stringify(
    SyncReconcileRequest$outboundSchema.parse(syncReconcileRequest),
  );
}
