/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type SyncListRequest = {
  /**
   * Workspace name. Required for user/session/OAuth requests. Optional for API keys because API keys are workspace-scoped; if provided with an API key, it must match the key's workspace.
   */
  workspace?: string | undefined;
  syncListRequest?: models.SyncListRequest | undefined;
};

/** @internal */
export type SyncListRequest$Outbound = {
  workspace?: string | undefined;
  SyncListRequest?: models.SyncListRequest$Outbound | undefined;
};

/** @internal */
export const SyncListRequest$outboundSchema: z.ZodType<
  SyncListRequest$Outbound,
  SyncListRequest
> = z.object({
  workspace: z.string().optional(),
  syncListRequest: models.SyncListRequest$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    syncListRequest: "SyncListRequest",
  });
});

export function syncListRequestToJSON(
  syncListRequest: SyncListRequest,
): string {
  return JSON.stringify(SyncListRequest$outboundSchema.parse(syncListRequest));
}
