/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type UpdateWorkspaceGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type UpdateWorkspaceRequestBody = {
  logoUrl?: string | null | undefined;
};

export type UpdateWorkspaceRequest = {
  /**
   * Unique identifier for the workspace.
   */
  id: string;
  requestBody?: UpdateWorkspaceRequestBody | undefined;
};

/** @internal */
export type UpdateWorkspaceRequestBody$Outbound = {
  logoUrl?: string | null | undefined;
};

/** @internal */
export const UpdateWorkspaceRequestBody$outboundSchema: z.ZodType<
  UpdateWorkspaceRequestBody$Outbound,
  UpdateWorkspaceRequestBody
> = z.object({
  logoUrl: z.nullable(z.string()).optional(),
});

export function updateWorkspaceRequestBodyToJSON(
  updateWorkspaceRequestBody: UpdateWorkspaceRequestBody,
): string {
  return JSON.stringify(
    UpdateWorkspaceRequestBody$outboundSchema.parse(updateWorkspaceRequestBody),
  );
}

/** @internal */
export type UpdateWorkspaceRequest$Outbound = {
  id: string;
  RequestBody?: UpdateWorkspaceRequestBody$Outbound | undefined;
};

/** @internal */
export const UpdateWorkspaceRequest$outboundSchema: z.ZodType<
  UpdateWorkspaceRequest$Outbound,
  UpdateWorkspaceRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => UpdateWorkspaceRequestBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function updateWorkspaceRequestToJSON(
  updateWorkspaceRequest: UpdateWorkspaceRequest,
): string {
  return JSON.stringify(
    UpdateWorkspaceRequest$outboundSchema.parse(updateWorkspaceRequest),
  );
}
