/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4"
import { remap as remap$ } from "../../lib/primitives.js"
import * as models from "../index.js"

export type UpdateDeploymentGroupRequest = {
  /**
   * Unique identifier for the deployment group.
   */
  id: string
  /**
   * Workspace name. Defaults to your last workspace (user auth) or your API key's workspace (token auth). When using an API key, if provided, must match the key's workspace.
   */
  workspace?: string | undefined
  updateDeploymentGroupRequest?: models.UpdateDeploymentGroupRequest | undefined
}

/** @internal */
export type UpdateDeploymentGroupRequest$Outbound = {
  id: string
  workspace?: string | undefined
  UpdateDeploymentGroupRequest?: models.UpdateDeploymentGroupRequest$Outbound | undefined
}

/** @internal */
export const UpdateDeploymentGroupRequest$outboundSchema: z.ZodType<
  UpdateDeploymentGroupRequest$Outbound,
  UpdateDeploymentGroupRequest
> = z
  .object({
    id: z.string(),
    workspace: z.string().optional(),
    updateDeploymentGroupRequest: models.UpdateDeploymentGroupRequest$outboundSchema.optional(),
  })
  .transform(v => {
    return remap$(v, {
      updateDeploymentGroupRequest: "UpdateDeploymentGroupRequest",
    })
  })

export function updateDeploymentGroupRequestToJSON(
  updateDeploymentGroupRequest: UpdateDeploymentGroupRequest,
): string {
  return JSON.stringify(
    UpdateDeploymentGroupRequest$outboundSchema.parse(updateDeploymentGroupRequest),
  )
}
