/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateProjectGcpOAuthProviderRequest = {
  /**
   * Project ID or name.
   */
  idOrName: string;
  /**
   * Workspace name. Defaults to your last workspace (user auth) or your API key's workspace (token auth). When using an API key, if provided, must match the key's workspace.
   */
  workspace?: string | undefined;
  updateProjectGcpOAuthProvider?:
    | models.UpdateProjectGcpOAuthProvider
    | undefined;
};

/** @internal */
export type UpdateProjectGcpOAuthProviderRequest$Outbound = {
  idOrName: string;
  workspace?: string | undefined;
  UpdateProjectGcpOAuthProvider?:
    | models.UpdateProjectGcpOAuthProvider$Outbound
    | undefined;
};

/** @internal */
export const UpdateProjectGcpOAuthProviderRequest$outboundSchema: z.ZodType<
  UpdateProjectGcpOAuthProviderRequest$Outbound,
  UpdateProjectGcpOAuthProviderRequest
> = z.object({
  idOrName: z.string(),
  workspace: z.string().optional(),
  updateProjectGcpOAuthProvider: models
    .UpdateProjectGcpOAuthProvider$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    updateProjectGcpOAuthProvider: "UpdateProjectGcpOAuthProvider",
  });
});

export function updateProjectGcpOAuthProviderRequestToJSON(
  updateProjectGcpOAuthProviderRequest: UpdateProjectGcpOAuthProviderRequest,
): string {
  return JSON.stringify(
    UpdateProjectGcpOAuthProviderRequest$outboundSchema.parse(
      updateProjectGcpOAuthProviderRequest,
    ),
  );
}
