apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alien-manager.fullname" . }}
  labels:
    {{- include "alien-manager.labels" . | nindent 4 }}
data:
  alien-manager.toml: |
{{- if .Values.config }}
{{ toToml .Values.config | indent 4 }}
{{- end }}
