/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AcquiredDeploymentResponse,
  AcquiredDeploymentResponse$inboundSchema,
} from "./acquireddeploymentresponse.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AcquireResponse = {
  deployments: Array<AcquiredDeploymentResponse>;
};

/** @internal */
export const AcquireResponse$inboundSchema: z.ZodType<
  AcquireResponse,
  unknown
> = z.object({
  deployments: z.array(AcquiredDeploymentResponse$inboundSchema),
});

export function acquireResponseFromJSON(
  jsonString: string,
): SafeParseResult<AcquireResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AcquireResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AcquireResponse' from JSON`,
  );
}
