/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Azure Managed Identity (Container Apps / App Service)
 *
 * @remarks
 * Uses IDENTITY_ENDPOINT + IDENTITY_HEADER injected by the platform
 */
export type AzureCredentialsManagedIdentity = {
  /**
   * The client ID of the user-assigned managed identity
   */
  clientId: string;
  /**
   * The identity endpoint URL (from IDENTITY_ENDPOINT env var)
   */
  identityEndpoint: string;
  /**
   * The identity header secret (from IDENTITY_HEADER env var)
   */
  identityHeader: string;
  type: "managedIdentity";
};

/**
 * Azure AD Workload Identity (federated identity)
 */
export type AzureCredentialsWorkloadIdentity = {
  /**
   * The authority host URL
   */
  authorityHost: string;
  /**
   * The client ID of the managed identity or application
   */
  clientId: string;
  /**
   * Path to the federated token file
   */
  federatedTokenFile: string;
  /**
   * The tenant ID for authentication
   */
  tenantId: string;
  type: "workloadIdentity";
};

/**
 * Azure VM IMDS managed identity.
 */
export type AzureCredentialsVMManagedIdentity = {
  /**
   * The client ID of the user-assigned managed identity
   */
  clientId: string;
  /**
   * Optional IMDS endpoint override
   */
  identityEndpoint?: string | null | undefined;
  type: "vmManagedIdentity";
};

/**
 * A short-lived Azure Storage shared access signature.
 *
 * @remarks
 *
 * Query parameter values are kept decoded. Azure clients must encode them
 * when attaching them to a request URL.
 */
export type AzureCredentialsSasToken = {
  /**
   * Exact SAS query parameters, including the signature and expiry.
   */
  queryParameters: { [k: string]: string };
  type: "sasToken";
};

/**
 * Short-lived bearer tokens keyed by their exact Azure OAuth scope.
 *
 * @remarks
 *
 * This is the only Azure credential form returned by the credential mint
 * endpoint. It contains no refreshable source credential and must not be
 * used for a scope that is absent from the map.
 */
export type AzureCredentialsScopedAccessTokens = {
  /**
   * Exact scope-to-token map. Minted configs include only the Azure
   *
   * @remarks
   * management, storage, Key Vault, and Service Bus scopes used by
   * Alien bindings.
   */
  tokens: { [k: string]: string };
  type: "scopedAccessTokens";
};

/**
 * Direct access token
 */
export type AzureCredentialsAccessToken = {
  /**
   * The bearer token to use for authentication
   */
  token: string;
  type: "accessToken";
};

/**
 * Service principal with client secret
 */
export type AzureCredentialsServicePrincipal = {
  /**
   * The client ID (application ID)
   */
  clientId: string;
  /**
   * The client secret
   */
  clientSecret: string;
  type: "servicePrincipal";
};

/**
 * Represents Azure authentication credentials
 */
export type AzureCredentials =
  | AzureCredentialsServicePrincipal
  | AzureCredentialsAccessToken
  | AzureCredentialsScopedAccessTokens
  | AzureCredentialsSasToken
  | AzureCredentialsVMManagedIdentity
  | AzureCredentialsWorkloadIdentity
  | AzureCredentialsManagedIdentity;

/** @internal */
export const AzureCredentialsManagedIdentity$inboundSchema: z.ZodType<
  AzureCredentialsManagedIdentity,
  unknown
> = z.object({
  client_id: z.string(),
  identity_endpoint: z.string(),
  identity_header: z.string(),
  type: z.literal("managedIdentity"),
}).transform((v) => {
  return remap$(v, {
    "client_id": "clientId",
    "identity_endpoint": "identityEndpoint",
    "identity_header": "identityHeader",
  });
});

export function azureCredentialsManagedIdentityFromJSON(
  jsonString: string,
): SafeParseResult<AzureCredentialsManagedIdentity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AzureCredentialsManagedIdentity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AzureCredentialsManagedIdentity' from JSON`,
  );
}

/** @internal */
export const AzureCredentialsWorkloadIdentity$inboundSchema: z.ZodType<
  AzureCredentialsWorkloadIdentity,
  unknown
> = z.object({
  authority_host: z.string(),
  client_id: z.string(),
  federated_token_file: z.string(),
  tenant_id: z.string(),
  type: z.literal("workloadIdentity"),
}).transform((v) => {
  return remap$(v, {
    "authority_host": "authorityHost",
    "client_id": "clientId",
    "federated_token_file": "federatedTokenFile",
    "tenant_id": "tenantId",
  });
});

export function azureCredentialsWorkloadIdentityFromJSON(
  jsonString: string,
): SafeParseResult<AzureCredentialsWorkloadIdentity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AzureCredentialsWorkloadIdentity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AzureCredentialsWorkloadIdentity' from JSON`,
  );
}

/** @internal */
export const AzureCredentialsVMManagedIdentity$inboundSchema: z.ZodType<
  AzureCredentialsVMManagedIdentity,
  unknown
> = z.object({
  client_id: z.string(),
  identity_endpoint: z.nullable(z.string()).optional(),
  type: z.literal("vmManagedIdentity"),
}).transform((v) => {
  return remap$(v, {
    "client_id": "clientId",
    "identity_endpoint": "identityEndpoint",
  });
});

export function azureCredentialsVMManagedIdentityFromJSON(
  jsonString: string,
): SafeParseResult<AzureCredentialsVMManagedIdentity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AzureCredentialsVMManagedIdentity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AzureCredentialsVMManagedIdentity' from JSON`,
  );
}

/** @internal */
export const AzureCredentialsSasToken$inboundSchema: z.ZodType<
  AzureCredentialsSasToken,
  unknown
> = z.object({
  query_parameters: z.record(z.string(), z.string()),
  type: z.literal("sasToken"),
}).transform((v) => {
  return remap$(v, {
    "query_parameters": "queryParameters",
  });
});

export function azureCredentialsSasTokenFromJSON(
  jsonString: string,
): SafeParseResult<AzureCredentialsSasToken, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AzureCredentialsSasToken$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AzureCredentialsSasToken' from JSON`,
  );
}

/** @internal */
export const AzureCredentialsScopedAccessTokens$inboundSchema: z.ZodType<
  AzureCredentialsScopedAccessTokens,
  unknown
> = z.object({
  tokens: z.record(z.string(), z.string()),
  type: z.literal("scopedAccessTokens"),
});

export function azureCredentialsScopedAccessTokensFromJSON(
  jsonString: string,
): SafeParseResult<AzureCredentialsScopedAccessTokens, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AzureCredentialsScopedAccessTokens$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AzureCredentialsScopedAccessTokens' from JSON`,
  );
}

/** @internal */
export const AzureCredentialsAccessToken$inboundSchema: z.ZodType<
  AzureCredentialsAccessToken,
  unknown
> = z.object({
  token: z.string(),
  type: z.literal("accessToken"),
});

export function azureCredentialsAccessTokenFromJSON(
  jsonString: string,
): SafeParseResult<AzureCredentialsAccessToken, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AzureCredentialsAccessToken$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AzureCredentialsAccessToken' from JSON`,
  );
}

/** @internal */
export const AzureCredentialsServicePrincipal$inboundSchema: z.ZodType<
  AzureCredentialsServicePrincipal,
  unknown
> = z.object({
  client_id: z.string(),
  client_secret: z.string(),
  type: z.literal("servicePrincipal"),
}).transform((v) => {
  return remap$(v, {
    "client_id": "clientId",
    "client_secret": "clientSecret",
  });
});

export function azureCredentialsServicePrincipalFromJSON(
  jsonString: string,
): SafeParseResult<AzureCredentialsServicePrincipal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AzureCredentialsServicePrincipal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AzureCredentialsServicePrincipal' from JSON`,
  );
}

/** @internal */
export const AzureCredentials$inboundSchema: z.ZodType<
  AzureCredentials,
  unknown
> = z.union([
  z.lazy(() => AzureCredentialsServicePrincipal$inboundSchema),
  z.lazy(() => AzureCredentialsAccessToken$inboundSchema),
  z.lazy(() => AzureCredentialsScopedAccessTokens$inboundSchema),
  z.lazy(() => AzureCredentialsSasToken$inboundSchema),
  z.lazy(() => AzureCredentialsVMManagedIdentity$inboundSchema),
  z.lazy(() => AzureCredentialsWorkloadIdentity$inboundSchema),
  z.lazy(() => AzureCredentialsManagedIdentity$inboundSchema),
]);

export function azureCredentialsFromJSON(
  jsonString: string,
): SafeParseResult<AzureCredentials, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AzureCredentials$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AzureCredentials' from JSON`,
  );
}
