/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Service endpoint overrides for testing Azure services
 */
export type AzureServiceOverrides = {
  /**
   * Override endpoints for specific Azure services
   *
   * @remarks
   * Key is the service name (e.g., "management", "storage", "containerApps"), value is the base URL
   */
  endpoints: { [k: string]: string };
};

/** @internal */
export const AzureServiceOverrides$inboundSchema: z.ZodType<
  AzureServiceOverrides,
  unknown
> = z.object({
  endpoints: z.record(z.string(), z.string()),
});

export function azureServiceOverridesFromJSON(
  jsonString: string,
): SafeParseResult<AzureServiceOverrides, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AzureServiceOverrides$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AzureServiceOverrides' from JSON`,
  );
}
