/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import {
  BuildHeartbeatStatus,
  BuildHeartbeatStatus$Outbound,
  BuildHeartbeatStatus$outboundSchema,
} from "./buildheartbeatstatus.js";
import {
  KubernetesEventSnapshot,
  KubernetesEventSnapshot$Outbound,
  KubernetesEventSnapshot$outboundSchema,
} from "./kuberneteseventsnapshot.js";

export type BuildHeartbeatDataKubernetesJob = {
  active?: number | null | undefined;
  completionTime?: Date | null | undefined;
  conditionCount: number;
  events: Array<KubernetesEventSnapshot>;
  failed?: number | null | undefined;
  imageDigest?: string | null | undefined;
  jobName: string;
  namespace: string;
  startTime?: Date | null | undefined;
  status: BuildHeartbeatStatus;
  succeeded?: number | null | undefined;
  backend: "kubernetesJob";
};

export type BuildHeartbeatDataAzureContainerApps = {
  environmentVariableCount: number;
  managedEnvironmentId: string;
  managedIdentityId?: string | null | undefined;
  resourceGroupName: string;
  resourcePrefix?: string | null | undefined;
  status: BuildHeartbeatStatus;
  backend: "azureContainerApps";
};

export type BuildHeartbeatDataGcpCloudBuild = {
  buildConfigId: string;
  environmentVariableCount: number;
  location: string;
  projectId: string;
  serviceAccount?: string | null | undefined;
  status: BuildHeartbeatStatus;
  backend: "gcpCloudBuild";
};

export type BuildHeartbeatDataAwsCodeBuild = {
  artifactsEncryptionDisabled?: boolean | null | undefined;
  artifactsType?: string | null | undefined;
  cloudWatchLogsStatus?: string | null | undefined;
  computeType?: string | null | undefined;
  created?: number | null | undefined;
  description?: string | null | undefined;
  encryptionKeyPresent: boolean;
  environmentImage?: string | null | undefined;
  environmentType?: string | null | undefined;
  environmentVariableCount: number;
  imagePullCredentialsType?: string | null | undefined;
  lastModified?: number | null | undefined;
  privilegedMode?: boolean | null | undefined;
  projectArn?: string | null | undefined;
  projectName: string;
  queuedTimeoutInMinutes?: number | null | undefined;
  s3LogsStatus?: string | null | undefined;
  serviceRolePresent: boolean;
  sourceType?: string | null | undefined;
  status: BuildHeartbeatStatus;
  timeoutInMinutes?: number | null | undefined;
  backend: "awsCodeBuild";
};

export type BuildHeartbeatData =
  | BuildHeartbeatDataAwsCodeBuild
  | BuildHeartbeatDataGcpCloudBuild
  | BuildHeartbeatDataAzureContainerApps
  | BuildHeartbeatDataKubernetesJob;

/** @internal */
export type BuildHeartbeatDataKubernetesJob$Outbound = {
  active?: number | null | undefined;
  completionTime?: string | null | undefined;
  conditionCount: number;
  events: Array<KubernetesEventSnapshot$Outbound>;
  failed?: number | null | undefined;
  imageDigest?: string | null | undefined;
  jobName: string;
  namespace: string;
  startTime?: string | null | undefined;
  status: BuildHeartbeatStatus$Outbound;
  succeeded?: number | null | undefined;
  backend: "kubernetesJob";
};

/** @internal */
export const BuildHeartbeatDataKubernetesJob$outboundSchema: z.ZodType<
  BuildHeartbeatDataKubernetesJob$Outbound,
  BuildHeartbeatDataKubernetesJob
> = z.object({
  active: z.nullable(z.int()).optional(),
  completionTime: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
  conditionCount: z.int(),
  events: z.array(KubernetesEventSnapshot$outboundSchema),
  failed: z.nullable(z.int()).optional(),
  imageDigest: z.nullable(z.string()).optional(),
  jobName: z.string(),
  namespace: z.string(),
  startTime: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  status: BuildHeartbeatStatus$outboundSchema,
  succeeded: z.nullable(z.int()).optional(),
  backend: z.literal("kubernetesJob"),
});

export function buildHeartbeatDataKubernetesJobToJSON(
  buildHeartbeatDataKubernetesJob: BuildHeartbeatDataKubernetesJob,
): string {
  return JSON.stringify(
    BuildHeartbeatDataKubernetesJob$outboundSchema.parse(
      buildHeartbeatDataKubernetesJob,
    ),
  );
}

/** @internal */
export type BuildHeartbeatDataAzureContainerApps$Outbound = {
  environmentVariableCount: number;
  managedEnvironmentId: string;
  managedIdentityId?: string | null | undefined;
  resourceGroupName: string;
  resourcePrefix?: string | null | undefined;
  status: BuildHeartbeatStatus$Outbound;
  backend: "azureContainerApps";
};

/** @internal */
export const BuildHeartbeatDataAzureContainerApps$outboundSchema: z.ZodType<
  BuildHeartbeatDataAzureContainerApps$Outbound,
  BuildHeartbeatDataAzureContainerApps
> = z.object({
  environmentVariableCount: z.int(),
  managedEnvironmentId: z.string(),
  managedIdentityId: z.nullable(z.string()).optional(),
  resourceGroupName: z.string(),
  resourcePrefix: z.nullable(z.string()).optional(),
  status: BuildHeartbeatStatus$outboundSchema,
  backend: z.literal("azureContainerApps"),
});

export function buildHeartbeatDataAzureContainerAppsToJSON(
  buildHeartbeatDataAzureContainerApps: BuildHeartbeatDataAzureContainerApps,
): string {
  return JSON.stringify(
    BuildHeartbeatDataAzureContainerApps$outboundSchema.parse(
      buildHeartbeatDataAzureContainerApps,
    ),
  );
}

/** @internal */
export type BuildHeartbeatDataGcpCloudBuild$Outbound = {
  buildConfigId: string;
  environmentVariableCount: number;
  location: string;
  projectId: string;
  serviceAccount?: string | null | undefined;
  status: BuildHeartbeatStatus$Outbound;
  backend: "gcpCloudBuild";
};

/** @internal */
export const BuildHeartbeatDataGcpCloudBuild$outboundSchema: z.ZodType<
  BuildHeartbeatDataGcpCloudBuild$Outbound,
  BuildHeartbeatDataGcpCloudBuild
> = z.object({
  buildConfigId: z.string(),
  environmentVariableCount: z.int(),
  location: z.string(),
  projectId: z.string(),
  serviceAccount: z.nullable(z.string()).optional(),
  status: BuildHeartbeatStatus$outboundSchema,
  backend: z.literal("gcpCloudBuild"),
});

export function buildHeartbeatDataGcpCloudBuildToJSON(
  buildHeartbeatDataGcpCloudBuild: BuildHeartbeatDataGcpCloudBuild,
): string {
  return JSON.stringify(
    BuildHeartbeatDataGcpCloudBuild$outboundSchema.parse(
      buildHeartbeatDataGcpCloudBuild,
    ),
  );
}

/** @internal */
export type BuildHeartbeatDataAwsCodeBuild$Outbound = {
  artifactsEncryptionDisabled?: boolean | null | undefined;
  artifactsType?: string | null | undefined;
  cloudWatchLogsStatus?: string | null | undefined;
  computeType?: string | null | undefined;
  created?: number | null | undefined;
  description?: string | null | undefined;
  encryptionKeyPresent: boolean;
  environmentImage?: string | null | undefined;
  environmentType?: string | null | undefined;
  environmentVariableCount: number;
  imagePullCredentialsType?: string | null | undefined;
  lastModified?: number | null | undefined;
  privilegedMode?: boolean | null | undefined;
  projectArn?: string | null | undefined;
  projectName: string;
  queuedTimeoutInMinutes?: number | null | undefined;
  s3LogsStatus?: string | null | undefined;
  serviceRolePresent: boolean;
  sourceType?: string | null | undefined;
  status: BuildHeartbeatStatus$Outbound;
  timeoutInMinutes?: number | null | undefined;
  backend: "awsCodeBuild";
};

/** @internal */
export const BuildHeartbeatDataAwsCodeBuild$outboundSchema: z.ZodType<
  BuildHeartbeatDataAwsCodeBuild$Outbound,
  BuildHeartbeatDataAwsCodeBuild
> = z.object({
  artifactsEncryptionDisabled: z.nullable(z.boolean()).optional(),
  artifactsType: z.nullable(z.string()).optional(),
  cloudWatchLogsStatus: z.nullable(z.string()).optional(),
  computeType: z.nullable(z.string()).optional(),
  created: z.nullable(z.number()).optional(),
  description: z.nullable(z.string()).optional(),
  encryptionKeyPresent: z.boolean(),
  environmentImage: z.nullable(z.string()).optional(),
  environmentType: z.nullable(z.string()).optional(),
  environmentVariableCount: z.int(),
  imagePullCredentialsType: z.nullable(z.string()).optional(),
  lastModified: z.nullable(z.number()).optional(),
  privilegedMode: z.nullable(z.boolean()).optional(),
  projectArn: z.nullable(z.string()).optional(),
  projectName: z.string(),
  queuedTimeoutInMinutes: z.nullable(z.int()).optional(),
  s3LogsStatus: z.nullable(z.string()).optional(),
  serviceRolePresent: z.boolean(),
  sourceType: z.nullable(z.string()).optional(),
  status: BuildHeartbeatStatus$outboundSchema,
  timeoutInMinutes: z.nullable(z.int()).optional(),
  backend: z.literal("awsCodeBuild"),
});

export function buildHeartbeatDataAwsCodeBuildToJSON(
  buildHeartbeatDataAwsCodeBuild: BuildHeartbeatDataAwsCodeBuild,
): string {
  return JSON.stringify(
    BuildHeartbeatDataAwsCodeBuild$outboundSchema.parse(
      buildHeartbeatDataAwsCodeBuild,
    ),
  );
}

/** @internal */
export type BuildHeartbeatData$Outbound =
  | BuildHeartbeatDataAwsCodeBuild$Outbound
  | BuildHeartbeatDataGcpCloudBuild$Outbound
  | BuildHeartbeatDataAzureContainerApps$Outbound
  | BuildHeartbeatDataKubernetesJob$Outbound;

/** @internal */
export const BuildHeartbeatData$outboundSchema: z.ZodType<
  BuildHeartbeatData$Outbound,
  BuildHeartbeatData
> = z.union([
  z.lazy(() => BuildHeartbeatDataAwsCodeBuild$outboundSchema),
  z.lazy(() => BuildHeartbeatDataGcpCloudBuild$outboundSchema),
  z.lazy(() => BuildHeartbeatDataAzureContainerApps$outboundSchema),
  z.lazy(() => BuildHeartbeatDataKubernetesJob$outboundSchema),
]);

export function buildHeartbeatDataToJSON(
  buildHeartbeatData: BuildHeartbeatData,
): string {
  return JSON.stringify(
    BuildHeartbeatData$outboundSchema.parse(buildHeartbeatData),
  );
}
