/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import {
  ComputeCapacityBlocker,
  ComputeCapacityBlocker$Outbound,
  ComputeCapacityBlocker$outboundSchema,
} from "./computecapacityblocker.js";
import {
  ComputeCapacityRecommendation,
  ComputeCapacityRecommendation$Outbound,
  ComputeCapacityRecommendation$outboundSchema,
} from "./computecapacityrecommendation.js";
import {
  ComputeDrainProgress,
  ComputeDrainProgress$Outbound,
  ComputeDrainProgress$outboundSchema,
} from "./computedrainprogress.js";

export type ComputeCapacityGroupStatus = {
  capacityBlocker?: ComputeCapacityBlocker | null | undefined;
  currentMachines: number;
  desiredMachines: number;
  drainProgress?: ComputeDrainProgress | null | undefined;
  groupId: string;
  instanceType?: string | null | undefined;
  maxMachines?: number | null | undefined;
  minMachines?: number | null | undefined;
  recommendation?: ComputeCapacityRecommendation | null | undefined;
};

/** @internal */
export type ComputeCapacityGroupStatus$Outbound = {
  capacityBlocker?: ComputeCapacityBlocker$Outbound | null | undefined;
  currentMachines: number;
  desiredMachines: number;
  drainProgress?: ComputeDrainProgress$Outbound | null | undefined;
  groupId: string;
  instanceType?: string | null | undefined;
  maxMachines?: number | null | undefined;
  minMachines?: number | null | undefined;
  recommendation?: ComputeCapacityRecommendation$Outbound | null | undefined;
};

/** @internal */
export const ComputeCapacityGroupStatus$outboundSchema: z.ZodType<
  ComputeCapacityGroupStatus$Outbound,
  ComputeCapacityGroupStatus
> = z.object({
  capacityBlocker: z.nullable(ComputeCapacityBlocker$outboundSchema).optional(),
  currentMachines: z.int(),
  desiredMachines: z.int(),
  drainProgress: z.nullable(ComputeDrainProgress$outboundSchema).optional(),
  groupId: z.string(),
  instanceType: z.nullable(z.string()).optional(),
  maxMachines: z.nullable(z.int()).optional(),
  minMachines: z.nullable(z.int()).optional(),
  recommendation: z.nullable(ComputeCapacityRecommendation$outboundSchema)
    .optional(),
});

export function computeCapacityGroupStatusToJSON(
  computeCapacityGroupStatus: ComputeCapacityGroupStatus,
): string {
  return JSON.stringify(
    ComputeCapacityGroupStatus$outboundSchema.parse(computeCapacityGroupStatus),
  );
}
