/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../types/enums.js";

/**
 * Token kinds an admin can create through the API.
 */
export const CreatableTokenType = {
  Tunnel: "tunnel",
} as const;
/**
 * Token kinds an admin can create through the API.
 */
export type CreatableTokenType = ClosedEnum<typeof CreatableTokenType>;

/** @internal */
export const CreatableTokenType$outboundSchema: z.ZodEnum<
  typeof CreatableTokenType
> = z.enum(CreatableTokenType);
