/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import {
  OperationApprovalUnion,
  OperationApprovalUnion$Outbound,
  OperationApprovalUnion$outboundSchema,
} from "./operationapprovalunion.js";
import {
  OperationSettingValueUnion,
  OperationSettingValueUnion$Outbound,
  OperationSettingValueUnion$outboundSchema,
} from "./operationsettingvalueunion.js";

/**
 * A published custom plugin at an exact version.
 */
export type CustomPluginOperationsConfig = {
  /**
   * Approval rule per operation: an operation name, or `*` for all of them.
   *
   * @remarks
   * Operations no rule matches need approval.
   */
  approval?: { [k: string]: OperationApprovalUnion } | undefined;
  /**
   * Values for the settings the plugin's manifest declares.
   */
  settings?: { [k: string]: OperationSettingValueUnion } | undefined;
  /**
   * Plugin name as published.
   */
  name: string;
  /**
   * Exact published version.
   */
  version: string;
};

/** @internal */
export type CustomPluginOperationsConfig$Outbound = {
  approval?: { [k: string]: OperationApprovalUnion$Outbound } | undefined;
  settings?: { [k: string]: OperationSettingValueUnion$Outbound } | undefined;
  name: string;
  version: string;
};

/** @internal */
export const CustomPluginOperationsConfig$outboundSchema: z.ZodType<
  CustomPluginOperationsConfig$Outbound,
  CustomPluginOperationsConfig
> = z.object({
  approval: z.record(z.string(), OperationApprovalUnion$outboundSchema)
    .optional(),
  settings: z.record(z.string(), OperationSettingValueUnion$outboundSchema)
    .optional(),
  name: z.string(),
  version: z.string(),
});

export function customPluginOperationsConfigToJSON(
  customPluginOperationsConfig: CustomPluginOperationsConfig,
): string {
  return JSON.stringify(
    CustomPluginOperationsConfig$outboundSchema.parse(
      customPluginOperationsConfig,
    ),
  );
}
