/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../types/enums.js";

/**
 * Deployment status in the deployment lifecycle
 */
export const DeploymentStatus = {
  Pending: "pending",
  InitialSetup: "initial-setup",
  InitialSetupFailed: "initial-setup-failed",
  Provisioning: "provisioning",
  ProvisioningFailed: "provisioning-failed",
  Running: "running",
  RefreshFailed: "refresh-failed",
  UpdatePending: "update-pending",
  Updating: "updating",
  UpdateFailed: "update-failed",
  DeletePending: "delete-pending",
  Deleting: "deleting",
  DeleteFailed: "delete-failed",
  Deleted: "deleted",
} as const;
/**
 * Deployment status in the deployment lifecycle
 */
export type DeploymentStatus = ClosedEnum<typeof DeploymentStatus>;

/** @internal */
export const DeploymentStatus$inboundSchema: z.ZodEnum<
  typeof DeploymentStatus
> = z.enum(DeploymentStatus);
/** @internal */
export const DeploymentStatus$outboundSchema: z.ZodEnum<
  typeof DeploymentStatus
> = DeploymentStatus$inboundSchema;
