/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { CommandsInfo, CommandsInfo$inboundSchema } from "./commandsinfo.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { PlatformEnum, PlatformEnum$inboundSchema } from "./platformenum.js";
import { ResourceEntry, ResourceEntry$inboundSchema } from "./resourceentry.js";

export type DeploymentInfoResponse = {
  commands: CommandsInfo;
  /**
   * Represents the target cloud platform.
   */
  platform: PlatformEnum;
  resources: { [k: string]: ResourceEntry };
  status: string;
};

/** @internal */
export const DeploymentInfoResponse$inboundSchema: z.ZodType<
  DeploymentInfoResponse,
  unknown
> = z.object({
  commands: CommandsInfo$inboundSchema,
  platform: PlatformEnum$inboundSchema,
  resources: z.record(z.string(), ResourceEntry$inboundSchema),
  status: z.string(),
});

export function deploymentInfoResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentInfoResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentInfoResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentInfoResponse' from JSON`,
  );
}
