/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Failure-domain policy selected for a compute pool.
 */
export type FailureDomainSelection = {
  /**
   * Concrete provider domains selected during setup.
   *
   * @remarks
   * Empty delegates deterministic selection to the provider setup implementation.
   */
  selectedFailureDomains?: Array<string> | undefined;
  /**
   * Number of distinct failure domains across which new stateful replicas may be spread.
   */
  spread: number;
};

/** @internal */
export const FailureDomainSelection$inboundSchema: z.ZodType<
  FailureDomainSelection,
  unknown
> = z.object({
  selectedFailureDomains: z.array(z.string()).optional(),
  spread: z.int(),
});
/** @internal */
export type FailureDomainSelection$Outbound = {
  selectedFailureDomains?: Array<string> | undefined;
  spread: number;
};

/** @internal */
export const FailureDomainSelection$outboundSchema: z.ZodType<
  FailureDomainSelection$Outbound,
  FailureDomainSelection
> = z.object({
  selectedFailureDomains: z.array(z.string()).optional(),
  spread: z.int(),
});

export function failureDomainSelectionToJSON(
  failureDomainSelection: FailureDomainSelection,
): string {
  return JSON.stringify(
    FailureDomainSelection$outboundSchema.parse(failureDomainSelection),
  );
}
export function failureDomainSelectionFromJSON(
  jsonString: string,
): SafeParseResult<FailureDomainSelection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FailureDomainSelection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FailureDomainSelection' from JSON`,
  );
}
