/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * GCP IAM condition
 */
export type GcpCondition = {
  expression: string;
  title: string;
};

/** @internal */
export const GcpCondition$inboundSchema: z.ZodType<GcpCondition, unknown> = z
  .object({
    expression: z.string(),
    title: z.string(),
  });
/** @internal */
export type GcpCondition$Outbound = {
  expression: string;
  title: string;
};

/** @internal */
export const GcpCondition$outboundSchema: z.ZodType<
  GcpCondition$Outbound,
  GcpCondition
> = z.object({
  expression: z.string(),
  title: z.string(),
});

export function gcpConditionToJSON(gcpCondition: GcpCondition): string {
  return JSON.stringify(GcpCondition$outboundSchema.parse(gcpCondition));
}
export function gcpConditionFromJSON(
  jsonString: string,
): SafeParseResult<GcpCondition, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GcpCondition$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GcpCondition' from JSON`,
  );
}
