/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Configuration for GCP service account impersonation
 */
export type GcpImpersonationConfig = {
  /**
   * Optional sequence of service accounts in a delegation chain
   */
  delegates?: Array<string> | null | undefined;
  /**
   * Optional desired lifetime duration of the access token (max 3600s)
   */
  lifetime?: string | null | undefined;
  /**
   * The OAuth 2.0 scopes that define the access token's permissions
   */
  scopes: Array<string>;
  /**
   * The email of the service account to impersonate
   */
  serviceAccountEmail: string;
  /**
   * Optional target project ID override. When provided, the impersonated config
   *
   * @remarks
   * uses this project ID instead of inheriting the caller's project.
   */
  targetProjectId?: string | null | undefined;
  /**
   * Optional target region override. When provided, the impersonated config
   *
   * @remarks
   * uses this region instead of inheriting the caller's region.
   */
  targetRegion?: string | null | undefined;
};

/** @internal */
export const GcpImpersonationConfig$inboundSchema: z.ZodType<
  GcpImpersonationConfig,
  unknown
> = z.object({
  delegates: z.nullable(z.array(z.string())).optional(),
  lifetime: z.nullable(z.string()).optional(),
  scopes: z.array(z.string()),
  serviceAccountEmail: z.string(),
  targetProjectId: z.nullable(z.string()).optional(),
  targetRegion: z.nullable(z.string()).optional(),
});

export function gcpImpersonationConfigFromJSON(
  jsonString: string,
): SafeParseResult<GcpImpersonationConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GcpImpersonationConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GcpImpersonationConfig' from JSON`,
  );
}
