/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type GitMetadata = {
  commitMessage?: string | null | undefined;
  commitRef?: string | null | undefined;
  commitSha?: string | null | undefined;
};

/** @internal */
export type GitMetadata$Outbound = {
  commitMessage?: string | null | undefined;
  commitRef?: string | null | undefined;
  commitSha?: string | null | undefined;
};

/** @internal */
export const GitMetadata$outboundSchema: z.ZodType<
  GitMetadata$Outbound,
  GitMetadata
> = z.object({
  commitMessage: z.nullable(z.string()).optional(),
  commitRef: z.nullable(z.string()).optional(),
  commitSha: z.nullable(z.string()).optional(),
});

export function gitMetadataToJSON(gitMetadata: GitMetadata): string {
  return JSON.stringify(GitMetadata$outboundSchema.parse(gitMetadata));
}
