/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import {
  HeartbeatIssueSeverity,
  HeartbeatIssueSeverity$outboundSchema,
} from "./heartbeatissueseverity.js";

export type HeartbeatEvent = {
  kind: string;
  message: string;
  observedAt: Date;
  severity: HeartbeatIssueSeverity;
  source?: string | null | undefined;
};

/** @internal */
export type HeartbeatEvent$Outbound = {
  kind: string;
  message: string;
  observedAt: string;
  severity: string;
  source?: string | null | undefined;
};

/** @internal */
export const HeartbeatEvent$outboundSchema: z.ZodType<
  HeartbeatEvent$Outbound,
  HeartbeatEvent
> = z.object({
  kind: z.string(),
  message: z.string(),
  observedAt: z.date().transform(v => v.toISOString()),
  severity: HeartbeatIssueSeverity$outboundSchema,
  source: z.nullable(z.string()).optional(),
});

export function heartbeatEventToJSON(heartbeatEvent: HeartbeatEvent): string {
  return JSON.stringify(HeartbeatEvent$outboundSchema.parse(heartbeatEvent));
}
