/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../types/enums.js";

/**
 * Package source that produced an import request. Observability label
 *
 * @remarks
 * only — the manager does not branch on this value, and any new deployment
 * pathway can omit it without affecting import behavior.
 */
export const ImportSourceKind = {
  Cloudformation: "cloudformation",
  Terraform: "terraform",
  Helm: "helm",
} as const;
/**
 * Package source that produced an import request. Observability label
 *
 * @remarks
 * only — the manager does not branch on this value, and any new deployment
 * pathway can omit it without affecting import behavior.
 */
export type ImportSourceKind = ClosedEnum<typeof ImportSourceKind>;

/** @internal */
export const ImportSourceKind$inboundSchema: z.ZodEnum<
  typeof ImportSourceKind
> = z.enum(ImportSourceKind);
/** @internal */
export const ImportSourceKind$outboundSchema: z.ZodEnum<
  typeof ImportSourceKind
> = ImportSourceKind$inboundSchema;
