/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { PlatformEnum, PlatformEnum$outboundSchema } from "./platformenum.js";

export type InitializeRequest = {
  name?: string | null | undefined;
  platform?: PlatformEnum | null | undefined;
};

/** @internal */
export type InitializeRequest$Outbound = {
  name?: string | null | undefined;
  platform?: string | null | undefined;
};

/** @internal */
export const InitializeRequest$outboundSchema: z.ZodType<
  InitializeRequest$Outbound,
  InitializeRequest
> = z.object({
  name: z.nullable(z.string()).optional(),
  platform: z.nullable(PlatformEnum$outboundSchema).optional(),
});

export function initializeRequestToJSON(
  initializeRequest: InitializeRequest,
): string {
  return JSON.stringify(
    InitializeRequest$outboundSchema.parse(initializeRequest),
  );
}
