/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import {
  KubernetesEventInvolvedObject,
  KubernetesEventInvolvedObject$Outbound,
  KubernetesEventInvolvedObject$outboundSchema,
} from "./kuberneteseventinvolvedobject.js";
import {
  KubernetesEventSource,
  KubernetesEventSource$Outbound,
  KubernetesEventSource$outboundSchema,
} from "./kuberneteseventsource.js";

export type KubernetesEventSnapshot = {
  count?: number | null | undefined;
  eventTime?: Date | null | undefined;
  firstTimestamp?: Date | null | undefined;
  involvedObject?: KubernetesEventInvolvedObject | null | undefined;
  lastTimestamp?: Date | null | undefined;
  message: string;
  raw?: any | null | undefined;
  reason: string;
  source?: KubernetesEventSource | null | undefined;
  type?: string | null | undefined;
};

/** @internal */
export type KubernetesEventSnapshot$Outbound = {
  count?: number | null | undefined;
  eventTime?: string | null | undefined;
  firstTimestamp?: string | null | undefined;
  involvedObject?: KubernetesEventInvolvedObject$Outbound | null | undefined;
  lastTimestamp?: string | null | undefined;
  message: string;
  raw?: any | null | undefined;
  reason: string;
  source?: KubernetesEventSource$Outbound | null | undefined;
  type?: string | null | undefined;
};

/** @internal */
export const KubernetesEventSnapshot$outboundSchema: z.ZodType<
  KubernetesEventSnapshot$Outbound,
  KubernetesEventSnapshot
> = z.object({
  count: z.nullable(z.int()).optional(),
  eventTime: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  firstTimestamp: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
  involvedObject: z.nullable(KubernetesEventInvolvedObject$outboundSchema)
    .optional(),
  lastTimestamp: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
  message: z.string(),
  raw: z.nullable(z.any()).optional(),
  reason: z.string(),
  source: z.nullable(KubernetesEventSource$outboundSchema).optional(),
  type: z.nullable(z.string()).optional(),
});

export function kubernetesEventSnapshotToJSON(
  kubernetesEventSnapshot: KubernetesEventSnapshot,
): string {
  return JSON.stringify(
    KubernetesEventSnapshot$outboundSchema.parse(kubernetesEventSnapshot),
  );
}
