/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  KubernetesClusterSettings,
  KubernetesClusterSettings$inboundSchema,
  KubernetesClusterSettings$Outbound,
  KubernetesClusterSettings$outboundSchema,
} from "./kubernetesclustersettings.js";
import {
  KubernetesExposureSettings,
  KubernetesExposureSettings$inboundSchema,
  KubernetesExposureSettings$Outbound,
  KubernetesExposureSettings$outboundSchema,
} from "./kubernetesexposuresettings.js";

/**
 * Kubernetes runtime substrate configuration.
 *
 * @remarks
 *
 * This controls how setup chooses the cluster backing `Platform::Kubernetes`
 * deployments. When omitted, cloud-backed Kubernetes deployments default to a
 * managed cluster and generic/on-prem Kubernetes defaults to an external
 * cluster.
 */
export type KubernetesSettings = {
  cluster?: KubernetesClusterSettings | null | undefined;
  exposure?: KubernetesExposureSettings | null | undefined;
};

/** @internal */
export const KubernetesSettings$inboundSchema: z.ZodType<
  KubernetesSettings,
  unknown
> = z.object({
  cluster: z.nullable(KubernetesClusterSettings$inboundSchema).optional(),
  exposure: z.nullable(KubernetesExposureSettings$inboundSchema).optional(),
});
/** @internal */
export type KubernetesSettings$Outbound = {
  cluster?: KubernetesClusterSettings$Outbound | null | undefined;
  exposure?: KubernetesExposureSettings$Outbound | null | undefined;
};

/** @internal */
export const KubernetesSettings$outboundSchema: z.ZodType<
  KubernetesSettings$Outbound,
  KubernetesSettings
> = z.object({
  cluster: z.nullable(KubernetesClusterSettings$outboundSchema).optional(),
  exposure: z.nullable(KubernetesExposureSettings$outboundSchema).optional(),
});

export function kubernetesSettingsToJSON(
  kubernetesSettings: KubernetesSettings,
): string {
  return JSON.stringify(
    KubernetesSettings$outboundSchema.parse(kubernetesSettings),
  );
}
export function kubernetesSettingsFromJSON(
  jsonString: string,
): SafeParseResult<KubernetesSettings, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KubernetesSettings$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KubernetesSettings' from JSON`,
  );
}
