/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ReleaseChannelResponse,
  ReleaseChannelResponse$inboundSchema,
} from "./releasechannelresponse.js";

export type ListReleaseChannelsResponse = {
  items: Array<ReleaseChannelResponse>;
};

/** @internal */
export const ListReleaseChannelsResponse$inboundSchema: z.ZodType<
  ListReleaseChannelsResponse,
  unknown
> = z.object({
  items: z.array(ReleaseChannelResponse$inboundSchema),
});

export function listReleaseChannelsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListReleaseChannelsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListReleaseChannelsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListReleaseChannelsResponse' from JSON`,
  );
}
