/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import {
  LocalRuntimeUnitKind,
  LocalRuntimeUnitKind$outboundSchema,
} from "./localruntimeunitkind.js";
import {
  MetricSample,
  MetricSample$Outbound,
  MetricSample$outboundSchema,
} from "./metricsample.js";

export type LocalRuntimeUnitStatus = {
  cpu?: MetricSample | null | undefined;
  kind: LocalRuntimeUnitKind;
  memory?: MetricSample | null | undefined;
  name: string;
  phase?: string | null | undefined;
  pid?: number | null | undefined;
  ready: boolean;
  restartCount?: number | null | undefined;
  unitId: string;
};

/** @internal */
export type LocalRuntimeUnitStatus$Outbound = {
  cpu?: MetricSample$Outbound | null | undefined;
  kind: string;
  memory?: MetricSample$Outbound | null | undefined;
  name: string;
  phase?: string | null | undefined;
  pid?: number | null | undefined;
  ready: boolean;
  restartCount?: number | null | undefined;
  unitId: string;
};

/** @internal */
export const LocalRuntimeUnitStatus$outboundSchema: z.ZodType<
  LocalRuntimeUnitStatus$Outbound,
  LocalRuntimeUnitStatus
> = z.object({
  cpu: z.nullable(MetricSample$outboundSchema).optional(),
  kind: LocalRuntimeUnitKind$outboundSchema,
  memory: z.nullable(MetricSample$outboundSchema).optional(),
  name: z.string(),
  phase: z.nullable(z.string()).optional(),
  pid: z.nullable(z.int()).optional(),
  ready: z.boolean(),
  restartCount: z.nullable(z.int()).optional(),
  unitId: z.string(),
});

export function localRuntimeUnitStatusToJSON(
  localRuntimeUnitStatus: LocalRuntimeUnitStatus,
): string {
  return JSON.stringify(
    LocalRuntimeUnitStatus$outboundSchema.parse(localRuntimeUnitStatus),
  );
}
