/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Use an existing VNet (Azure).
 *
 * @remarks
 *
 * Alien validates the references but creates no networking infrastructure.
 * The customer is responsible for routing and egress (NAT Gateway, proxy, VPN, etc.).
 */
export type NetworkSettingsByoVnetAzure = {
  /**
   * Name of the dedicated classic Application Gateway subnet within the VNet.
   */
  applicationGatewaySubnetName?: string | null | undefined;
  /**
   * Name of the dedicated subnet that hosts Private Endpoints (e.g. for a
   *
   * @remarks
   * Postgres Flexible Server). A Private Endpoint must not share the private
   * subnet, which is already claimed by the Container Apps environment's
   * `infrastructure_subnet_id`. Required only when the stack contains a
   * Postgres resource; otherwise unused.
   */
  privateEndpointSubnetName?: string | null | undefined;
  /**
   * Name of the private subnet within the VNet
   */
  privateSubnetName: string;
  /**
   * Name of the public subnet within the VNet
   */
  publicSubnetName: string;
  type: "byo-vnet-azure";
  /**
   * The full resource ID of the existing VNet
   */
  vnetResourceId: string;
};

/**
 * Use an existing VPC (GCP).
 *
 * @remarks
 *
 * Alien validates the references but creates no networking infrastructure.
 * The customer is responsible for routing and egress (Cloud NAT, proxy, VPN, etc.).
 */
export type NetworkSettingsByoVpcGcp = {
  /**
   * The name of the existing VPC network
   */
  networkName: string;
  /**
   * The region of the subnet
   */
  region: string;
  /**
   * The name of the subnet to use
   */
  subnetName: string;
  type: "byo-vpc-gcp";
};

/**
 * Use an existing VPC (AWS).
 *
 * @remarks
 *
 * Alien validates the references but creates no networking infrastructure.
 * The customer is responsible for routing and egress (NAT, proxy, VPN, etc.).
 */
export type NetworkSettingsByoVpcAws = {
  /**
   * IDs of private subnets
   */
  privateSubnetIds: Array<string>;
  /**
   * IDs of public subnets (required for public ingress)
   */
  publicSubnetIds: Array<string>;
  /**
   * Optional security group IDs to use
   */
  securityGroupIds?: Array<string> | undefined;
  type: "byo-vpc-aws";
  /**
   * The ID of the existing VPC
   */
  vpcId: string;
};

/**
 * Create a new isolated VPC/VNet with a managed NAT gateway.
 *
 * @remarks
 *
 * All networking infrastructure is provisioned by Alien and cleaned up on delete.
 * VMs use private IPs only; all outbound traffic routes through the NAT gateway.
 *
 * Recommended for production deployments.
 */
export type NetworkSettingsCreate = {
  /**
   * Number of availability zones (default: 2).
   */
  availabilityZones?: number | undefined;
  /**
   * VPC/VNet CIDR block. If not specified, auto-generated from stack ID
   *
   * @remarks
   * to reduce conflicts (e.g., "10.{hash}.0.0/16").
   */
  cidr?: string | null | undefined;
  type: "create";
};

/**
 * Use the cloud provider's default VPC/network.
 *
 * @remarks
 *
 * Designed for fast dev/test provisioning. No isolated VPC is created, so there
 * is nothing to wait for or clean up. VMs receive ephemeral public IPs for internet
 * access — no NAT gateway is provisioned.
 *
 * - **AWS**: Discovers the account's default VPC. Subnets are public with auto-assigned IPs.
 * - **GCP**: Discovers the project's `default` network and regional subnet. Instance
 *   templates include an `AccessConfig` to assign an ephemeral external IP.
 * - **Azure**: Azure has no default VNet, so one is created along with a NAT Gateway.
 *   VMs stay private and use NAT for egress.
 *
 * Not recommended for production. Use `Create` instead.
 */
export type NetworkSettingsUseDefault = {
  type: "use-default";
};

/**
 * Network configuration for the stack.
 *
 * @remarks
 *
 * Controls how VPC/VNet networking is provisioned. Users configure this in
 * `StackSettings`; the Network resource itself is auto-generated by preflights.
 *
 * ## Egress policy
 *
 * Container cluster VMs are configured for egress based on the mode:
 *
 * - `UseDefault` → VMs get ephemeral public IPs (no NAT is provisioned)
 * - `Create` → VMs use private IPs; Alien provisions a NAT gateway for outbound access
 * - `ByoVpc*` / `ByoVnet*` → no public IPs assigned; customer manages egress
 *
 * For production workloads, use `Create`. For fast dev/test iteration, `UseDefault` is
 * sufficient. For environments with existing VPCs, use the appropriate `ByoVpc*` variant.
 */
export type NetworkSettings =
  | NetworkSettingsUseDefault
  | NetworkSettingsCreate
  | NetworkSettingsByoVpcAws
  | NetworkSettingsByoVpcGcp
  | NetworkSettingsByoVnetAzure;

/** @internal */
export const NetworkSettingsByoVnetAzure$inboundSchema: z.ZodType<
  NetworkSettingsByoVnetAzure,
  unknown
> = z.object({
  application_gateway_subnet_name: z.nullable(z.string()).optional(),
  private_endpoint_subnet_name: z.nullable(z.string()).optional(),
  private_subnet_name: z.string(),
  public_subnet_name: z.string(),
  type: z.literal("byo-vnet-azure"),
  vnet_resource_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "application_gateway_subnet_name": "applicationGatewaySubnetName",
    "private_endpoint_subnet_name": "privateEndpointSubnetName",
    "private_subnet_name": "privateSubnetName",
    "public_subnet_name": "publicSubnetName",
    "vnet_resource_id": "vnetResourceId",
  });
});
/** @internal */
export type NetworkSettingsByoVnetAzure$Outbound = {
  application_gateway_subnet_name?: string | null | undefined;
  private_endpoint_subnet_name?: string | null | undefined;
  private_subnet_name: string;
  public_subnet_name: string;
  type: "byo-vnet-azure";
  vnet_resource_id: string;
};

/** @internal */
export const NetworkSettingsByoVnetAzure$outboundSchema: z.ZodType<
  NetworkSettingsByoVnetAzure$Outbound,
  NetworkSettingsByoVnetAzure
> = z.object({
  applicationGatewaySubnetName: z.nullable(z.string()).optional(),
  privateEndpointSubnetName: z.nullable(z.string()).optional(),
  privateSubnetName: z.string(),
  publicSubnetName: z.string(),
  type: z.literal("byo-vnet-azure"),
  vnetResourceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    applicationGatewaySubnetName: "application_gateway_subnet_name",
    privateEndpointSubnetName: "private_endpoint_subnet_name",
    privateSubnetName: "private_subnet_name",
    publicSubnetName: "public_subnet_name",
    vnetResourceId: "vnet_resource_id",
  });
});

export function networkSettingsByoVnetAzureToJSON(
  networkSettingsByoVnetAzure: NetworkSettingsByoVnetAzure,
): string {
  return JSON.stringify(
    NetworkSettingsByoVnetAzure$outboundSchema.parse(
      networkSettingsByoVnetAzure,
    ),
  );
}
export function networkSettingsByoVnetAzureFromJSON(
  jsonString: string,
): SafeParseResult<NetworkSettingsByoVnetAzure, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NetworkSettingsByoVnetAzure$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NetworkSettingsByoVnetAzure' from JSON`,
  );
}

/** @internal */
export const NetworkSettingsByoVpcGcp$inboundSchema: z.ZodType<
  NetworkSettingsByoVpcGcp,
  unknown
> = z.object({
  network_name: z.string(),
  region: z.string(),
  subnet_name: z.string(),
  type: z.literal("byo-vpc-gcp"),
}).transform((v) => {
  return remap$(v, {
    "network_name": "networkName",
    "subnet_name": "subnetName",
  });
});
/** @internal */
export type NetworkSettingsByoVpcGcp$Outbound = {
  network_name: string;
  region: string;
  subnet_name: string;
  type: "byo-vpc-gcp";
};

/** @internal */
export const NetworkSettingsByoVpcGcp$outboundSchema: z.ZodType<
  NetworkSettingsByoVpcGcp$Outbound,
  NetworkSettingsByoVpcGcp
> = z.object({
  networkName: z.string(),
  region: z.string(),
  subnetName: z.string(),
  type: z.literal("byo-vpc-gcp"),
}).transform((v) => {
  return remap$(v, {
    networkName: "network_name",
    subnetName: "subnet_name",
  });
});

export function networkSettingsByoVpcGcpToJSON(
  networkSettingsByoVpcGcp: NetworkSettingsByoVpcGcp,
): string {
  return JSON.stringify(
    NetworkSettingsByoVpcGcp$outboundSchema.parse(networkSettingsByoVpcGcp),
  );
}
export function networkSettingsByoVpcGcpFromJSON(
  jsonString: string,
): SafeParseResult<NetworkSettingsByoVpcGcp, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NetworkSettingsByoVpcGcp$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NetworkSettingsByoVpcGcp' from JSON`,
  );
}

/** @internal */
export const NetworkSettingsByoVpcAws$inboundSchema: z.ZodType<
  NetworkSettingsByoVpcAws,
  unknown
> = z.object({
  private_subnet_ids: z.array(z.string()),
  public_subnet_ids: z.array(z.string()),
  security_group_ids: z.array(z.string()).optional(),
  type: z.literal("byo-vpc-aws"),
  vpc_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "private_subnet_ids": "privateSubnetIds",
    "public_subnet_ids": "publicSubnetIds",
    "security_group_ids": "securityGroupIds",
    "vpc_id": "vpcId",
  });
});
/** @internal */
export type NetworkSettingsByoVpcAws$Outbound = {
  private_subnet_ids: Array<string>;
  public_subnet_ids: Array<string>;
  security_group_ids?: Array<string> | undefined;
  type: "byo-vpc-aws";
  vpc_id: string;
};

/** @internal */
export const NetworkSettingsByoVpcAws$outboundSchema: z.ZodType<
  NetworkSettingsByoVpcAws$Outbound,
  NetworkSettingsByoVpcAws
> = z.object({
  privateSubnetIds: z.array(z.string()),
  publicSubnetIds: z.array(z.string()),
  securityGroupIds: z.array(z.string()).optional(),
  type: z.literal("byo-vpc-aws"),
  vpcId: z.string(),
}).transform((v) => {
  return remap$(v, {
    privateSubnetIds: "private_subnet_ids",
    publicSubnetIds: "public_subnet_ids",
    securityGroupIds: "security_group_ids",
    vpcId: "vpc_id",
  });
});

export function networkSettingsByoVpcAwsToJSON(
  networkSettingsByoVpcAws: NetworkSettingsByoVpcAws,
): string {
  return JSON.stringify(
    NetworkSettingsByoVpcAws$outboundSchema.parse(networkSettingsByoVpcAws),
  );
}
export function networkSettingsByoVpcAwsFromJSON(
  jsonString: string,
): SafeParseResult<NetworkSettingsByoVpcAws, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NetworkSettingsByoVpcAws$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NetworkSettingsByoVpcAws' from JSON`,
  );
}

/** @internal */
export const NetworkSettingsCreate$inboundSchema: z.ZodType<
  NetworkSettingsCreate,
  unknown
> = z.object({
  availability_zones: z.int().optional(),
  cidr: z.nullable(z.string()).optional(),
  type: z.literal("create"),
}).transform((v) => {
  return remap$(v, {
    "availability_zones": "availabilityZones",
  });
});
/** @internal */
export type NetworkSettingsCreate$Outbound = {
  availability_zones?: number | undefined;
  cidr?: string | null | undefined;
  type: "create";
};

/** @internal */
export const NetworkSettingsCreate$outboundSchema: z.ZodType<
  NetworkSettingsCreate$Outbound,
  NetworkSettingsCreate
> = z.object({
  availabilityZones: z.int().optional(),
  cidr: z.nullable(z.string()).optional(),
  type: z.literal("create"),
}).transform((v) => {
  return remap$(v, {
    availabilityZones: "availability_zones",
  });
});

export function networkSettingsCreateToJSON(
  networkSettingsCreate: NetworkSettingsCreate,
): string {
  return JSON.stringify(
    NetworkSettingsCreate$outboundSchema.parse(networkSettingsCreate),
  );
}
export function networkSettingsCreateFromJSON(
  jsonString: string,
): SafeParseResult<NetworkSettingsCreate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NetworkSettingsCreate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NetworkSettingsCreate' from JSON`,
  );
}

/** @internal */
export const NetworkSettingsUseDefault$inboundSchema: z.ZodType<
  NetworkSettingsUseDefault,
  unknown
> = z.object({
  type: z.literal("use-default"),
});
/** @internal */
export type NetworkSettingsUseDefault$Outbound = {
  type: "use-default";
};

/** @internal */
export const NetworkSettingsUseDefault$outboundSchema: z.ZodType<
  NetworkSettingsUseDefault$Outbound,
  NetworkSettingsUseDefault
> = z.object({
  type: z.literal("use-default"),
});

export function networkSettingsUseDefaultToJSON(
  networkSettingsUseDefault: NetworkSettingsUseDefault,
): string {
  return JSON.stringify(
    NetworkSettingsUseDefault$outboundSchema.parse(networkSettingsUseDefault),
  );
}
export function networkSettingsUseDefaultFromJSON(
  jsonString: string,
): SafeParseResult<NetworkSettingsUseDefault, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NetworkSettingsUseDefault$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NetworkSettingsUseDefault' from JSON`,
  );
}

/** @internal */
export const NetworkSettings$inboundSchema: z.ZodType<
  NetworkSettings,
  unknown
> = z.union([
  z.lazy(() => NetworkSettingsUseDefault$inboundSchema),
  z.lazy(() => NetworkSettingsCreate$inboundSchema),
  z.lazy(() => NetworkSettingsByoVpcAws$inboundSchema),
  z.lazy(() => NetworkSettingsByoVpcGcp$inboundSchema),
  z.lazy(() => NetworkSettingsByoVnetAzure$inboundSchema),
]);
/** @internal */
export type NetworkSettings$Outbound =
  | NetworkSettingsUseDefault$Outbound
  | NetworkSettingsCreate$Outbound
  | NetworkSettingsByoVpcAws$Outbound
  | NetworkSettingsByoVpcGcp$Outbound
  | NetworkSettingsByoVnetAzure$Outbound;

/** @internal */
export const NetworkSettings$outboundSchema: z.ZodType<
  NetworkSettings$Outbound,
  NetworkSettings
> = z.union([
  z.lazy(() => NetworkSettingsUseDefault$outboundSchema),
  z.lazy(() => NetworkSettingsCreate$outboundSchema),
  z.lazy(() => NetworkSettingsByoVpcAws$outboundSchema),
  z.lazy(() => NetworkSettingsByoVpcGcp$outboundSchema),
  z.lazy(() => NetworkSettingsByoVnetAzure$outboundSchema),
]);

export function networkSettingsToJSON(
  networkSettings: NetworkSettings,
): string {
  return JSON.stringify(NetworkSettings$outboundSchema.parse(networkSettings));
}
export function networkSettingsFromJSON(
  jsonString: string,
): SafeParseResult<NetworkSettings, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NetworkSettings$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NetworkSettings' from JSON`,
  );
}
