/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../types/enums.js";

/**
 * Whether matching operations run without approval.
 */
export const OperationApprovalDecision = {
  Auto: "auto",
  Manual: "manual",
} as const;
/**
 * Whether matching operations run without approval.
 */
export type OperationApprovalDecision = ClosedEnum<
  typeof OperationApprovalDecision
>;

/** @internal */
export const OperationApprovalDecision$outboundSchema: z.ZodEnum<
  typeof OperationApprovalDecision
> = z.enum(OperationApprovalDecision);
