/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import {
  DeploymentState,
  DeploymentState$Outbound,
  DeploymentState$outboundSchema,
} from "./deploymentstate.js";

export type ReconcileRequest = {
  deploymentId: string;
  session: string;
  /**
   * Deployment state
   *
   * @remarks
   *
   * Represents the current state of deployed infrastructure, including release tracking.
   * This is platform-agnostic - no backend IDs or database relationships.
   *
   * The deployment engine manages releases internally: when a deployment succeeds,
   * it promotes `target_release` to `current_release` and clears `target_release`.
   */
  state: DeploymentState;
  updateHeartbeat?: boolean | undefined;
};

/** @internal */
export type ReconcileRequest$Outbound = {
  deploymentId: string;
  session: string;
  state: DeploymentState$Outbound;
  updateHeartbeat?: boolean | undefined;
};

/** @internal */
export const ReconcileRequest$outboundSchema: z.ZodType<
  ReconcileRequest$Outbound,
  ReconcileRequest
> = z.object({
  deploymentId: z.string(),
  session: z.string(),
  state: DeploymentState$outboundSchema,
  updateHeartbeat: z.boolean().optional(),
});

export function reconcileRequestToJSON(
  reconcileRequest: ReconcileRequest,
): string {
  return JSON.stringify(
    ReconcileRequest$outboundSchema.parse(reconcileRequest),
  );
}
