/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  DeploymentState,
  DeploymentState$inboundSchema,
} from "./deploymentstate.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ReconcileResponse = {
  /**
   * Deployment state
   *
   * @remarks
   *
   * Represents the current state of deployed infrastructure, including release tracking.
   * This is platform-agnostic - no backend IDs or database relationships.
   *
   * The deployment engine manages releases internally: when a deployment succeeds,
   * it promotes `target_release` to `current_release` and clears `target_release`.
   */
  current: DeploymentState;
  success: boolean;
};

/** @internal */
export const ReconcileResponse$inboundSchema: z.ZodType<
  ReconcileResponse,
  unknown
> = z.object({
  current: DeploymentState$inboundSchema,
  success: z.boolean(),
});

export function reconcileResponseFromJSON(
  jsonString: string,
): SafeParseResult<ReconcileResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReconcileResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReconcileResponse' from JSON`,
  );
}
