/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import {
  ExecutionClaim,
  ExecutionClaim$Outbound,
  ExecutionClaim$outboundSchema,
} from "./executionclaim.js";

export type ReleaseRequest = {
  deploymentId: string;
  executionClaim?: ExecutionClaim | null | undefined;
  session: string;
};

/** @internal */
export type ReleaseRequest$Outbound = {
  deploymentId: string;
  executionClaim?: ExecutionClaim$Outbound | null | undefined;
  session: string;
};

/** @internal */
export const ReleaseRequest$outboundSchema: z.ZodType<
  ReleaseRequest$Outbound,
  ReleaseRequest
> = z.object({
  deploymentId: z.string(),
  executionClaim: z.nullable(ExecutionClaim$outboundSchema).optional(),
  session: z.string(),
});

export function releaseRequestToJSON(releaseRequest: ReleaseRequest): string {
  return JSON.stringify(ReleaseRequest$outboundSchema.parse(releaseRequest));
}
