/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

export type ReleaseRequest = {
  deploymentId: string;
  session: string;
};

/** @internal */
export type ReleaseRequest$Outbound = {
  deploymentId: string;
  session: string;
};

/** @internal */
export const ReleaseRequest$outboundSchema: z.ZodType<
  ReleaseRequest$Outbound,
  ReleaseRequest
> = z.object({
  deploymentId: z.string(),
  session: z.string(),
});

export function releaseRequestToJSON(releaseRequest: ReleaseRequest): string {
  return JSON.stringify(ReleaseRequest$outboundSchema.parse(releaseRequest));
}
