/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Concrete send-only queue topology returned to remote clients.
 */
export type RemoteServiceBusQueueBinding = {
  namespace: string;
  queueName: string;
};

/** @internal */
export const RemoteServiceBusQueueBinding$inboundSchema: z.ZodType<
  RemoteServiceBusQueueBinding,
  unknown
> = z.object({
  namespace: z.string(),
  queueName: z.string(),
});

export function remoteServiceBusQueueBindingFromJSON(
  jsonString: string,
): SafeParseResult<RemoteServiceBusQueueBinding, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoteServiceBusQueueBinding$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoteServiceBusQueueBinding' from JSON`,
  );
}
