/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type RemoteAzureKeyVaultKeyBinding = {
  keyId: string;
};

/** @internal */
export const RemoteAzureKeyVaultKeyBinding$inboundSchema: z.ZodType<
  RemoteAzureKeyVaultKeyBinding,
  unknown
> = z.object({
  keyId: z.string(),
});

export function remoteAzureKeyVaultKeyBindingFromJSON(
  jsonString: string,
): SafeParseResult<RemoteAzureKeyVaultKeyBinding, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoteAzureKeyVaultKeyBinding$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoteAzureKeyVaultKeyBinding' from JSON`,
  );
}
