/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type RemoteAwsBedrockAiBinding = {
  region: string;
};

/** @internal */
export const RemoteAwsBedrockAiBinding$inboundSchema: z.ZodType<
  RemoteAwsBedrockAiBinding,
  unknown
> = z.object({
  region: z.string(),
});

export function remoteAwsBedrockAiBindingFromJSON(
  jsonString: string,
): SafeParseResult<RemoteAwsBedrockAiBinding, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoteAwsBedrockAiBinding$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoteAwsBedrockAiBinding' from JSON`,
  );
}
