/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type RemoteAwsKmsKeyBinding = {
  keyArn: string;
  region?: string | null | undefined;
};

/** @internal */
export const RemoteAwsKmsKeyBinding$inboundSchema: z.ZodType<
  RemoteAwsKmsKeyBinding,
  unknown
> = z.object({
  keyArn: z.string(),
  region: z.nullable(z.string()).optional(),
});

export function remoteAwsKmsKeyBindingFromJSON(
  jsonString: string,
): SafeParseResult<RemoteAwsKmsKeyBinding, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoteAwsKmsKeyBinding$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoteAwsKmsKeyBinding' from JSON`,
  );
}
