/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Explicit fields of an Azure user-delegation SAS. Keeping the fields typed
 *
 * @remarks
 * lets clients independently validate container scope, permissions, protocol,
 * and expiry before constructing query parameters.
 */
export type RemoteAzureContainerSas = {
  /**
   * Storage account named by the signed canonical resource.
   */
  accountName: string;
  /**
   * Blob container named by the signed canonical resource.
   */
  containerName: string;
  /**
   * SAS validity end (`se`).
   */
  expiresAt: string;
  /**
   * Canonically ordered SAS permissions (`sp`).
   */
  permissions: string;
  /**
   * Required transport protocol (`spr`).
   */
  protocol: string;
  /**
   * Storage authorization version (`sv`).
   */
  serviceVersion: string;
  /**
   * HMAC-SHA256 signature (`sig`).
   */
  signature: string;
  /**
   * Delegation-key validity end (`ske`).
   */
  signedKeyExpiry: string;
  /**
   * Delegation-key service (`sks`).
   */
  signedKeyService: string;
  /**
   * Delegation-key validity start (`skt`).
   */
  signedKeyStart: string;
  /**
   * Delegation-key version (`skv`).
   */
  signedKeyVersion: string;
  /**
   * Object ID that requested the delegation key (`skoid`).
   */
  signedObjectId: string;
  /**
   * Signed resource kind (`sr`).
   */
  signedResource: string;
  /**
   * Tenant ID that issued the delegation key (`sktid`).
   */
  signedTenantId: string;
  /**
   * SAS validity start (`st`).
   */
  startsAt: string;
};

/** @internal */
export const RemoteAzureContainerSas$inboundSchema: z.ZodType<
  RemoteAzureContainerSas,
  unknown
> = z.object({
  accountName: z.string(),
  containerName: z.string(),
  expiresAt: z.string(),
  permissions: z.string(),
  protocol: z.string(),
  serviceVersion: z.string(),
  signature: z.string(),
  signedKeyExpiry: z.string(),
  signedKeyService: z.string(),
  signedKeyStart: z.string(),
  signedKeyVersion: z.string(),
  signedObjectId: z.string(),
  signedResource: z.string(),
  signedTenantId: z.string(),
  startsAt: z.string(),
});

export function remoteAzureContainerSasFromJSON(
  jsonString: string,
): SafeParseResult<RemoteAzureContainerSas, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoteAzureContainerSas$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoteAzureContainerSas' from JSON`,
  );
}
