/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Concrete DynamoDB KV topology returned to remote clients.
 */
export type RemoteDynamodbKvBinding = {
  /**
   * AWS region of the table.
   */
  region: string;
  /**
   * DynamoDB table authorized by the credential lease.
   */
  tableName: string;
};

/** @internal */
export const RemoteDynamodbKvBinding$inboundSchema: z.ZodType<
  RemoteDynamodbKvBinding,
  unknown
> = z.object({
  region: z.string(),
  tableName: z.string(),
});

export function remoteDynamodbKvBindingFromJSON(
  jsonString: string,
): SafeParseResult<RemoteDynamodbKvBinding, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoteDynamodbKvBinding$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoteDynamodbKvBinding' from JSON`,
  );
}
