/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Concrete send-only queue topology returned to remote clients.
 */
export type RemotePubsubQueueBinding = {
  subscription: string;
  topic: string;
};

/** @internal */
export const RemotePubsubQueueBinding$inboundSchema: z.ZodType<
  RemotePubsubQueueBinding,
  unknown
> = z.object({
  subscription: z.string(),
  topic: z.string(),
});

export function remotePubsubQueueBindingFromJSON(
  jsonString: string,
): SafeParseResult<RemotePubsubQueueBinding, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemotePubsubQueueBinding$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemotePubsubQueueBinding' from JSON`,
  );
}
