/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

/**
 * One OTLP batch from the environment.
 */
export type ReportedTelemetry = {
  /**
   * OTLP protobuf, base64.
   */
  data: string;
  /**
   * The site's sequence number for the batch. The manager keeps the
   *
   * @remarks
   * highest one it has passed on and skips any it already has, so a
   * report sent again doesn't duplicate telemetry.
   */
  id?: number | null | undefined;
  /**
   * `logs`, `metrics` or `traces`.
   */
  signal: string;
};

/** @internal */
export type ReportedTelemetry$Outbound = {
  data: string;
  id?: number | null | undefined;
  signal: string;
};

/** @internal */
export const ReportedTelemetry$outboundSchema: z.ZodType<
  ReportedTelemetry$Outbound,
  ReportedTelemetry
> = z.object({
  data: z.string(),
  id: z.nullable(z.int()).optional(),
  signal: z.string(),
});

export function reportedTelemetryToJSON(
  reportedTelemetry: ReportedTelemetry,
): string {
  return JSON.stringify(
    ReportedTelemetry$outboundSchema.parse(reportedTelemetry),
  );
}
