/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";

/**
 * A single operation the Operator currently has loaded. Opaque identifiers
 *
 * @remarks
 * only — no tier, description, or other plugin business logic crosses into
 * this public crate.
 */
export type ReportedOperation = {
  /**
   * Name of the operation within the plugin.
   */
  name: string;
  /**
   * Name of the plugin that owns this operation.
   */
  plugin: string;
  /**
   * Version of the plugin that owns this operation.
   */
  pluginVersion: string;
};

/** @internal */
export type ReportedOperation$Outbound = {
  name: string;
  plugin: string;
  pluginVersion: string;
};

/** @internal */
export const ReportedOperation$outboundSchema: z.ZodType<
  ReportedOperation$Outbound,
  ReportedOperation
> = z.object({
  name: z.string(),
  plugin: z.string(),
  pluginVersion: z.string(),
});

export function reportedOperationToJSON(
  reportedOperation: ReportedOperation,
): string {
  return JSON.stringify(
    ReportedOperation$outboundSchema.parse(reportedOperation),
  );
}
