/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../types/enums.js";

/**
 * Describes the lifecycle of a resource within a stack, determining how it's managed and deployed.
 */
export const ResourceLifecycle = {
  Frozen: "frozen",
  Live: "live",
  LiveOnSetup: "live-on-setup",
} as const;
/**
 * Describes the lifecycle of a resource within a stack, determining how it's managed and deployed.
 */
export type ResourceLifecycle = ClosedEnum<typeof ResourceLifecycle>;

/** @internal */
export const ResourceLifecycle$inboundSchema: z.ZodEnum<
  typeof ResourceLifecycle
> = z.enum(ResourceLifecycle);
/** @internal */
export const ResourceLifecycle$outboundSchema: z.ZodEnum<
  typeof ResourceLifecycle
> = ResourceLifecycle$inboundSchema;
