/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import {
  ResolveBindingKind,
  ResolveBindingKind$outboundSchema,
} from "./resolvebindingkind.js";

/**
 * Request body for `POST /v1/bindings/resolve`.
 */
export type ResolveBindingRequest = {
  /**
   * Deployment containing the remote-enabled resource.
   */
  deploymentId: string;
  kind?: ResolveBindingKind | null | undefined;
  /**
   * Logical remote-enabled resource id in the deployment's stack state.
   */
  resourceId?: string | null | undefined;
};

/** @internal */
export type ResolveBindingRequest$Outbound = {
  deploymentId: string;
  kind?: string | null | undefined;
  resourceId?: string | null | undefined;
};

/** @internal */
export const ResolveBindingRequest$outboundSchema: z.ZodType<
  ResolveBindingRequest$Outbound,
  ResolveBindingRequest
> = z.object({
  deploymentId: z.string(),
  kind: z.nullable(ResolveBindingKind$outboundSchema).optional(),
  resourceId: z.nullable(z.string()).optional(),
});

export function resolveBindingRequestToJSON(
  resolveBindingRequest: ResolveBindingRequest,
): string {
  return JSON.stringify(
    ResolveBindingRequest$outboundSchema.parse(resolveBindingRequest),
  );
}
