/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Reference to a Kubernetes Secret
 */
export type SecretReference = {
  key: string;
  name: string;
};

/** @internal */
export const SecretReference$inboundSchema: z.ZodType<
  SecretReference,
  unknown
> = z.object({
  key: z.string(),
  name: z.string(),
});
/** @internal */
export type SecretReference$Outbound = {
  key: string;
  name: string;
};

/** @internal */
export const SecretReference$outboundSchema: z.ZodType<
  SecretReference$Outbound,
  SecretReference
> = z.object({
  key: z.string(),
  name: z.string(),
});

export function secretReferenceToJSON(
  secretReference: SecretReference,
): string {
  return JSON.stringify(SecretReference$outboundSchema.parse(secretReference));
}
export function secretReferenceFromJSON(
  jsonString: string,
): SafeParseResult<SecretReference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SecretReference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SecretReference' from JSON`,
  );
}
