/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import {
  StorageHeartbeatStatus,
  StorageHeartbeatStatus$Outbound,
  StorageHeartbeatStatus$outboundSchema,
} from "./storageheartbeatstatus.js";

export type StorageHeartbeatDataLocal = {
  isDirectory?: boolean | null | undefined;
  modifiedAt?: Date | null | undefined;
  path: string;
  pathExists: boolean;
  readonly?: boolean | null | undefined;
  status: StorageHeartbeatStatus;
  backend: "local";
};

export type StorageHeartbeatDataAzureBlob = {
  accessTier?: string | null | undefined;
  accountKind?: string | null | undefined;
  allowBlobPublicAccess?: boolean | null | undefined;
  blobDeleteRetentionDays?: number | null | undefined;
  blobDeleteRetentionEnabled?: boolean | null | undefined;
  blobEncryptionEnabled?: boolean | null | undefined;
  blobVersioningEnabled?: boolean | null | undefined;
  changeFeedEnabled?: boolean | null | undefined;
  changeFeedRetentionDays?: number | null | undefined;
  containerDeleteRetentionDays?: number | null | undefined;
  containerDeleteRetentionEnabled?: boolean | null | undefined;
  containerPublicAccess?: string | null | undefined;
  encryptionKeySource?: string | null | undefined;
  fileEncryptionEnabled?: boolean | null | undefined;
  location?: string | null | undefined;
  name: string;
  primaryLocation?: string | null | undefined;
  provisioningState?: string | null | undefined;
  publicNetworkAccess?: string | null | undefined;
  queueEncryptionEnabled?: boolean | null | undefined;
  resourceGroup?: string | null | undefined;
  secondaryLocation?: string | null | undefined;
  skuName?: string | null | undefined;
  skuTier?: string | null | undefined;
  status: StorageHeartbeatStatus;
  statusOfPrimary?: string | null | undefined;
  statusOfSecondary?: string | null | undefined;
  storageAccountName?: string | null | undefined;
  tableEncryptionEnabled?: boolean | null | undefined;
  backend: "azureBlob";
};

export type StorageHeartbeatDataGcpCloudStorage = {
  bucketId?: string | null | undefined;
  defaultKmsKeyName?: string | null | undefined;
  encryptionConfigPresent: boolean;
  lifecyclePresent: boolean;
  lifecycleRuleCount?: number | null | undefined;
  location?: string | null | undefined;
  locationType?: string | null | undefined;
  name: string;
  publicAccessPrevention?: string | null | undefined;
  retentionPeriod?: string | null | undefined;
  retentionPolicyEffectiveTime?: string | null | undefined;
  retentionPolicyIsLocked?: boolean | null | undefined;
  softDeleteEffectiveTime?: string | null | undefined;
  softDeleteRetentionDurationSeconds?: string | null | undefined;
  status: StorageHeartbeatStatus;
  storageClass?: string | null | undefined;
  uniformBucketLevelAccessEnabled?: boolean | null | undefined;
  uniformBucketLevelAccessLockedTime?: string | null | undefined;
  versioningEnabled?: boolean | null | undefined;
  backend: "gcpCloudStorage";
};

export type StorageHeartbeatDataAwsS3 = {
  blockPublicAcls?: boolean | null | undefined;
  blockPublicPolicy?: boolean | null | undefined;
  bucketAclPresent?: boolean | null | undefined;
  bucketLocation?: string | null | undefined;
  bucketPolicyPresent?: boolean | null | undefined;
  encryptionConfigPresent: boolean;
  encryptionEnabled?: boolean | null | undefined;
  ignorePublicAcls?: boolean | null | undefined;
  lifecyclePresent: boolean;
  lifecycleRuleCount?: number | null | undefined;
  name: string;
  publicAccessBlockPresent: boolean;
  region?: string | null | undefined;
  restrictPublicBuckets?: boolean | null | undefined;
  status: StorageHeartbeatStatus;
  versioningEnabled?: boolean | null | undefined;
  versioningStatus?: string | null | undefined;
  backend: "awsS3";
};

export type StorageHeartbeatData =
  | StorageHeartbeatDataAwsS3
  | StorageHeartbeatDataGcpCloudStorage
  | StorageHeartbeatDataAzureBlob
  | StorageHeartbeatDataLocal;

/** @internal */
export type StorageHeartbeatDataLocal$Outbound = {
  isDirectory?: boolean | null | undefined;
  modifiedAt?: string | null | undefined;
  path: string;
  pathExists: boolean;
  readonly?: boolean | null | undefined;
  status: StorageHeartbeatStatus$Outbound;
  backend: "local";
};

/** @internal */
export const StorageHeartbeatDataLocal$outboundSchema: z.ZodType<
  StorageHeartbeatDataLocal$Outbound,
  StorageHeartbeatDataLocal
> = z.object({
  isDirectory: z.nullable(z.boolean()).optional(),
  modifiedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  path: z.string(),
  pathExists: z.boolean(),
  readonly: z.nullable(z.boolean()).optional(),
  status: StorageHeartbeatStatus$outboundSchema,
  backend: z.literal("local"),
});

export function storageHeartbeatDataLocalToJSON(
  storageHeartbeatDataLocal: StorageHeartbeatDataLocal,
): string {
  return JSON.stringify(
    StorageHeartbeatDataLocal$outboundSchema.parse(storageHeartbeatDataLocal),
  );
}

/** @internal */
export type StorageHeartbeatDataAzureBlob$Outbound = {
  accessTier?: string | null | undefined;
  accountKind?: string | null | undefined;
  allowBlobPublicAccess?: boolean | null | undefined;
  blobDeleteRetentionDays?: number | null | undefined;
  blobDeleteRetentionEnabled?: boolean | null | undefined;
  blobEncryptionEnabled?: boolean | null | undefined;
  blobVersioningEnabled?: boolean | null | undefined;
  changeFeedEnabled?: boolean | null | undefined;
  changeFeedRetentionDays?: number | null | undefined;
  containerDeleteRetentionDays?: number | null | undefined;
  containerDeleteRetentionEnabled?: boolean | null | undefined;
  containerPublicAccess?: string | null | undefined;
  encryptionKeySource?: string | null | undefined;
  fileEncryptionEnabled?: boolean | null | undefined;
  location?: string | null | undefined;
  name: string;
  primaryLocation?: string | null | undefined;
  provisioningState?: string | null | undefined;
  publicNetworkAccess?: string | null | undefined;
  queueEncryptionEnabled?: boolean | null | undefined;
  resourceGroup?: string | null | undefined;
  secondaryLocation?: string | null | undefined;
  skuName?: string | null | undefined;
  skuTier?: string | null | undefined;
  status: StorageHeartbeatStatus$Outbound;
  statusOfPrimary?: string | null | undefined;
  statusOfSecondary?: string | null | undefined;
  storageAccountName?: string | null | undefined;
  tableEncryptionEnabled?: boolean | null | undefined;
  backend: "azureBlob";
};

/** @internal */
export const StorageHeartbeatDataAzureBlob$outboundSchema: z.ZodType<
  StorageHeartbeatDataAzureBlob$Outbound,
  StorageHeartbeatDataAzureBlob
> = z.object({
  accessTier: z.nullable(z.string()).optional(),
  accountKind: z.nullable(z.string()).optional(),
  allowBlobPublicAccess: z.nullable(z.boolean()).optional(),
  blobDeleteRetentionDays: z.nullable(z.int()).optional(),
  blobDeleteRetentionEnabled: z.nullable(z.boolean()).optional(),
  blobEncryptionEnabled: z.nullable(z.boolean()).optional(),
  blobVersioningEnabled: z.nullable(z.boolean()).optional(),
  changeFeedEnabled: z.nullable(z.boolean()).optional(),
  changeFeedRetentionDays: z.nullable(z.int()).optional(),
  containerDeleteRetentionDays: z.nullable(z.int()).optional(),
  containerDeleteRetentionEnabled: z.nullable(z.boolean()).optional(),
  containerPublicAccess: z.nullable(z.string()).optional(),
  encryptionKeySource: z.nullable(z.string()).optional(),
  fileEncryptionEnabled: z.nullable(z.boolean()).optional(),
  location: z.nullable(z.string()).optional(),
  name: z.string(),
  primaryLocation: z.nullable(z.string()).optional(),
  provisioningState: z.nullable(z.string()).optional(),
  publicNetworkAccess: z.nullable(z.string()).optional(),
  queueEncryptionEnabled: z.nullable(z.boolean()).optional(),
  resourceGroup: z.nullable(z.string()).optional(),
  secondaryLocation: z.nullable(z.string()).optional(),
  skuName: z.nullable(z.string()).optional(),
  skuTier: z.nullable(z.string()).optional(),
  status: StorageHeartbeatStatus$outboundSchema,
  statusOfPrimary: z.nullable(z.string()).optional(),
  statusOfSecondary: z.nullable(z.string()).optional(),
  storageAccountName: z.nullable(z.string()).optional(),
  tableEncryptionEnabled: z.nullable(z.boolean()).optional(),
  backend: z.literal("azureBlob"),
});

export function storageHeartbeatDataAzureBlobToJSON(
  storageHeartbeatDataAzureBlob: StorageHeartbeatDataAzureBlob,
): string {
  return JSON.stringify(
    StorageHeartbeatDataAzureBlob$outboundSchema.parse(
      storageHeartbeatDataAzureBlob,
    ),
  );
}

/** @internal */
export type StorageHeartbeatDataGcpCloudStorage$Outbound = {
  bucketId?: string | null | undefined;
  defaultKmsKeyName?: string | null | undefined;
  encryptionConfigPresent: boolean;
  lifecyclePresent: boolean;
  lifecycleRuleCount?: number | null | undefined;
  location?: string | null | undefined;
  locationType?: string | null | undefined;
  name: string;
  publicAccessPrevention?: string | null | undefined;
  retentionPeriod?: string | null | undefined;
  retentionPolicyEffectiveTime?: string | null | undefined;
  retentionPolicyIsLocked?: boolean | null | undefined;
  softDeleteEffectiveTime?: string | null | undefined;
  softDeleteRetentionDurationSeconds?: string | null | undefined;
  status: StorageHeartbeatStatus$Outbound;
  storageClass?: string | null | undefined;
  uniformBucketLevelAccessEnabled?: boolean | null | undefined;
  uniformBucketLevelAccessLockedTime?: string | null | undefined;
  versioningEnabled?: boolean | null | undefined;
  backend: "gcpCloudStorage";
};

/** @internal */
export const StorageHeartbeatDataGcpCloudStorage$outboundSchema: z.ZodType<
  StorageHeartbeatDataGcpCloudStorage$Outbound,
  StorageHeartbeatDataGcpCloudStorage
> = z.object({
  bucketId: z.nullable(z.string()).optional(),
  defaultKmsKeyName: z.nullable(z.string()).optional(),
  encryptionConfigPresent: z.boolean(),
  lifecyclePresent: z.boolean(),
  lifecycleRuleCount: z.nullable(z.int()).optional(),
  location: z.nullable(z.string()).optional(),
  locationType: z.nullable(z.string()).optional(),
  name: z.string(),
  publicAccessPrevention: z.nullable(z.string()).optional(),
  retentionPeriod: z.nullable(z.string()).optional(),
  retentionPolicyEffectiveTime: z.nullable(z.string()).optional(),
  retentionPolicyIsLocked: z.nullable(z.boolean()).optional(),
  softDeleteEffectiveTime: z.nullable(z.string()).optional(),
  softDeleteRetentionDurationSeconds: z.nullable(z.string()).optional(),
  status: StorageHeartbeatStatus$outboundSchema,
  storageClass: z.nullable(z.string()).optional(),
  uniformBucketLevelAccessEnabled: z.nullable(z.boolean()).optional(),
  uniformBucketLevelAccessLockedTime: z.nullable(z.string()).optional(),
  versioningEnabled: z.nullable(z.boolean()).optional(),
  backend: z.literal("gcpCloudStorage"),
});

export function storageHeartbeatDataGcpCloudStorageToJSON(
  storageHeartbeatDataGcpCloudStorage: StorageHeartbeatDataGcpCloudStorage,
): string {
  return JSON.stringify(
    StorageHeartbeatDataGcpCloudStorage$outboundSchema.parse(
      storageHeartbeatDataGcpCloudStorage,
    ),
  );
}

/** @internal */
export type StorageHeartbeatDataAwsS3$Outbound = {
  blockPublicAcls?: boolean | null | undefined;
  blockPublicPolicy?: boolean | null | undefined;
  bucketAclPresent?: boolean | null | undefined;
  bucketLocation?: string | null | undefined;
  bucketPolicyPresent?: boolean | null | undefined;
  encryptionConfigPresent: boolean;
  encryptionEnabled?: boolean | null | undefined;
  ignorePublicAcls?: boolean | null | undefined;
  lifecyclePresent: boolean;
  lifecycleRuleCount?: number | null | undefined;
  name: string;
  publicAccessBlockPresent: boolean;
  region?: string | null | undefined;
  restrictPublicBuckets?: boolean | null | undefined;
  status: StorageHeartbeatStatus$Outbound;
  versioningEnabled?: boolean | null | undefined;
  versioningStatus?: string | null | undefined;
  backend: "awsS3";
};

/** @internal */
export const StorageHeartbeatDataAwsS3$outboundSchema: z.ZodType<
  StorageHeartbeatDataAwsS3$Outbound,
  StorageHeartbeatDataAwsS3
> = z.object({
  blockPublicAcls: z.nullable(z.boolean()).optional(),
  blockPublicPolicy: z.nullable(z.boolean()).optional(),
  bucketAclPresent: z.nullable(z.boolean()).optional(),
  bucketLocation: z.nullable(z.string()).optional(),
  bucketPolicyPresent: z.nullable(z.boolean()).optional(),
  encryptionConfigPresent: z.boolean(),
  encryptionEnabled: z.nullable(z.boolean()).optional(),
  ignorePublicAcls: z.nullable(z.boolean()).optional(),
  lifecyclePresent: z.boolean(),
  lifecycleRuleCount: z.nullable(z.int()).optional(),
  name: z.string(),
  publicAccessBlockPresent: z.boolean(),
  region: z.nullable(z.string()).optional(),
  restrictPublicBuckets: z.nullable(z.boolean()).optional(),
  status: StorageHeartbeatStatus$outboundSchema,
  versioningEnabled: z.nullable(z.boolean()).optional(),
  versioningStatus: z.nullable(z.string()).optional(),
  backend: z.literal("awsS3"),
});

export function storageHeartbeatDataAwsS3ToJSON(
  storageHeartbeatDataAwsS3: StorageHeartbeatDataAwsS3,
): string {
  return JSON.stringify(
    StorageHeartbeatDataAwsS3$outboundSchema.parse(storageHeartbeatDataAwsS3),
  );
}

/** @internal */
export type StorageHeartbeatData$Outbound =
  | StorageHeartbeatDataAwsS3$Outbound
  | StorageHeartbeatDataGcpCloudStorage$Outbound
  | StorageHeartbeatDataAzureBlob$Outbound
  | StorageHeartbeatDataLocal$Outbound;

/** @internal */
export const StorageHeartbeatData$outboundSchema: z.ZodType<
  StorageHeartbeatData$Outbound,
  StorageHeartbeatData
> = z.union([
  z.lazy(() => StorageHeartbeatDataAwsS3$outboundSchema),
  z.lazy(() => StorageHeartbeatDataGcpCloudStorage$outboundSchema),
  z.lazy(() => StorageHeartbeatDataAzureBlob$outboundSchema),
  z.lazy(() => StorageHeartbeatDataLocal$outboundSchema),
]);

export function storageHeartbeatDataToJSON(
  storageHeartbeatData: StorageHeartbeatData,
): string {
  return JSON.stringify(
    StorageHeartbeatData$outboundSchema.parse(storageHeartbeatData),
  );
}
