packages:
  - ai-chatbot-ts
  - ai-quickstart-ts
  - basic-worker-ts
  - basic-worker-rs
  - remote-worker-ts
  - data-connector-ts
  - event-pipeline-ts
  - webhook-api-ts
  - nextjs-app
  - byoc-database
  - endpoint-agent
  - full-stack-microservices
  - full-stack-microservices/services/*
  - command-routing-ts
  - command-routing-ts/services/*
  - github-agent/packages/remote-agent
