packages:
  - basic-worker-ts
  - basic-worker-rs
  - remote-worker-ts
  - data-connector-ts
  - event-pipeline-ts
  - webhook-api-ts
  - byoc-database
  - endpoint-agent
  - github-agent/packages/remote-agent
