/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4dfb7f032a73
 */

import * as z from "zod/v4";

export type GetChildDeploymentPolicyGlobals = {
  /**
   * Workspace name. Platform API keys already select a workspace; other authentication methods can configure it once on the SDK client.
   */
  workspace?: string | undefined;
};

export type GetChildDeploymentPolicyRequest = {
  /**
   * Unique identifier for the deployment.
   */
  id: string;
};

/** @internal */
export type GetChildDeploymentPolicyRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetChildDeploymentPolicyRequest$outboundSchema: z.ZodType<
  GetChildDeploymentPolicyRequest$Outbound,
  GetChildDeploymentPolicyRequest
> = z.object({
  id: z.string(),
});

export function getChildDeploymentPolicyRequestToJSON(
  getChildDeploymentPolicyRequest: GetChildDeploymentPolicyRequest,
): string {
  return JSON.stringify(
    GetChildDeploymentPolicyRequest$outboundSchema.parse(
      getChildDeploymentPolicyRequest,
    ),
  );
}
