/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deploymentGetInfo } from "../funcs/deploymentGetInfo.js";
import { deploymentPlanCompute } from "../funcs/deploymentPlanCompute.js";
import { deploymentPrepareStack } from "../funcs/deploymentPrepareStack.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Deployment extends ClientSDK {
  /**
   * Get deployment information for the deployment portal. Accepts both deployment-scoped and deployment-group-scoped API keys. Returns project information, package status/outputs, and either deployment or deployment group details depending on the token type. Poll this endpoint to check if packages are ready.
   */
  async getInfo(
    request?: operations.GetDeploymentInfoRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.DeploymentInfo> {
    return unwrapAsync(deploymentGetInfo(
      this,
      request,
      options,
    ));
  }

  /**
   * Plan deployment compute for the active release before stack preparation. The response contains recommended machine and scale choices for cloud compute pools.
   */
  async planCompute(
    request?: operations.PlanDeploymentComputeRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.DeploymentComputePlan> {
    return unwrapAsync(deploymentPlanCompute(
      this,
      request,
      options,
    ));
  }

  /**
   * Prepare the active release stack for a deployment portal setup session. The response contains the generated stack shape plus setup compatibility metadata.
   */
  async prepareStack(
    request?: operations.PrepareDeploymentStackRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PreparedDeploymentStack> {
    return unwrapAsync(deploymentPrepareStack(
      this,
      request,
      options,
    ));
  }
}
