/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deploymentsCreate } from "../funcs/deploymentsCreate.js"
import { deploymentsCreateToken } from "../funcs/deploymentsCreateToken.js"
import { deploymentsDelete } from "../funcs/deploymentsDelete.js"
import { deploymentsGet } from "../funcs/deploymentsGet.js"
import { deploymentsGetInfo } from "../funcs/deploymentsGetInfo.js"
import { deploymentsGetStats } from "../funcs/deploymentsGetStats.js"
import { deploymentsImport } from "../funcs/deploymentsImport.js"
import { deploymentsList } from "../funcs/deploymentsList.js"
import { deploymentsListFilterDeploymentGroups } from "../funcs/deploymentsListFilterDeploymentGroups.js"
import { deploymentsListFilterPlatforms } from "../funcs/deploymentsListFilterPlatforms.js"
import { deploymentsPinRelease } from "../funcs/deploymentsPinRelease.js"
import { deploymentsRedeploy } from "../funcs/deploymentsRedeploy.js"
import { deploymentsRetry } from "../funcs/deploymentsRetry.js"
import { deploymentsUpdateEnvironmentVariables } from "../funcs/deploymentsUpdateEnvironmentVariables.js"
import { ClientSDK, type RequestOptions } from "../lib/sdks.js"
import type * as models from "../models/index.js"
import type * as operations from "../models/operations/index.js"
import { unwrapAsync } from "../types/fp.js"

export class Deployments extends ClientSDK {
  /**
   * Retrieve all agents.
   */
  async list(
    request?: operations.ListDeploymentsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListDeploymentsResponse> {
    return unwrapAsync(deploymentsList(this, request, options))
  }

  /**
   * Create a new agent. Deployment group tokens automatically use their group. Workspace/project tokens must provide deploymentGroupId.
   */
  async create(
    request?: operations.CreateDeploymentRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.CreateDeploymentResponse> {
    return unwrapAsync(deploymentsCreate(this, request, options))
  }

  /**
   * Get aggregated agent statistics. Returns total count and breakdown by status.
   */
  async getStats(
    request?: operations.GetDeploymentStatsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.DeploymentStats> {
    return unwrapAsync(deploymentsGetStats(this, request, options))
  }

  /**
   * List distinct platforms used by agents. Used for filter dropdowns.
   */
  async listFilterPlatforms(
    request?: operations.ListDeploymentFilterPlatformsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListDeploymentFilterPlatformsResponse> {
    return unwrapAsync(deploymentsListFilterPlatforms(this, request, options))
  }

  /**
   * List deployment groups with agent counts. Used for filter dropdowns.
   */
  async listFilterDeploymentGroups(
    request?: operations.ListDeploymentFilterDeploymentGroupsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListDeploymentFilterDeploymentGroupsResponse> {
    return unwrapAsync(deploymentsListFilterDeploymentGroups(this, request, options))
  }

  /**
   * Retrieve an agent by ID.
   */
  async get(
    request: operations.GetDeploymentRequest,
    options?: RequestOptions,
  ): Promise<models.DeploymentDetailResponse> {
    return unwrapAsync(deploymentsGet(this, request, options))
  }

  /**
   * Delete an agent by ID. This can be used to start deletion or retry failed deletions.
   */
  async delete(
    request: operations.DeleteDeploymentRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteDeploymentResponse> {
    return unwrapAsync(deploymentsDelete(this, request, options))
  }

  /**
   * Get deployment connection information including ARC endpoint and resource URLs.
   */
  async getInfo(
    request: operations.GetDeploymentConnectionInfoRequest,
    options?: RequestOptions,
  ): Promise<models.DeploymentConnectionInfo> {
    return unwrapAsync(deploymentsGetInfo(this, request, options))
  }

  /**
   * Import an agent from existing infrastructure (e.g., CloudFormation stack). The agent ID is automatically generated.
   */
  async import(
    request?: operations.ImportDeploymentRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.Deployment> {
    return unwrapAsync(deploymentsImport(this, request, options))
  }

  /**
   * Redeploy a running agent with the same release and fresh environment variables. Sets status to update-pending.
   */
  async redeploy(
    request: operations.RedeployDeploymentRequest,
    options?: RequestOptions,
  ): Promise<operations.RedeployDeploymentResponse> {
    return unwrapAsync(deploymentsRedeploy(this, request, options))
  }

  /**
   * Pin or unpin agent to a specific release. Only works for running agents. Controller will automatically trigger update to target release.
   */
  async pinRelease(
    request: operations.PinDeploymentReleaseRequest,
    options?: RequestOptions,
  ): Promise<operations.PinDeploymentReleaseResponse> {
    return unwrapAsync(deploymentsPinRelease(this, request, options))
  }

  /**
   * Retry a failed agent operation. Uses alien-infra's retry mechanisms to resume from exact failure point.
   */
  async retry(
    request: operations.RetryDeploymentRequest,
    options?: RequestOptions,
  ): Promise<operations.RetryDeploymentResponse> {
    return unwrapAsync(deploymentsRetry(this, request, options))
  }

  /**
   * Update an agent's environment variables. If the agent is running and not locked, the status will be changed to update-pending to trigger a deployment.
   */
  async updateEnvironmentVariables(
    request: operations.UpdateDeploymentEnvironmentVariablesRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateDeploymentEnvironmentVariablesResponse> {
    return unwrapAsync(deploymentsUpdateEnvironmentVariables(this, request, options))
  }

  /**
   * Create an agent token (agent-scoped API key) for this agent. The agent must exist before creating a token.
   */
  async createToken(
    request: operations.CreateDeploymentTokenRequest,
    options?: RequestOptions,
  ): Promise<models.CreateDeploymentTokenResponse> {
    return unwrapAsync(deploymentsCreateToken(this, request, options))
  }
}
