apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alien-agent.fullname" . }}
  labels:
    {{- include "alien-agent.labels" . | nindent 4 }}
type: Opaque
data:
  sync-token: {{ .Values.syncToken | b64enc | quote }}
  encryption-key: {{ .Values.encryptionKey | b64enc | quote }}
