//! Network infrastructure controllers for VPC/VNet management.
//!
//! This module provides platform-specific controllers for managing network infrastructure
//! including VPCs, subnets, Internet Gateways, NAT Gateways, route tables, and security groups.
//!
//! The Network resource is always auto-generated by the `NetworkMutation` preflight based on
//! `StackSettings.network`. Users configure network settings in their stack settings,
//! not directly as resources.

#[cfg(feature = "aws")]
mod aws;
#[cfg(feature = "aws")]
pub use aws::*;

#[cfg(feature = "aws")]
mod aws_import;
#[cfg(feature = "aws")]
pub use aws_import::AwsNetworkImporter;

#[cfg(feature = "gcp")]
mod gcp;
#[cfg(feature = "gcp")]
pub use gcp::*;

#[cfg(feature = "gcp")]
mod gcp_import;
#[cfg(feature = "gcp")]
pub use gcp_import::GcpNetworkImporter;

#[cfg(feature = "azure")]
mod azure;
#[cfg(feature = "azure")]
pub use azure::*;

#[cfg(feature = "azure")]
mod azure_import;
#[cfg(feature = "azure")]
pub use azure_import::AzureNetworkImporter;
