/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type SignDeploymentBundleRequest = {
  /**
   * Deployment ID
   */
  id: string;
  bundleSignatureRequest: models.BundleSignatureRequest;
};

/** @internal */
export type SignDeploymentBundleRequest$Outbound = {
  id: string;
  BundleSignatureRequest: models.BundleSignatureRequest$Outbound;
};

/** @internal */
export const SignDeploymentBundleRequest$outboundSchema: z.ZodType<
  SignDeploymentBundleRequest$Outbound,
  SignDeploymentBundleRequest
> = z.object({
  id: z.string(),
  bundleSignatureRequest: models.BundleSignatureRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    bundleSignatureRequest: "BundleSignatureRequest",
  });
});

export function signDeploymentBundleRequestToJSON(
  signDeploymentBundleRequest: SignDeploymentBundleRequest,
): string {
  return JSON.stringify(
    SignDeploymentBundleRequest$outboundSchema.parse(
      signDeploymentBundleRequest,
    ),
  );
}
