/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UploadCompleteRequest = {
  /**
   * Command identifier
   */
  commandId: string;
  uploadCompleteRequest: models.UploadCompleteRequest;
};

/** @internal */
export type UploadCompleteRequest$Outbound = {
  command_id: string;
  UploadCompleteRequest: models.UploadCompleteRequest$Outbound;
};

/** @internal */
export const UploadCompleteRequest$outboundSchema: z.ZodType<
  UploadCompleteRequest$Outbound,
  UploadCompleteRequest
> = z.object({
  commandId: z.string(),
  uploadCompleteRequest: models.UploadCompleteRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    commandId: "command_id",
    uploadCompleteRequest: "UploadCompleteRequest",
  });
});

export function uploadCompleteRequestToJSON(
  uploadCompleteRequest: UploadCompleteRequest,
): string {
  return JSON.stringify(
    UploadCompleteRequest$outboundSchema.parse(uploadCompleteRequest),
  );
}
