name: Renovate

on:
  schedule:
    - cron: "47 * * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: renovate
  cancel-in-progress: false

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.4.2"

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.98.1"

      - name: Install Renovate
        run: npm install --global renovate@44.61.1

      - name: Run Renovate
        env:
          RENOVATE_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          RENOVATE_CONFIG_FILE: ${{ github.workspace }}/.github/renovate-bot.js
        run: renovate
